Number_Properties_Priority = 2.0

Number_Properties = {
}

String_Properties_Priority = 2.0

String_Properties = {
	path_build = [[data:scripts/races/kushan/scripts/sp_build.lua]],

	generic_sp_build_restrict = "kus_scout5,kus_interceptor5,kus_attackbomber5,kus_lightcorvette3,kus_heavycorvette3,kus_multiguncorvette3,Kus_Autogunl,Kus_Autoguns,Kus_Hw2AssaultFrigate,Kus_Hw2IonCannonFrigate,Kus_Hw2SupportFrigate,Kus_Hw2DroneFrigate,Kus_Hw2Destroyer,Kus_Hw2MissileDestroyer,Kus_Hw2HeavyCruiser",

	generic_sp_research_restrict = "cpuplayers_defensive,cpuplayers_aggressive,cpuplayers_dynamic,cpuplayers_norushtime5,cpuplayers_norushtime10,cpuplayers_norushtime15,AllShipBuildSpeed,AllShipBuildSpeedHard,AllShipBuildSpeedExpert,ResourceCollectionRateHard,ResourceCollectionRateExpert,MissileDestroyerVolley,HeavyCorvetteAttackBurst,Hyperspace,AttackBomberImprovedBombs,MothershipHealthUpgrade1,MothershipMAXSPEEDUpgrade1,MothershipBUILDSPEEDUpgrade1,MothershipBUILDSPEEDUpgrade2,MothershipBUILDSPEEDUpgrade3,MothershipBUILDSPEEDUpgrade4,MothershipBUILDSPEEDUpgrade5,CarrierHealthUpgrade1,CarrierMAXSPEEDUpgrade1,CarrierBUILDSPEEDUpgrade1,CarrierBUILDSPEEDUpgrade2,CarrierBUILDSPEEDUpgrade3,CarrierBUILDSPEEDUpgrade4,CarrierBUILDSPEEDUpgrade5,ScoutMAXSPEEDUpgrade1,InterceptorMAXSPEEDUpgrade1,DefenderMAXSPEEDUpgrade1,AttackBomberMAXSPEEDUpgrade1,CloakerMAXSPEEDUpgrade1,RepairCorvetteMAXSPEEDUpgrade1,SalvageCorvetteMAXSPEEDUpgrade1,LightCorvetteMAXSPEEDUpgrade1,HeavyCorvetteMAXSPEEDUpgrade1,MultigunCorvetteMAXSPEEDUpgrade1,MinelayerCorvetteMAXSPEEDUpgrade1,SupportFrigateHealthUpgrade1,SupportFrigateMAXSPEEDUpgrade1,AssaultFrigateHealthUpgrade1,AssaultFrigateMAXSPEEDUpgrade1,IonCannonFrigateHealthUpgrade1,IonCannonFrigateMAXSPEEDUpgrade1,DroneFrigateHealthUpgrade1,DroneFrigateMAXSPEEDUpgrade1,HeavycruiserHealthUpgrade1,HeavycruiserMAXSPEEDUpgrade1,DestroyerHealthUpgrade1,DestroyerMAXSPEEDUpgrade1,MissileDestroyerHealthUpgrade1,MissileDestroyerMAXSPEEDUpgrade1,ScoutMAXSPEEDUpgrade2,InterceptorMAXSPEEDUpgrade2,DefenderMAXSPEEDUpgrade2,AttackBomberMAXSPEEDUpgrade2,CloakerMAXSPEEDUpgrade2,RepairCorvetteMAXSPEEDUpgrade2,SalvageCorvetteMAXSPEEDUpgrade2,LightCorvetteMAXSPEEDUpgrade2,HeavyCorvetteMAXSPEEDUpgrade2,MultigunCorvetteMAXSPEEDUpgrade2,MinelayerCorvetteMAXSPEEDUpgrade2,SupportFrigateHealthUpgrade2,SupportFrigateMAXSPEEDUpgrade2,AssaultFrigateHealthUpgrade2,AssaultFrigateMAXSPEEDUpgrade2,IonCannonFrigateHealthUpgrade2,IonCannonFrigateMAXSPEEDUpgrade2,DroneFrigateHealthUpgrade2,DroneFrigateMAXSPEEDUpgrade2,HeavycruiserHealthUpgrade2,HeavycruiserMAXSPEEDUpgrade2,DestroyerHealthUpgrade2,DestroyerMAXSPEEDUpgrade2,MissileDestroyerHealthUpgrade2,MissileDestroyerMAXSPEEDUpgrade2,MothershipHW2HealthBaseUp",
}
