Number_Properties_Priority = 2.0

Number_Properties = {
	dm_challenge_research_baseline = 4,
}

String_Properties_Priority = 2.0
 
String_Properties = {
	dm_carriersonly_build_restrict = "hgn_shipyard",
					
	dm_carriersonly_research_restrict = "MothershipHealthUpgrade1,MothershipMAXSPEEDUpgrade1,MothershipBUILDSPEEDUpgrade1,ShipyardHealthUpgrade1,ShipyardMAXSPEEDUpgrade1,ShipyardBUILDSPEEDUpgrade1",

	generic_mp_build_restrict = "	Hgn_MS_Production_CorvetteMover,Hgn_PulsarFighter,Hgn_HeavyAssaultCorvette,Hgn_PulsarTurret,Hgn_HW1AssaultFrigate,Hgn_HW1TorpedoFrigate,Hgn_HW1IonCannonFrigate,Hgn_HW1Destroyer,Hgn_HW1Battlecruiser,Hgn_Hw1GunTurret,Hgn_Hw1IonTurret,Kpr_Mover,Hgn_Shipyard_SPG",

	generic_mp_research_restrict = "PulsarFighterMAXSPEEDUpgrade1,PulsarFighterMAXSPEEDUpgrade2,HeavyAssaultCorvetteHealthUpgrade1,HeavyAssaultCorvetteHealthUpgrade2,HeavyAssaultCorvetteMAXSPEEDUpgrade1,HeavyAssaultCorvetteMAXSPEEDUpgrade2,PulsarTurretHealthUpgrade1,PulsarTurretHealthUpgrade2,AssaultCorvetteEliteWeaponUpgrade,AttackBomberEliteWeaponUpgrade,SensorsDowngrade1,SensorsDowngrade2,SensorsDowngrade3,SensorsBackToNormal1,SensorsBackToNormal2,SensorsBackToNormal3,MoverHealthDowngrade,MoverHealthUpgrade,FrigateHealthUpgradeSPGAME,DamageMoverTech,KeeperHealthUpgradeSPGAME_LOW,KeeperHealthUpgradeSPGAME_MED,KeeperHealthUpgradeSPGAME_HIGH,KeeperWeaponUpgradeSPGAME_M10_LVL_1,KeeperWeaponUpgradeSPGAME_M10_LVL_2,KeeperWeaponUpgradeSPGAME_M10_LVL_3,KeeperWeaponUpgradeSPGAME_M10_LVL_4,KeeperWeaponUpgradeSPGAME_M10_LVL_5,KeeperWeaponUpgradeSPGAME_M10_LVL_6,KeeperHealthUpgradeSPGAME_M10_LVL_1,KeeperHealthUpgradeSPGAME_M10_LVL_2,KeeperHealthUpgradeSPGAME_M10_LVL_3,AttackDroidHealthUpgradeSPGAME_LOW,AttackDroidHealthUpgradeSPGAME_MED,AttackDroidHealthUpgradeSPGAME_HIGH,AttackDroidWeaponUpgradeSPGAME_LOW,AttackDroidWeaponUpgradeSPGAME_MED,AttackDroidWeaponUpgradeSPGAME_HIGH,RadiationDefenseField",	

	Experimental_research_unrestrict =  "PulsarFighterMAXSPEEDUpgrade1,PulsarFighterMAXSPEEDUpgrade2,HeavyAssaultCorvetteHealthUpgrade1,HeavyAssaultCorvetteHealthUpgrade2,HeavyAssaultCorvetteMAXSPEEDUpgrade1,HeavyAssaultCorvetteMAXSPEEDUpgrade2,PulsarTurretHealthUpgrade1,PulsarTurretHealthUpgrade2,AssaultCorvetteEliteWeaponUpgrade,AttackBomberEliteWeaponUpgrade,FrigateHealthUpgradeSPGAME,RadiationDefenseField",
	
	Experimental_build_unrestrict =  "Hgn_MS_Production_CorvetteMover,Kpr_Mover,Hgn_Shipyard_SPG,Hgn_PulsarFighter,Hgn_HeavyAssaultCorvette,Hgn_PulsarTurret",
	
	HW1Upgrades_build_unrestrict =  "Hgn_HW1AssaultFrigate,Hgn_HW1TorpedoFrigate,Hgn_HW1IonCannonFrigate,Hgn_HW1Destroyer,Hgn_HW1Battlecruiser,Hgn_Hw1GunTurret,Hgn_Hw1IonTurret",

	HW1Upgrades_build_restrict =  "Hgn_AssaultFrigate,Hgn_TorpedoFrigate,Hgn_IonCannonFrigate,Hgn_Destroyer,Hgn_Battlecruiser,Hgn_GunTurret,Hgn_IonTurret",

	HW2noUpgrades_research_restrict =  "AttackBomberImprovedBombs,ImprovedTorpedo,MothershipHealthUpgrade1,MothershipHealthUpgrade2,MothershipMAXSPEEDUpgrade1,MothershipMAXSPEEDUpgrade2,MothershipBUILDSPEEDUpgrade1,CarrierHealthUpgrade1,CarrierHealthUpgrade2,CarrierMAXSPEEDUpgrade1,CarrierMAXSPEEDUpgrade2,CarrierBUILDSPEEDUpgrade1,InterceptorMAXSPEEDUpgrade1,InterceptorMAXSPEEDUpgrade2,AttackBomberMAXSPEEDUpgrade1,AttackBomberMAXSPEEDUpgrade2,AssaultCorvetteHealthUpgrade1,AssaultCorvetteHealthUpgrade2,AssaultCorvetteMAXSPEEDUpgrade1,AssaultCorvetteMAXSPEEDUpgrade2,PulsarCorvetteHealthUpgrade1,PulsarCorvetteHealthUpgrade2,PulsarCorvetteMAXSPEEDUpgrade1,PulsarCorvetteMAXSPEEDUpgrade2,TorpedoFrigateHealthUpgrade1,TorpedoFrigateHealthUpgrade2,TorpedoFrigateMAXSPEEDUpgrade1,TorpedoFrigateMAXSPEEDUpgrade2,IonCannonFrigateHealthUpgrade1,IonCannonFrigateHealthUpgrade2,IonCannonFrigateMAXSPEEDUpgrade1,IonCannonFrigateMAXSPEEDUpgrade2,AssaultFrigateHealthUpgrade1,AssaultFrigateHealthUpgrade2,AssaultFrigateMAXSPEEDUpgrade1,AssaultFrigateMAXSPEEDUpgrade2,BattlecruiserHealthUpgrade1,BattlecruiserHealthUpgrade2,BattlecruiserMAXSPEEDUpgrade1,BattlecruiserMAXSPEEDUpgrade2,DestroyerHealthUpgrade1,DestroyerHealthUpgrade2,DestroyerMAXSPEEDUpgrade1,DestroyerMAXSPEEDUpgrade2,GunTurretHealthUpgrade1,GunTurretHealthUpgrade2,IonTurretHealthUpgrade1,IonTurretHealthUpgrade2,ResourceCollectorHealthUpgrade1,ResourceCollectorHealthUpgrade2,ResourceControllerHealthUpgrade1,ResourceControllerHealthUpgrade2,HyperspaceCostUpgrade1,HyperspaceCostUpgrade2,ShipyardHealthUpgrade1,ShipyardHealthUpgrade2,ShipyardMAXSPEEDUpgrade1,ShipyardMAXSPEEDUpgrade2,ShipyardBUILDSPEEDUpgrade1",

	HW1Balance_research_restrict =  "AttackBomberImprovedBombs,ImprovedTorpedo,MothershipHealthUpgrade1,MothershipHealthUpgrade2,MothershipMAXSPEEDUpgrade1,MothershipMAXSPEEDUpgrade2,MothershipBUILDSPEEDUpgrade1,CarrierHealthUpgrade1,CarrierHealthUpgrade2,CarrierMAXSPEEDUpgrade1,CarrierMAXSPEEDUpgrade2,CarrierBUILDSPEEDUpgrade1,InterceptorMAXSPEEDUpgrade1,InterceptorMAXSPEEDUpgrade2,AttackBomberMAXSPEEDUpgrade1,AttackBomberMAXSPEEDUpgrade2,AssaultCorvetteHealthUpgrade1,AssaultCorvetteHealthUpgrade2,AssaultCorvetteMAXSPEEDUpgrade1,AssaultCorvetteMAXSPEEDUpgrade2,PulsarCorvetteHealthUpgrade1,PulsarCorvetteHealthUpgrade2,PulsarCorvetteMAXSPEEDUpgrade1,PulsarCorvetteMAXSPEEDUpgrade2,TorpedoFrigateHealthUpgrade1,TorpedoFrigateHealthUpgrade2,TorpedoFrigateMAXSPEEDUpgrade1,TorpedoFrigateMAXSPEEDUpgrade2,IonCannonFrigateHealthUpgrade1,IonCannonFrigateHealthUpgrade2,IonCannonFrigateMAXSPEEDUpgrade1,IonCannonFrigateMAXSPEEDUpgrade2,AssaultFrigateHealthUpgrade1,AssaultFrigateHealthUpgrade2,AssaultFrigateMAXSPEEDUpgrade1,AssaultFrigateMAXSPEEDUpgrade2,BattlecruiserHealthUpgrade1,BattlecruiserHealthUpgrade2,BattlecruiserMAXSPEEDUpgrade1,BattlecruiserMAXSPEEDUpgrade2,DestroyerHealthUpgrade1,DestroyerHealthUpgrade2,DestroyerMAXSPEEDUpgrade1,DestroyerMAXSPEEDUpgrade2,GunTurretHealthUpgrade1,GunTurretHealthUpgrade2,IonTurretHealthUpgrade1,IonTurretHealthUpgrade2,ResourceCollectorHealthUpgrade1,ResourceCollectorHealthUpgrade2,ResourceControllerHealthUpgrade1,ResourceControllerHealthUpgrade2,HyperspaceCostUpgrade1,HyperspaceCostUpgrade2,ShipyardHealthUpgrade1,ShipyardHealthUpgrade2,ShipyardMAXSPEEDUpgrade1,ShipyardMAXSPEEDUpgrade2,ShipyardBUILDSPEEDUpgrade1",

	HW1Balance_build_unrestrict =  "Hgn_HW1AssaultFrigate,Hgn_HW1TorpedoFrigate,Hgn_HW1IonCannonFrigate,Hgn_HW1Destroyer,Hgn_HW1Battlecruiser,Hgn_Hw1GunTurret,Hgn_Hw1IonTurret",

	HW1Balance_build_restrict =  "Hgn_AssaultFrigate,Hgn_TorpedoFrigate,Hgn_IonCannonFrigate,Hgn_Destroyer,Hgn_Battlecruiser,Hgn_GunTurret,Hgn_IonTurret",
}
