Number_Properties_Priority = 2.0

Number_Properties = {
	dm_challenge_research_baseline = 4,
}

String_Properties_Priority = 2.0
 
String_Properties = {
	dm_carriersonly_build_restrict = "vgr_shipyard",
	
	dm_carriersonly_research_restrict = "MothershipBUILDSPEEDUpgrade1",

	generic_mp_build_restrict = "	Vgr_Hw1AssaultFrigate,Vgr_Hw1HeavyMissileFrigate,Vgr_Hw1InfiltratorFrigate,Vgr_Hw1Destroyer,Vgr_Hw1BattleCruiser,Vgr_PlanetKillerMissile",

	generic_mp_research_restrict = "WeakVgrHeavyMissiles,HyperspaceRecoveryTimeUpgradeSPGAME,HyperspaceTransitionTimeUpgradeSPGAME,VaygrCarrierHealthRegenDowngrade,ShipyardSpeedDowngradeSPGAME,SuperCapHealthUpgradeSPGAME,VaygrFrigateHealthUpgradeSPGAME,VaygrFrigateHealthRegenDowngradeSPGAME,CorvetteHealthUpgradeSPGAME,ExtraStrongVgrHeavyMissilesSPGAME,VaygrCaptureHack,VaygrReduceCaptureHack,VaygrRadiationImmunityHack,VaygrCarrierHealthUpgrade",	
	
	Experimental_research_unrestrict =  "CorvetteHealthUpgradeSPGAME,ExtraStrongVgrHeavyMissilesSPGAME,VaygrRadiationImmunityHack",

	HW1Upgrades_build_unrestrict =  "Vgr_Hw1AssaultFrigate,Vgr_Hw1HeavyMissileFrigate,Vgr_Hw1InfiltratorFrigate,Vgr_Hw1Destroyer,Vgr_Hw1BattleCruiser,Vgr_Hw1WeaponPlatform_gun,Vgr_Hw1WeaponPlatform_missile",

	HW1Upgrades_build_restrict =  "Vgr_AssaultFrigate,Vgr_HeavyMissileFrigate,Vgr_InfiltratorFrigate,Vgr_Destroyer,Vgr_BattleCruiser,Vgr_WeaponPlatform_gun,Vgr_WeaponPlatform_missile",

	HW2noUpgrades_research_restrict =  "BomberImprovedBombs,MothershipBUILDSPEEDUpgrade1,SuperCapHealthUpgrade1,SuperCapHealthUpgrade2,SuperCapSpeedUpgrade1,SuperCapSpeedUpgrade2,CarrierBUILDSPEEDUpgrade1,ShipyardBUILDSPEEDUpgrade1,FighterspeedUpgrade1,FighterspeedUpgrade2,CorvetteHealthUpgrade1,CorvetteHealthUpgrade2,CorvetteSpeedUpgrade1,CorvetteSpeedUpgrade2,FrigateHealthUpgrade1,FrigateHealthUpgrade2,FrigateSpeedUpgrade1,SpeedUpgrade2,PlatformHealthUpgrade1,PlatformHealthUpgrade2,UtilityHealthUpgrade1,UtilityHealthUpgrade2",

	HW1Balance_research_restrict =  "BomberImprovedBombs,MothershipBUILDSPEEDUpgrade1,SuperCapHealthUpgrade1,SuperCapHealthUpgrade2,SuperCapSpeedUpgrade1,SuperCapSpeedUpgrade2,CarrierBUILDSPEEDUpgrade1,ShipyardBUILDSPEEDUpgrade1,FighterspeedUpgrade1,FighterspeedUpgrade2,CorvetteHealthUpgrade1,CorvetteHealthUpgrade2,CorvetteSpeedUpgrade1,CorvetteSpeedUpgrade2,FrigateHealthUpgrade1,FrigateHealthUpgrade2,FrigateSpeedUpgrade1,SpeedUpgrade2,PlatformHealthUpgrade1,PlatformHealthUpgrade2,UtilityHealthUpgrade1,UtilityHealthUpgrade2",

	HW1Balance_build_unrestrict =  "Vgr_Hw1AssaultFrigate,Vgr_Hw1HeavyMissileFrigate,Vgr_Hw1InfiltratorFrigate,Vgr_Hw1Destroyer,Vgr_Hw1BattleCruiser,Vgr_Hw1WeaponPlatform_gun,Vgr_Hw1WeaponPlatform_missile",

	HW1Balance_build_restrict =  "Vgr_AssaultFrigate,Vgr_HeavyMissileFrigate,Vgr_InfiltratorFrigate,Vgr_Destroyer,Vgr_BattleCruiser,Vgr_WeaponPlatform_gun,Vgr_WeaponPlatform_missile",
}
