Number_Properties_Priority = 2.0

Number_Properties = {
}

String_Properties_Priority = 2.0

String_Properties = {
	generic_sp_build_restrict = "tur_fighter5,tur_hw2ionarrayfrigate,tur_hw2p1mothership,Tur_Autogunl,Tur_Autoguns,Tur_Hw2Autogunl,Tur_Hw2Autoguns,tur_carrier,tur_hw2carrier",

	generic_sp_research_restrict = "CapitalProduction,cpuplayers_defensive,cpuplayers_aggressive,cpuplayers_dynamic,cpuplayers_norushtime5,cpuplayers_norushtime10,cpuplayers_norushtime15,AllShipBuildSpeed,AllShipBuildSpeedHard,AllShipBuildSpeedExpert,ResourceCollectionRateHard,ResourceCollectionRateExpert,FighterMAXSPEEDUpgrade1,StandardCorvetteMAXSPEEDUpgrade1,MissileCorvetteMAXSPEEDUpgrade1,IonArrayFrigateHealthUpgrade1,IonArrayFrigateMAXSPEEDUpgrade1,P1MothershipHealthUpgrade1,P1MothershipMAXSPEEDUpgrade1,MissileCorvetteVolley",
}
