Number_Properties_Priority = 2.0

Number_Properties = {
	dm_challenge_research_baseline = 4,
}

String_Properties_Priority = 2.0

String_Properties = {
		dm_carriersonly_build_restrict = "hgn_shipyard",
					
	dm_carriersonly_research_restrict = "MothershipHealthUpgrade1,MothershipMAXSPEEDUpgrade1,MothershipBUILDSPEEDUpgrade1,ShipyardHealthUpgrade1,ShipyardMAXSPEEDUpgrade1,ShipyardBUILDSPEEDUpgrade1",

	generic_mp_build_restrict = "	Hgn_MS_Production_CorvetteMover,Hgn_PulsarFighter,Hgn_HeavyAssaultCorvette,Hgn_PulsarTurret,Hgn_HW1AssaultFrigate,Hgn_HW1TorpedoFrigate,Hgn_HW1IonCannonFrigate,Hgn_HW1Destroyer,Hgn_HW1Battlecruiser,Hgn_Hw1GunTurret,Hgn_Hw1IonTurret,Kpr_Mover,Hgn_Shipyard_SPG",

	generic_mp_research_restrict = "PulsarFighterMAXSPEEDUpgrade1,PulsarFighterMAXSPEEDUpgrade2,HeavyAssaultCorvetteHealthUpgrade1,HeavyAssaultCorvetteHealthUpgrade2,HeavyAssaultCorvetteMAXSPEEDUpgrade1,HeavyAssaultCorvetteMAXSPEEDUpgrade2,PulsarTurretHealthUpgrade1,PulsarTurretHealthUpgrade2,AssaultCorvetteEliteWeaponUpgrade,AttackBomberEliteWeaponUpgrade,SensorsDowngrade1,SensorsDowngrade2,SensorsDowngrade3,SensorsBackToNormal1,SensorsBackToNormal2,SensorsBackToNormal3,MoverHealthDowngrade,MoverHealthUpgrade,FrigateHealthUpgradeSPGAME,DamageMoverTech,KeeperHealthUpgradeSPGAME_LOW,KeeperHealthUpgradeSPGAME_MED,KeeperHealthUpgradeSPGAME_HIGH,KeeperWeaponUpgradeSPGAME_M10_LVL_1,KeeperWeaponUpgradeSPGAME_M10_LVL_2,KeeperWeaponUpgradeSPGAME_M10_LVL_3,KeeperWeaponUpgradeSPGAME_M10_LVL_4,KeeperWeaponUpgradeSPGAME_M10_LVL_5,KeeperWeaponUpgradeSPGAME_M10_LVL_6,KeeperHealthUpgradeSPGAME_M10_LVL_1,KeeperHealthUpgradeSPGAME_M10_LVL_2,KeeperHealthUpgradeSPGAME_M10_LVL_3,AttackDroidHealthUpgradeSPGAME_LOW,AttackDroidHealthUpgradeSPGAME_MED,AttackDroidHealthUpgradeSPGAME_HIGH,AttackDroidWeaponUpgradeSPGAME_LOW,AttackDroidWeaponUpgradeSPGAME_MED,AttackDroidWeaponUpgradeSPGAME_HIGH,RadiationDefenseField",	
}
