Ship = 0
SubSystem = 1
build = 
    { 
-------------------------------------------------------------------------------
	-- PRODUCTION MODULE SUBSYSTEMS

	--Subsystems--
	{       Type=SubSystem,
                ThingToBuild="kpr_balcora_capital",
                RequiredResearch="",
                RequiredFleetSubSystems = "",
                DisplayPriority=0,
                DisplayedName="$7006",
                Description="$7007"
        },
	{       Type=SubSystem,
                ThingToBuild="kpr_a_capital",
                RequiredResearch="",
                RequiredFleetSubSystems = "",
                DisplayPriority=0,
                DisplayedName="$7006",
                Description="$7007"
        },
        {       Type=SubSystem,
                ThingToBuild="kpr_ms_fighter",
                RequiredResearch="",
                RequiredFleetSubSystems = "",
                DisplayPriority=0,
                DisplayedName="$7000",
                Description="$7001"        
        },
        {       Type=SubSystem,
                ThingToBuild="kpr_c_fighter",
                RequiredResearch="",
                RequiredFleetSubSystems = "",
                DisplayPriority=0,
                DisplayedName="$7000",
                Description="$7001"
        },
        {       Type=SubSystem,
                ThingToBuild="kpr_a_fighter",
                RequiredResearch="",
                RequiredFleetSubSystems = "",
                DisplayPriority=0,
                DisplayedName="$7000",
                Description="$7001"
        },
        {       Type=SubSystem,
                ThingToBuild="kpr_ms_research",
                RequiredResearch="",
                RequiredFleetSubSystems = "",
                DisplayPriority=0,
                DisplayedName="$7010",
                Description="$7011"
        },
        {       Type=SubSystem,
                ThingToBuild="kpr_c_research",
                RequiredResearch="",
                RequiredFleetSubSystems = "",
                DisplayPriority=0,
                DisplayedName="$7010",
                Description="$7011"
        },
        {       Type=SubSystem,
                ThingToBuild="kpr_a_research",
                RequiredResearch="",
                RequiredFleetSubSystems = "",
                DisplayPriority=0,
                DisplayedName="$7010",
                Description="$7011"
        },
        {       Type=SubSystem,
                ThingToBuild="kpr_ms_corvette",
                RequiredResearch="",
                RequiredFleetSubSystems = "Research",
                DisplayPriority=0,
                DisplayedName="$7002",
                Description="$7003"
        },
        {       Type=SubSystem,
                ThingToBuild="kpr_c_corvette",
                RequiredResearch="",
                RequiredFleetSubSystems = "Research",
                DisplayPriority=0,
                DisplayedName="$7002",
                Description="$7003"
        },
        {       Type=SubSystem,
                ThingToBuild="kpr_a_corvette",
                RequiredResearch="",
                RequiredFleetSubSystems = "Research",
                DisplayPriority=0,
                DisplayedName="$7002",
                Description="$7003"
        },
        {       Type=SubSystem,
                ThingToBuild="kpr_ms_frigate",
                RequiredResearch="",
                RequiredFleetSubSystems = "Research",
                DisplayPriority=0,
                DisplayedName="$7004",
                Description="$7005"
        },
        {       Type=SubSystem,
                ThingToBuild="kpr_c_frigate",
                RequiredResearch="",
                RequiredFleetSubSystems = "Research",
                DisplayPriority=0,
                DisplayedName="$7004",
                Description="$7005"
        },
        {       Type=SubSystem,
                ThingToBuild="kpr_a_frigate",
                RequiredResearch="",
                RequiredFleetSubSystems = "Research",
                DisplayPriority=0,
                DisplayedName="$7004",
                Description="$7005"
        },
        {       Type=SubSystem,
                ThingToBuild="kpr_ms_research_adv",
                RequiredResearch="",
                RequiredFleetSubSystems = "Research",
                DisplayPriority=10,
                DisplayedName="$7012",
                Description="$7013"
        },
        {       Type=SubSystem,
                ThingToBuild="kpr_c_research_adv",
                RequiredResearch="",
                RequiredFleetSubSystems = "Research",
                DisplayPriority=10,
                DisplayedName="$7012",
                Description="$7013"
        },
        {       Type=SubSystem,
                ThingToBuild="kpr_a_research_adv",
                RequiredResearch="",
                RequiredFleetSubSystems = "Research",
                DisplayPriority=10,
                DisplayedName="$7012",
                Description="$7013"
        
      },
        {       Type=SubSystem,
                ThingToBuild="kpr_ms_hyperspace",
                RequiredResearch="",
                RequiredFleetSubSystems = "Research",
                DisplayPriority=30,
                DisplayedName="$7014",
                Description="$7015"
        },
        {       Type=SubSystem,
                ThingToBuild="kpr_c_hyperspace",
                RequiredResearch="",
                RequiredFleetSubSystems = "Research",
                DisplayPriority=30,
                DisplayedName="$7014",
                Description="$7015"
        },
        {       Type=SubSystem,
                ThingToBuild="kpr_a_hyperspace",
                RequiredResearch="",
                RequiredFleetSubSystems = "Research",
                DisplayPriority=30,
                DisplayedName="$7014",
                Description="$7015"
        },
        {       Type=SubSystem,
                ThingToBuild="kpr_ms_hyperspace_in",
                RequiredResearch="",
                RequiredFleetSubSystems = "Research",
                DisplayPriority=40,
                DisplayedName="$7016",
                Description="$7017"
        },
        {       Type=SubSystem,
                ThingToBuild="kpr_c_hyperspace_in",
                RequiredResearch="",
                RequiredFleetSubSystems = "Research",
                DisplayPriority=40,
                DisplayedName="$7016",
                Description="$7017"
        },
        {       Type=SubSystem,
                ThingToBuild="kpr_a_hyperspace_in",
                RequiredResearch="",
                RequiredFleetSubSystems = "Research",
                DisplayPriority=40,
                DisplayedName="$7016",
                Description="$7017"
        },
        {       Type=SubSystem,
                ThingToBuild="kpr_ms_fire",
                RequiredResearch="",
                RequiredFleetSubSystems = "AdvancedResearch",
                DisplayPriority=60,
                DisplayedName="$7020",
                Description="$7021"
        },
        {       Type=SubSystem,
                ThingToBuild="kpr_c_fire",
                RequiredResearch="",
                RequiredFleetSubSystems = "AdvancedResearch",
                DisplayPriority=60,
                DisplayedName="$7020",
                Description="$7021"
        },
        {       Type=SubSystem,
                ThingToBuild="kpr_a_fire",
                RequiredResearch="",
                RequiredFleetSubSystems = "AdvancedResearch",
                DisplayPriority=60,
                DisplayedName="$7020",
                Description="$7021"
        },
        {       Type=SubSystem,
                ThingToBuild="kpr_ms_s_hyper",
                RequiredResearch="",
                RequiredFleetSubSystems = "",
                DisplayPriority=150,
                DisplayedName="$7036",
                Description="$7037"
        },
        {       Type=SubSystem,
                ThingToBuild="kpr_c_s_hyper",
                RequiredResearch="",
                RequiredFleetSubSystems = "",
                DisplayPriority=150,
                DisplayedName="$7036",
                Description="$7037"
        },
        {       Type=SubSystem,
                ThingToBuild="kpr_a_s_hyper",
                RequiredResearch="",
                RequiredFleetSubSystems = "",
                DisplayPriority=150,
                DisplayedName="$7036",
                Description="$7037"
        },
        {       Type=SubSystem,
                ThingToBuild="kpr_ms_s_array",
                RequiredResearch="",
                RequiredFleetSubSystems = "",
                DisplayPriority=151,
                DisplayedName="$7022",
                Description="$7023"
        },
        {       Type=SubSystem,
                ThingToBuild="kpr_c_s_array",
                RequiredResearch="",
                RequiredFleetSubSystems = "",
                DisplayPriority=151,
                DisplayedName="$7022",
                Description="$7023"
        },
        {       Type=SubSystem,
                ThingToBuild="kpr_a_s_array",
                RequiredResearch="",
                RequiredFleetSubSystems = "",
                DisplayPriority=151,
                DisplayedName="$7022",
                Description="$7023"
        },
        {       Type=SubSystem,
                ThingToBuild="kpr_ms_s_cloak",
                RequiredResearch="",
                RequiredFleetSubSystems = "",
                DisplayPriority=152,
                DisplayedName="$7024",
                Description="$7025"
        },
        {       Type=SubSystem,
                ThingToBuild="kpr_c_s_cloak",
                RequiredResearch="",
                RequiredFleetSubSystems = "",
                DisplayPriority=152,
                DisplayedName="$7024",
                Description="$7025"
        },
        {       Type=SubSystem,
                ThingToBuild="kpr_a_s_cloak",
                RequiredResearch="",
                RequiredFleetSubSystems = "",
                DisplayPriority=152,
                DisplayedName="$7024",
                Description="$7025"
      },

	 
	



	-------------------------------------------------------------------------------
 {
		Type = Ship,
		ThingToBuild = "kpr_Balcoragate",
		RequiredResearch = "",
		RequiredShipSubSystems = "Hyperspace", 
            	RequiredFleetSubSystems = "AdvancedResearch",
                DisplayPriority = 210,
		DisplayedName = "Balcora Gate",
		Description = "<b>Description:</b> AI-controlled progenitor hyperspace supergate, can bring forth the most destructive ships the progenitors can wield, Balcora is the only thing that can build Dreadnaughts and up.  \n\n<b>Strong Vs:</b> None \n\n<b>Weak Vs:</b> All \n\n<b>Prerequisites:</b> Regenerated Hyperspace Array",
	},
	{
		Type = Ship,
		ThingToBuild = "kpr_capital_sleeper",
		RequiredResearch = "",
		RequiredShipSubSystems = "CapshipProduction",
		DisplayPriority = 240,
		DisplayedName = "Sleeper",
		Description = "<b>Description:</b> Self-aware progenitor carrier ship, can build fighters and corvette class drones, friagtes, and can phase to negate damage. \n\n<b>Strong Vs:</b> All \n\n<b>Prerequisites:</b> Capital Facility",
	},
	{
		Type = Ship,
		ThingToBuild = "kpr_destroyer",
		RequiredResearch = "KPRDestroyerTech",
		RequiredShipSubSystems = "CapShipProduction",
		DisplayPriority = 220,
		DisplayedName = "Keeper",
		Description = "<b>Description:</b> Self-aware progenitor combat ship, can build drones and phase to negate damage  \n\n<b>Strong Vs:</b> All \n\n<b>Prerequisites:</b> Capital Facility",
	},
	{
		Type = Ship,
		ThingToBuild = "kpr_dreadnaught",
		RequiredResearch = "KPRDreadnaughtTech",
		RequiredShipSubSystems = "CapShipProduction",
		DisplayPriority = 260,
		DisplayedName = "Dreadnaught",
		Description = "<b>Description:</b> AI-controlled progenitor dreadnaught.  \n\n<b>Strong Vs:</b> All \n\n<b>Weak Vs:</b> None \n\n<b>Prerequisites:</b> Balcora Gate",
	},
	{
		Type = Ship,
		ThingToBuild = "kpr_sajuuk",
		RequiredResearch = "KprCapitalWeapons",
		RequiredShipSubSystems = "CapShipProduction",
		DisplayPriority = 270,
		DisplayedName = "Sajuuk",
		Description = "<b>Description:</b> He who's hand shapes what is.  \n\n<b>Strong Vs:</b> All \n\n<b>Weak Vs:</b> None \n\n<b>Prerequisites:</b> Balcora Gate",
	},
--Frigate--
	{
                Type = Ship,
		ThingToBuild = "kpr_frigate_sentinel",
		RequiredResearch = "",
		RequiredShipSubSystems = "FrigateProduction",
		DisplayPriority = 181,
	      DisplayedName = "Sentinel",
		Description = "<b>Description:</b> AI-controlled progenitor Anti-Fighter ship.  \n\n<b>Strong Vs:</b> Corvettes \n\n<b>Weak Vs:</b> Frigates, Destroyers & Battlecruisers \n\n<b>Prerequisites:</b> Frigate Facility",
	},
	{
            Type = Ship,
		ThingToBuild = "kpr_frigate_guardian",
		RequiredResearch = "KPRInstaAdvancedFrigateTech",
		RequiredShipSubSystems = "FrigateProduction",
		DisplayPriority = 182,
		DisplayedName = "Guardian",
		Description = "<b>Description:</b> AI-controlled progenitor anti-frigate and anti-capital ship.  \n\n<b>Strong Vs:</b> Frigates & Carriers  \n\n<b>Weak Vs:</b> Corvettes, Destroyers & Battlecruisers \n\n<b>Prerequisites:</b> Frigate Facility",
	},
	{
	      Type = Ship,
		ThingToBuild = "kpr_deciever",
		RequiredResearch = "KPRInstaAdvancedFrigateTech",
		RequiredShipSubSystems = "FrigateProduction",
		DisplayPriority = 179,
		DisplayedName = "Deciever",
		Description = "<b>Description:</b> AI-controlled progenitor Capture Frigate.  \n\n<b>Strong Vs:</b> Frigates \n\n<b>Weak Vs:</b> Corvettes, Destroyers & Battlecruisers \n\n<b>Prerequisites:</b> Frigate Facility",
	},
	{
		Type = Ship,
		ThingToBuild = "kpr_seeker",
		RequiredResearch = "",
		RequiredShipSubSystems = "FrigateProduction",
		DisplayPriority = 178,
		DisplayedName = "Seeker",
		Description = "<b>Description:</b> AI-controlled progenitor anti-Corvette ship.  \n\n<b>Strong Vs:</b> Strikecraft \n\n<b>Weak Vs:</b> Corvettes, Destroyers & Battlecruisers \n\n<b>Prerequisites:</b> Frigate Facility",
	},
--Corvette--
	{
		Type = Ship,
		ThingToBuild = "kpr_mover_nsp",
		RequiredResearch = "",
		RequiredShipSubSystems = "CorvetteProduction",
		DisplayPriority = 174,
		DisplayedName = "Mover",
		Description = "<b>Description:</b> AI-controlled progenitor maintenance drone, can attack and capture.  \n\n<b>Strong Vs:</b> Frigates \n\n<b>Weak Vs:</b> Bombers & Corvettes \n\n<b>Prerequisites:</b> Corvette Facility",
	},
---Fighters--
--	{
--		Type = Ship,
--		ThingToBuild = "hgn_kpr_fighter_stalker",
--		RequiredResearch = "",
--		RequiredShipSubSystems = "",
--		DisplayPriority = 172,
--		DisplayedName = "Stalker",
--		Description = "<b>Description:</b> AI-controlled progenitor multiple burn reconnaissance drone.  \n\n<b>Strong Vs:</b> None \n\n<b>Weak Vs:</b> All \n\n<b>Prerequisites:</b> None",
--	},
	{
		Type = Ship,
		ThingToBuild = "kpr_attackdroid",
		RequiredResearch = "",
		RequiredShipSubSystems = "FighterProduction",
		DisplayPriority = 11,
		DisplayedName = "Aggressor",
		Description = "<b>Description:</b> AI-controlled progenitor anti-fighter drone.  \n\n<b>Strong Vs:</b> Frghters \n\n<b>Weak Vs:</b> Corvettes \n\n<b>Prerequisites:</b> Fighter Facility",
	},
--UTILITY---
	{
                Type = Ship,
		ThingToBuild = "kpr_utility_observer",
		RequiredResearch = "",
		RequiredShipSubSystems = "",
		DisplayPriority = 171,
		DisplayedName = "Observer",
		Description = "<b>Description:</b> AI-controlled progenitor single burn advanced reconnaissance drone, can detect cloaked ships.  \n\n<b>Strong Vs:</b> None \n\n<b>Weak Vs:</b> All \n\n<b>Prerequisites:</b> None",	
	},
	{
                Type = Ship,
		ThingToBuild = "kpr_utility_processor",
		RequiredResearch = "",
		RequiredShipSubSystems = "",
		DisplayPriority = 170,
		DisplayedName = "Processor",
		Description = "<b>Description:</b> AI-controlled progenitor matter refinement ship.  \n\n<b>Strong Vs:</b> Frghters \n\n<b>Weak Vs:</b> Corvettes \n\n<b>Prerequisites:</b> None",
	},
	{
		Type = Ship,
		ThingToBuild = "kpr_utility_reclaimer",
		RequiredResearch = "",
		RequiredShipSubSystems = "",
		DisplayPriority = 14,
		DisplayedName = "Reclaimer",
		Description = "<b>Description:</b> AI-controlled progenitor acquisition drone, can salvage, resource and repair.  \n\n<b>Strong Vs:</b> None \n\n<b>Weak Vs:</b> All \n\n<b>Prerequisites:</b> None",
	},
}