-- UC_ file
-- Generated by Nick Waanders
-- UC_ file
-- Generated by Nick Waanders

--
UC_Family("Fighter", 14);
UC_Family("Fighter_hw1", 80);
UC_ShipType("Fighter_hw1sqd", 16);

--
UC_Family("Corvette", 12);
UC_Family("Corvette_hw1", 50);
UC_ShipType("MinelayerCorvette",10);
UC_ShipType("Corvette_hw1sqd", 16);
--
UC_Family("Frigate", 21);

	--UC_ShipType("TorpedoFrigate",4);		-- max 4 torpedo frigates
	UC_ShipType("DefenseFieldFrigate",2);
	
	UC_ShipType("CaptureFrigate",6);		-- max 6 capture frigates
--
UC_Family("Capital", 12);
UC_ShipType("Destroyer", 5);
UC_ShipType("Carrier", 4);
UC_ShipType("Battlecruiser",2);
UC_ShipType("HeavyCruiser",4);
UC_ShipType("Shipyard", 1);

--
UC_Family("Utility", 50);

UC_ShipType("ResourceCollector", 20);
UC_ShipType("ResourceController", 4);
UC_ShipType("Probe", 10);
UC_ShipType("ECMProbe", 10);
UC_ShipType("ProximitySensor", 10);	
	
UC_Family("Resource", 25);
UC_ShipType("ResourceCollector_hw1", 20);
UC_ShipType("ResourceController_hw1", 5);
--
UC_Family("NonCombat", 25);
UC_ShipType("Probe_hw1", 10);
UC_ShipType("ProximitySensor_hw1", 10);
UC_ShipType("Research", 1);
UC_ShipType("Research1", 1);
UC_ShipType("Research2", 1);
UC_ShipType("Research3", 1);
UC_ShipType("Research4", 1);
UC_ShipType("Research5", 1);
--UC_ShipType("CloakGenerator", 4);
--UC_ShipType("GravWellGenerator", 4);	

--
UC_Family("Platform", 20);
	UC_ShipType("HyperspacePlatform", 4);

--
UC_Family("Mothership", 1);

--
UC_Family("DreadNaught", 1);

UC_Family("SinglePlayerMisc", 100);

--
UC_Family("SinglePlayerMisc", 100);
	UC_ShipType("Mover", 10);		-- max 10 movers

--	
UC_Family("SPMovers", 10);

--
UC_Family("CommStation", 1 );

