Icon_Speed = "data:ui/newui/research/icons/speed.mres"
Icon_Health = "data:ui/newui/research/icons/health.mres"
Icon_Tech = "data:ui/newui/research/icons/tech.mres"
Icon_Ability = "data:ui/newui/research/icons/ability.mres"
Icon_Build = "data:ui/newui/research/icons/build.mres"
Modifier = 0
Ability = 1
AllShips = 0
Family = 1
Ship = 2

research =
{	
--Fighter Techs
	{
		Name =			"FighterDrive",
		RequiredResearch =	"",
		RequiredSubSystems =	"Research",
		Cost = 			30,
		Time = 			36,
		DisplayedName =		"$11502",
		ShortDisplayedName =	"$11502",
		DisplayPriority =		11,
		Description =		"$11503",
		Icon = 			Icon_Build,
		TargetName =		"Kus_Scout",
	},
	{
		Name =			"FighterChassis",
		RequiredResearch =	"FighterDrive",
		RequiredSubSystems =	"Research",
		Cost = 			30,
		Time = 			60,
		DisplayedName =		"$11514",
		ShortDisplayedName =	"$11514",
		DisplayPriority =		12,
		Description =		"$11515",
		Icon = 			Icon_Build,
		TargetName =		"Kus_Interceptor",
	},
	{
		Name =			"DefenderSubSystems",
		RequiredResearch =	"FighterDrive",
		RequiredSubSystems =	"Research",
		Cost = 			30,
		Time = 			120,
		DisplayedName =		"$11528",
		ShortDisplayedName =	"$11528",
		DisplayPriority =		13,
		Description =		"$11529",
		Icon = 			Icon_Build,
		TargetName =		"Kus_Defender",
	},
	{
		Name =			"PlasmaBombLauncher",
		RequiredResearch =	"FighterChassis",
		RequiredSubSystems =	"Research",
		Cost = 			30,
		Time = 			120,
		DisplayedName =		"$11512",
		ShortDisplayedName =	"$11512",
		DisplayPriority =		14,
		Description =		"$11513",
		Icon = 			Icon_Build,
		TargetName =		"Kus_AttackBomber",
	},		
	{
		Name =			"CloakedFighter",
		RequiredResearch =	"FighterChassis",
		RequiredSubSystems =	"Research",
		Cost = 			30,
		Time = 			160,
		DisplayedName =		"$11506",
		ShortDisplayedName =	"$11506",
		DisplayPriority =		15,
		Description =		"$11507",
		Icon = 			Icon_Build,
		TargetName =		"Kus_CloakedFighter",
	},	
--Corvette Techs
	{
		Name =			"CorvetteDrive",
		RequiredResearch =	"",
		RequiredSubSystems =	"Research",
		Cost = 			30,
		Time = 			52,
		DisplayedName =		"$11516",
		ShortDisplayedName =	"$11516",
		DisplayPriority =		21,
		Description =		"$11517",
		Icon = 			Icon_Build,
		TargetName =		"Kus_RepairCorvette",
	},
	{
		Name =			"CorvetteChassis",
		RequiredResearch =	"CorvetteDrive",
		RequiredSubSystems =	"Research",
		Cost = 			30,
		Time = 			64,
		DisplayedName =		"$11522",
		ShortDisplayedName =	"$11522",
		DisplayPriority =		22,
		Description =		"$11523",
		Icon = 			Icon_Build,
		TargetName =		"Kus_LightCorvette",
	},
	{
		Name =			"HeavyCorvetteUpgrade",
		RequiredResearch =	"CorvetteChassis",
		RequiredSubSystems =	"Research",
		Cost = 			30,
		Time = 			64,
		DisplayedName =		"$11518",
		ShortDisplayedName =	"$11518",
		DisplayPriority =		23,
		Description =		"$11519",
		Icon = 			Icon_Build,
		TargetName =		"Kus_HeavyCorvette",
	},
	{
		Name =			"FastTrackingTurrets",
		RequiredResearch =	"CorvetteChassis",
		RequiredSubSystems =	"Research",
		Cost = 			30,
		Time = 			120,
		DisplayedName =		"$11530",
		ShortDisplayedName =	"$11530",
		DisplayPriority =		24,
		Description =		"$11511",
		Icon = 			Icon_Build,
		TargetName =		"Kus_MultiGunCorvette",
	},
	{
		Name =			"MinelayingTech",
		RequiredResearch =	"CorvetteChassis",
		RequiredSubSystems =	"Research",
		Cost = 			30,
		Time = 			120,
		DisplayedName =		"$11520",
		ShortDisplayedName =	"$11520",
		DisplayPriority =		25,
		Description =		"$11521",
		Icon = 			Icon_Build,
		TargetName =		"Kus_MinelayerCorvette",
	},	
--Frigate Techs
	{
		Name =			"CapitalShipDrive",
		RequiredResearch =	"",
		RequiredSubSystems =	"Research",
		Cost = 			30,
		Time = 			80,
		DisplayedName =		"$11526",
		ShortDisplayedName =	"$11526",
		DisplayPriority =		31,
		Description =		"$11527",
		Icon = 			Icon_Build,
		TargetName =		"Kus_SupportFrigate",
	},
	{
		Name =			"CapitalShipChassis",
		RequiredResearch =	"CapitalShipDrive",
		RequiredSubSystems =	"Research",
		Cost = 			30,
		Time = 			68,
		DisplayedName =		"$11540",
		ShortDisplayedName =	"$11540",
		DisplayPriority =		32,
		Description =		"$11541",
		Icon = 			Icon_Build,
		TargetName =		"Kus_AssaultFrigate",
	},
	{
		Name =			"IonCannons",
		RequiredResearch =	"CapitalShipChassis",
		RequiredSubSystems =	"Research",
		Cost = 			30,
		Time = 			180,
		DisplayedName =		"$11534",
		ShortDisplayedName =	"$11534",
		DisplayPriority =		33,
		Description =		"$11535",
		Icon = 			Icon_Build,
		TargetName =		"Kus_IonCannonFrigate",
	},
	{
		Name =			"DroneTechnology",
		RequiredResearch =	"CapitalShipChassis",
		RequiredSubSystems =	"Research",
		Cost = 			30,
		Time = 			160,
		DisplayedName =		"$11536",
		ShortDisplayedName =	"$11536",
		DisplayPriority =		34,
		Description =		"$11537",
		Icon = 			Icon_Build,
		TargetName =		"Kus_DroneFrigate",
	},	
--Super-Capital Ship Techs
	{
		Name =			"SuperCapitalShipDrive",
		RequiredResearch =	"CapitalShipChassis",
		RequiredSubSystems =	"Research",
		Cost = 			30,
		Time = 			120,
		DisplayedName =		"$11542",
		ShortDisplayedName =	"$11542",
		DisplayPriority =		41,
		Description =		"$11543",
		Icon = 			Icon_Build,
		TargetName =		"Kus_Destroyer",
	},
	{
		Name =			"GuidedMissiles",
		RequiredResearch =	"SuperCapitalShipDrive",
		RequiredSubSystems =	"Research",
		Cost = 			30,
		Time = 			120,
		DisplayedName =		"$11546",
		ShortDisplayedName =	"$11546",
		DisplayPriority =		42,
		Description =		"$11547",
		Icon = 			Icon_Build,
		TargetName =		"Kus_MissileDestroyer",
	},
	{
		Name =			"SuperHeavyChassis",
		RequiredResearch =	"SuperCapitalShipDrive",
		RequiredSubSystems =	"Research",
		Cost = 			30,
		Time = 			180,
		DisplayedName =		"$11560",
		ShortDisplayedName =	"$11560",
		DisplayPriority =		43,
		Description =		"$11561",
		Icon = 			Icon_Build,
		TargetName =		"Kus_Carrier",
	},
	{
		Name =			"HeavyGuns",
		RequiredResearch =	"SuperHeavyChassis",
		RequiredSubSystems =	"Research",
		Cost = 			30,
		Time = 			160,
		DisplayedName =		"$11550",
		ShortDisplayedName =	"$11550",
		DisplayPriority =		44,
		Description =		"$11551",
		Icon = 			Icon_Build,
		TargetName =		"Kus_HeavyCruiser",
	},
--Non-Combat Techs
	{
		Name =			"ProximitySensor",
		RequiredResearch =	"",
		RequiredSubSystems =	"Research",
		Cost = 			30,
		Time = 			40,
		DisplayedName =		"$11552",
		ShortDisplayedName =	"$11552",
		DisplayPriority =		51,
		Description =		"$11553",
		Icon = 			Icon_Build,
		TargetName =		"Kus_ProximitySensor",
	},
	{
		Name =			"SensorArray",
		RequiredResearch =	"ProximitySensor",
		RequiredSubSystems =	"Research",
		Cost = 			30,
		Time = 			160,
		DisplayedName =		"$11554",
		ShortDisplayedName =	"$11554",
		DisplayPriority =		52,
		Description =		"$11555",
		Icon = 			Icon_Build,
		TargetName =		"Kus_SensorArray",
	},
	{
		Name =			"GravityGenerator",
		RequiredResearch =	"CapitalShipDrive",
		RequiredSubSystems =	"Research",
		Cost = 			30,
		Time = 			180,
		DisplayedName =		"$11556",
		ShortDisplayedName =	"$11556",
		DisplayPriority =		53,
		Description =		"$11557",
		Icon = 			Icon_Build,
		TargetName =		"Kus_GravWellGenerator",
	},
	{
		Name =			"CloakGenerator",
		RequiredResearch =	"CapitalShipDrive",
		RequiredSubSystems =	"Research",
		Cost = 			30,
		Time = 			180,
		DisplayedName =		"$11558",
		ShortDisplayedName =	"$11558",
		DisplayPriority =		54,
		Description =		"$11559",
		Icon = 			Icon_Build,
		TargetName =		"Kus_CloakGenerator",
	},
	{
		Name =				"Hyperspace",
		RequiredResearch =		"CapitalShipDrive",
		RequiredSubSystems =		"Research",
		Cost = 				30,
		Time = 				160,
		DisplayedName =			"Hyperspace",
		DisplayPriority =		12,
		Description =			"Enables Hyperspace ",
		UpgradeType =			Ability,
		TargetType =			AllShips,
		TargetName =			"Kus_ResearchShip",
	        UpgradeName =			"HyperSpace",
		Icon = Icon_Hyperspace,
		ShortDisplayedName = "Hyperspace",
	},

	{
		Name =				"MothershipBUILDSPEEDUpgrade1",
		RequiredResearch =		"",
		RequiredSubSystems =		"Research1",
		Cost = 				0,
		Time = 				0,
		DisplayedName =			"$7800",
		DisplayPriority =		45,
		Description =			"$7801",
		UpgradeType =			Modifier,
		TargetType =			Ship,
		TargetName =			"Kus_MotherShip",
	        UpgradeName =			"BUILDSPEED",
        	UpgradeValue =			1.075,
		Icon = Icon_Build,
		ShortDisplayedName = "$7240",
	},
	{
		Name =				"MothershipBUILDSPEEDUpgrade2",
		RequiredResearch =		"",
		RequiredSubSystems =		"Research2",
		Cost = 				0,
		Time = 				0,
		DisplayedName =			"$7800",
		DisplayPriority =		45,
		Description =			"$7801",
		UpgradeType =			Modifier,
		TargetType =			Ship,
		TargetName =			"Kus_MotherShip",
	        UpgradeName =			"BUILDSPEED",
        	UpgradeValue =			1.15,
		Icon = Icon_Build,
		ShortDisplayedName = "$7240",
	},
	{
		Name =				"MothershipBUILDSPEEDUpgrade3",
		RequiredResearch =		"",
		RequiredSubSystems =		"Research3",
		Cost = 				0,
		Time = 				0,
		DisplayedName =			"$7800",
		DisplayPriority =		45,
		Description =			"$7801",
		UpgradeType =			Modifier,
		TargetType =			Ship,
		TargetName =			"Kus_MotherShip",
	        UpgradeName =			"BUILDSPEED",
        	UpgradeValue =			1.225,
		Icon = Icon_Build,
		ShortDisplayedName = "$7240",
	},
	{
		Name =				"MothershipBUILDSPEEDUpgrade4",
		RequiredResearch =		"",
		RequiredSubSystems =		"Research4",
		Cost = 				0,
		Time = 				0,
		DisplayedName =			"$7800",
		DisplayPriority =		45,
		Description =			"$7801",
		UpgradeType =			Modifier,
		TargetType =			Ship,
		TargetName =			"Kus_MotherShip",
	        UpgradeName =			"BUILDSPEED",
        	UpgradeValue =			1.3,
		Icon = Icon_Build,
		ShortDisplayedName = "$7240",
	},
	{
		Name =				"MothershipBUILDSPEEDUpgrade5",
		RequiredResearch =		"",
		RequiredSubSystems =		"Research5",
		Cost = 				0,
		Time = 				0,
		DisplayedName =			"$7800",
		DisplayPriority =		45,
		Description =			"$7801",
		UpgradeType =			Modifier,
		TargetType =			Ship,
		TargetName =			"Kus_MotherShip",
	        UpgradeName =			"BUILDSPEED",
        	UpgradeValue =			1.4,
		Icon = Icon_Build,
		ShortDisplayedName = "$7240",
	},
	{
		Name =				"CarrierBUILDSPEEDUpgrade1",
		RequiredResearch =		"SuperHeavyChassis",
		RequiredSubSystems =		"Research1",
		Cost = 				0,
		Time = 				0,
		DisplayedName =			"$7800",
		DisplayPriority =		45,
		Description =			"$7801",
		UpgradeType =			Modifier,
		TargetType =			Ship,
		TargetName =			"Kus_Carrier",
	        UpgradeName =			"BUILDSPEED",
        	UpgradeValue =			1.075,
		Icon = Icon_Build,
		ShortDisplayedName = "$7240",
	},
	{
		Name =				"CarrierBUILDSPEEDUpgrade2",
		RequiredResearch =		"SuperHeavyChassis",
		RequiredSubSystems =		"Research2",
		Cost = 				0,
		Time = 				0,
		DisplayedName =			"$7800",
		DisplayPriority =		45,
		Description =			"$7801",
		UpgradeType =			Modifier,
		TargetType =			Ship,
		TargetName =			"Kus_Carrier",
	        UpgradeName =			"BUILDSPEED",
        	UpgradeValue =			1.15,
		Icon = Icon_Build,
		ShortDisplayedName = "$7240",
	},
	{
		Name =				"CarrierBUILDSPEEDUpgrade3",
		RequiredResearch =		"SuperHeavyChassis",
		RequiredSubSystems =		"Research3",
		Cost = 				0,
		Time = 				0,
		DisplayedName =			"$7800",
		DisplayPriority =		45,
		Description =			"$7801",
		UpgradeType =			Modifier,
		TargetType =			Ship,
		TargetName =			"Kus_Carrier",
	        UpgradeName =			"BUILDSPEED",
        	UpgradeValue =			1.225,
		Icon = Icon_Build,
		ShortDisplayedName = "$7240",
	},
	{
		Name =				"CarrierBUILDSPEEDUpgrade4",
		RequiredResearch =		"SuperHeavyChassis",
		RequiredSubSystems =		"Research4",
		Cost = 				0,
		Time = 				0,
		DisplayedName =			"$7800",
		DisplayPriority =		45,
		Description =			"$7801",
		UpgradeType =			Modifier,
		TargetType =			Ship,
		TargetName =			"Kus_Carrier",
	        UpgradeName =			"BUILDSPEED",
        	UpgradeValue =			1.3,
		Icon = Icon_Build,
		ShortDisplayedName = "$7240",
	},
	{
		Name =				"CarrierBUILDSPEEDUpgrade5",
		RequiredResearch =		"SuperHeavyChassis",
		RequiredSubSystems =		"Research5",
		Cost = 				0,
		Time = 				0,
		DisplayedName =			"$7800",
		DisplayPriority =		45,
		Description =			"$7801",
		UpgradeType =			Modifier,
		TargetType =			Ship,
		TargetName =			"Kus_Carrier",
	        UpgradeName =			"BUILDSPEED",
        	UpgradeValue =			1.4,
		Icon = Icon_Build,
		ShortDisplayedName = "$7240",
	},
{
		Name =				"ScaffoldBUILDSPEEDUpgrade1",
		RequiredResearch =		"Hyperspace",
		RequiredSubSystems =		"Research1",
		Cost = 				0,
		Time = 				0,
		DisplayedName =			"$7800",
		DisplayPriority =		45,
		Description =			"$7801",
		UpgradeType =			Modifier,
		TargetType =			Ship,
		TargetName =			"Kus_Scaffold",
	        UpgradeName =			"BUILDSPEED",
        	UpgradeValue =			1.075,
		Icon = Icon_Build,
		ShortDisplayedName = "$7240",
	},
	{
		Name =				"ScaffoldBUILDSPEEDUpgrade2",
		RequiredResearch =		"Hyperspace",
		RequiredSubSystems =		"Research2",
		Cost = 				0,
		Time = 				0,
		DisplayedName =			"$7800",
		DisplayPriority =		45,
		Description =			"$7801",
		UpgradeType =			Modifier,
		TargetType =			Ship,
		TargetName =			"Kus_Scaffold",
	        UpgradeName =			"BUILDSPEED",
        	UpgradeValue =			1.15,
		Icon = Icon_Build,
		ShortDisplayedName = "$7240",
	},
	{
		Name =				"ScaffoldBUILDSPEEDUpgrade3",
		RequiredResearch =		"Hyperspace",
		RequiredSubSystems =		"Research3",
		Cost = 				0,
		Time = 				0,
		DisplayedName =			"$7800",
		DisplayPriority =		45,
		Description =			"$7801",
		UpgradeType =			Modifier,
		TargetType =			Ship,
		TargetName =			"Kus_Scaffold",
	        UpgradeName =			"BUILDSPEED",
        	UpgradeValue =			1.225,
		Icon = Icon_Build,
		ShortDisplayedName = "$7240",
	},
	{
		Name =				"ScaffoldBUILDSPEEDUpgrade4",
		RequiredResearch =		"Hyperspace",
		RequiredSubSystems =		"Research4",
		Cost = 				0,
		Time = 				0,
		DisplayedName =			"$7800",
		DisplayPriority =		45,
		Description =			"$7801",
		UpgradeType =			Modifier,
		TargetType =			Ship,
		TargetName =			"Kus_Scaffold",
	        UpgradeName =			"BUILDSPEED",
        	UpgradeValue =			1.3,
		Icon = Icon_Build,
		ShortDisplayedName = "$7240",
	},
	{
		Name =				"ScaffoldBUILDSPEEDUpgrade5",
		RequiredResearch =		"Hyperspace",
		RequiredSubSystems =		"Research5",
		Cost = 				0,
		Time = 				0,
		DisplayedName =			"$7800",
		DisplayPriority =		45,
		Description =			"$7801",
		UpgradeType =			Modifier,
		TargetType =			Ship,
		TargetName =			"Kus_Scaffold",
	        UpgradeName =			"BUILDSPEED",
        	UpgradeValue =			1.4,
		Icon = Icon_Build,
		ShortDisplayedName = "$7240",
	},
	{
		Name =				"AttackBomberImprovedBombs",
		RequiredResearch =		"PlasmaBombLauncher",
		RequiredSubSystems =		"Research",
		Cost = 				30,
		Time = 				45,
		DisplayedName =			"$7517",
		DisplayPriority =		30,
		Description =			"$7518",
		UpgradeType =			Ability,
		TargetType =			Ship,
		TargetName =			"Kus_AttackBomber",
	        UpgradeName =			"UseSpecialWeaponsInNormalAttack",
		Icon = Icon_Ability,
		ShortDisplayedName = "$7208",
	},
	{
		Name =				"AttackBomberImprovedBombs5",
		RequiredResearch =		"AttackBomberImprovedBombs",
		RequiredSubSystems =		"Research",
		Cost = 				0,
		Time = 				0,
		DisplayedName =			"$7517",
		DisplayPriority =		30,
		Description =			"$7518",
		UpgradeType =			Ability,
		TargetType =			Ship,
		TargetName =			"Kus_AttackBomber5",
	        UpgradeName =			"UseSpecialWeaponsInNormalAttack",
		Icon = Icon_Ability,
		ShortDisplayedName = "$7208"},
{Name="FighterHealthUpgrade1",
RequiredResearch = "", 
RequiredSubSystems="Research",
Cost=30,
Time=60,
DisplayedName="Fighter Armor Level 1",
DisplayPriority=80,
Description="Improved fighter armor to Level 1 allowing them to withstand more hits",
UpgradeType=Modifier,
TargetType=Family,
TargetName="Fighter",
UpgradeName="MAXHEALTH",
UpgradeValue=2,
Icon=Icon_Health,
ShortDisplayedName="Fighter Armor Level 1"},

{Name="FighterHealthUpgrade2",
RequiredResearch="FighterHealthUpgrade1",
RequiredSubSystems="Research",
Cost=30,
Time=80,
DisplayedName="Fighter Armor Level 2",
DisplayPriority=80,
Description="Improves Fighter Armor to Level 2",
UpgradeType=Modifier,
TargetType=Family,
TargetName="Fighter",
	UpgradeName="MAXHEALTH",
	UpgradeValue=4,
	Icon=Icon_Health,
	ShortDisplayedName="Fighter Armor Level 2"},
		
		{Name="KSHFighterspeedUpgrade1",
		RequiredResearch="FighterDrive",
		RequiredSubSystems="Research",
		Cost=30,
		Time=50,
		DisplayedName="$7755",
		DisplayPriority=81,
		Description="$7756",
		UpgradeType=Modifier,
		TargetType=Family,
		TargetName="Fighter",
		UpgradeName="MAXSPEED",
		UpgradeValue=1.25,
		Icon=Icon_Speed,
		ShortDisplayedName="$7331"},

{Name="KSHFighterspeedUpgrade2",
RequiredResearch="KSHFighterspeedUpgrade1",
RequiredSubSystems="Research",
Cost=30,
Time=70,
DisplayedName="$7757",
DisplayPriority=81,
Description="$7758",
UpgradeType=Modifier,
TargetType=Family,
TargetName="Fighter",
UpgradeName="MAXSPEED",
UpgradeValue=1.5,
Icon=Icon_Speed,
ShortDisplayedName="$7332"},

{Name="KSHCorvetteHealthUpgrade1",
RequiredResearch="CorvetteChassis",
RequiredSubSystems="Research",
Cost=30,
Time=60,
DisplayedName="$7759",
DisplayPriority=200,
Description="$7760",
UpgradeType=Modifier,
TargetType=Family,
TargetName="Corvette",
UpgradeName="MAXHEALTH",
UpgradeValue=1.3,
Icon=Icon_Health,
ShortDisplayedName="$7341"},

{Name="KSHCorvetteHealthUpgrade2",
RequiredResearch="KSHCorvetteHealthUpgrade1 & CorvetteChassis",
RequiredSubSystems="Research",
Cost=30,
Time=80,
DisplayedName="$7761",
DisplayPriority=200,
Description="$7762",
UpgradeType=Modifier,
TargetType=Family,
TargetName="Corvette",
UpgradeName="MAXHEALTH",
UpgradeValue=1.6,
Icon=Icon_Health,
ShortDisplayedName="$7342"},

{Name="KSHCorvetteSpeedUpgrade1",
RequiredResearch="CorvetteDrive",
RequiredSubSystems="Research",
Cost=30,
Time=60,
DisplayedName="$7763",
DisplayPriority=201,
Description="$7764",
UpgradeType=Modifier,
TargetType=Family,
TargetName="Corvette",
UpgradeName="MAXSPEED",
UpgradeValue=1.2,
Icon=Icon_Speed,
ShortDisplayedName="$7341"},

{Name="KSHCorvetteSpeedUpgrade2",
RequiredResearch="CorvetteDrive & KSHCorvetteSpeedUpgrade1",
RequiredSubSystems="Research",
Cost=30,
Time=80,
DisplayedName="$7765",
DisplayPriority=201,
Description="$7766",
UpgradeType=Modifier,
TargetType=Family,
TargetName="Corvette",
UpgradeName="MAXSPEED",
UpgradeValue=1.4,
Icon=Icon_Speed,
ShortDisplayedName="$7342"},

{Name="KSHFrigateHealthUpgrade1",
RequiredResearch="CapitalShipChassis",
RequiredSubSystems="Research",
Cost=30,
Time=80,
DisplayedName="$7767",
DisplayPriority=306,
Description="$7768",
UpgradeType=Modifier,
TargetType=Family,
TargetName="Frigate",
UpgradeName="MAXHEALTH",
UpgradeValue=1.3,
Icon=Icon_Health,
ShortDisplayedName="$7371"},

{Name="KSHFrigateHealthUpgrade2",
RequiredResearch="KSHFrigateHealthUpgrade1",
RequiredSubSystems="Research",
Cost=30,
Time=300,
DisplayedName="$7769",
DisplayPriority=306,
Description="$7770",
UpgradeType=Modifier,
TargetType=Family,
TargetName="Frigate",
UpgradeName="MAXHEALTH",
UpgradeValue=1.6,
Icon=Icon_Health,
ShortDisplayedName="$7372"},

{Name="KSHFrigateSpeedUpgrade1",
RequiredResearch="CapitalShipDrive",
RequiredSubSystems="Research",
Cost=30,
Time=70,
DisplayedName="$7771",
DisplayPriority=307,
Description="$7772",
UpgradeType=Modifier,
TargetType=Family,
TargetName="Frigate",
UpgradeName="MAXSPEED",
UpgradeValue=1.2,
Icon=Icon_Speed,
ShortDisplayedName="$7371"},

{Name="KSHFrigateSpeedUpgrade2",
RequiredResearch="KSHFrigateSpeedUpgrade1",
RequiredSubSystems="Research",
Cost=30,
Time=300,
DisplayedName="$7773",
DisplayPriority=307,
Description="$7774",
UpgradeType=Modifier,
TargetType=Family,
TargetName="Frigate",
UpgradeName="MAXSPEED",
UpgradeValue=1.35,
Icon=Icon_Speed,
ShortDisplayedName="$7372"},

{Name="KSHSuperCapHealthUpgrade1",
RequiredResearch="SuperHeavyChassis",
RequiredSubSystems="Research",
Cost=30,
Time=60,
DisplayedName="$7743",
DisplayPriority=61,
Description="$7744",
UpgradeType=Modifier,
TargetType=Family,
TargetName="Capital",
UpgradeName="MAXHEALTH",
UpgradeValue=1.3,
Icon=Icon_Health,
ShortDisplayedName="$7354"},

{Name="KSHSuperCapHealthUpgrade2",
RequiredResearch="KSHSuperCapHealthUpgrade1",
RequiredSubSystems="Research",
Cost=30,
Time=80,
DisplayedName="$7745",
DisplayPriority=61,
Description="$7746",
UpgradeType=Modifier,
TargetType=Family,
TargetName="Capital",
UpgradeName="MAXHEALTH",
UpgradeValue=1.6,
Icon=Icon_Health,
ShortDisplayedName="$7355"},

{Name="KSHSuperCapSpeedUpgrade1",
RequiredResearch="SuperCapitalShipDrive",
RequiredSubSystems="Research",
Cost=30,
Time=60,
DisplayedName="$7747",
DisplayPriority=64,
Description="$7748",
UpgradeType=Modifier,
TargetType=Family,
TargetName="Capital",
UpgradeName="MAXSPEED",
UpgradeValue=1.2,
Icon=Icon_Speed,
ShortDisplayedName="$7354"},

{Name="KSHSuperCapSpeedUpgrade2",
RequiredResearch="KSHSuperCapSpeedUpgrade1",
RequiredSubSystems="Research",
Cost=30,
Time=80,
DisplayedName="$7749",
DisplayPriority=64,
Description="$7750",
UpgradeType=Modifier,
TargetType=Family,
TargetName="Capital",
UpgradeName="MAXSPEED",
UpgradeValue=1.35,
Icon=Icon_Speed,
ShortDisplayedName="$7355"},

{Name="KshGunTurretHealthUpgrade1",
RequiredResearch="GravityGenerator",
RequiredSubSystems="Research",
Cost=30,
Time=30,
DisplayedName="Gravity Well Generator Armor 1",
DisplayPriority=600,
Description="$7604",
UpgradeType=Modifier,
TargetType=Ship,
TargetName="Kus_Gravwellgenerator",
UpgradeName="MAXHEALTH",
UpgradeValue=1.3,
Icon=Icon_Health,
ShortDisplayedName="Lvl 1 Gravity Well Gen."},

{Name="KshGunTurretHealthUpgrade2",
RequiredResearch="KshGunTurretHealthUpgrade1",
RequiredSubSystems="Research",
Cost=30,
Time=40,
DisplayedName="Gravity Well Generator Armor 2",
DisplayPriority=600,
Description="$7606",
UpgradeType=Modifier,
TargetType=Ship,
TargetName="Kus_Gravwellgenerator",
UpgradeName="MAXHEALTH",
UpgradeValue=1.6,
Icon=Icon_Health,
ShortDisplayedName="Lvl 2 Gravity Well Gen."},

{Name="KshIonTurretHealthUpgrade1",
RequiredResearch="cloakgenerator",
RequiredSubSystems="Research",
Cost=30,
Time=30,
DisplayedName="Cloak Generator Armor 1",
DisplayPriority=603,
Description="$7608",
UpgradeType=Modifier,
TargetType=Ship,
TargetName="Kus_CloakGenerator",
UpgradeName="MAXHEALTH",
UpgradeValue=1.3,
Icon=Icon_Health,
ShortDisplayedName="Lvl 1 Cloak Generator"},

{Name="KshIonTurretHealthUpgrade2",
RequiredResearch="KshIonTurretHealthUpgrade1",
RequiredSubSystems="Research",
Cost=30,
Time=40,
DisplayedName="Cloak Generator Armor 2",
DisplayPriority=603,
Description="$7630",
UpgradeType=Modifier,
TargetType=Ship,
TargetName="Kus_CloakGenerator",
UpgradeName="MAXHEALTH",
UpgradeValue=1.6,
Icon=Icon_Health,
ShortDisplayedName="Lvl 2 Cloak Generator"},

{Name="KshResourceCollectorHealthUpgrade1",
RequiredResearch="",
RequiredSubSystems="Research",
Cost=30,
Time=40,
DisplayedName="$7611",
DisplayPriority=701,
Description="$7612",
UpgradeType=Modifier,
TargetType=Ship,
TargetName="Kus_ResourceCollector",
UpgradeName="MAXHEALTH",
UpgradeValue=1.5,
Icon=Icon_Health,
ShortDisplayedName="$7264"},

{Name="KshResourceCollectorHealthUpgrade2",
RequiredResearch="KshResourceCollectorHealthUpgrade1",
RequiredSubSystems="Research",
Cost=30,
Time=60,
DisplayedName="$7613",
DisplayPriority=701,
Description="$7614",
UpgradeType=Modifier,
TargetType=Ship,
TargetName="Kus_ResourceCollector",
UpgradeName="MAXHEALTH",
UpgradeValue=2,
Icon=Icon_Health,
ShortDisplayedName="$7265"},

{Name="KshResourceControllerHealthUpgrade1",
RequiredResearch="",
RequiredSubSystems="Research",
Cost=30,
Time=30,
DisplayedName="$7267",
DisplayPriority=704,
Description="$7616",
UpgradeType=Modifier,
TargetType=Ship,
TargetName="Kus_ResourceController",
UpgradeName="MAXHEALTH",
UpgradeValue=1.3,
Icon=Icon_Health,
ShortDisplayedName="$7267"},

{Name="KshResourceControllerHealthUpgrade2",
RequiredResearch="KshResourceControllerHealthUpgrade1",
RequiredSubSystems="Research",
Cost=30,
Time=40,
DisplayedName="$7617",
DisplayPriority=704,
Description="$7618",
UpgradeType=Modifier,
TargetType=Ship,
TargetName="Kus_ResourceController",
UpgradeName="MAXHEALTH",
UpgradeValue=1.6,
Icon=Icon_Health,
ShortDisplayedName="$7268"},
	

--AI behaviour 	
	{ 
		Name = "cpuplayers_defensive", 
		RequiredResearch = "", 
		RequiredSubSystems = "", 
		Cost = 1, 
		Time = 1, 
		DisplayedName = "", 
		DisplayPriority = 0,        
		Description = "",             
		TargetName = "",
	},	
	{ 
		Name = "cpuplayers_aggressive", 
		RequiredResearch = "", 
		RequiredSubSystems = "", 
		Cost = 1, 
		Time = 1, 
		DisplayedName = "", 
		DisplayPriority = 0,        
		Description = "",             
		TargetName = "",
	},	
	{ 
		Name = "cpuplayers_dynamic", 
		RequiredResearch = "", 
		RequiredSubSystems = "", 
		Cost = 1, 
		Time = 1, 
		DisplayedName = "", 
		DisplayPriority = 0,        
		Description = "",             
		TargetName = "",
	},
--AI no-rush	
	{ 
		Name = "cpuplayers_norushtime5", 
		RequiredResearch = "", 
		RequiredSubSystems = "", 
		Cost = 1, 
		Time = 1, 
		DisplayedName = "", 
		DisplayPriority = 0,        
		Description = "",             
		TargetName = "",
	},		
	{ 
		Name = "cpuplayers_norushtime30", 
		RequiredResearch = "", 
		RequiredSubSystems = "", 
		Cost = 1, 
		Time = 1, 
		DisplayedName = "", 
		DisplayPriority = 0,        
		Description = "",             
		TargetName = "",
	},		
	{ 
		Name = "cpuplayers_norushtime15", 
		RequiredResearch = "", 
		RequiredSubSystems = "", 
		Cost = 1, 
		Time = 1, 
		DisplayedName = "", 
		DisplayPriority = 0,        
		Description = "",             
		TargetName = "",
	},	
--AI build speed
	{ 
		Name =			"AllShipBuildSpeed",
		RequiredResearch =	"",                       
		RequiredSubSystems =	"",                               
		Cost = 			1,
		Time = 			1,
		DisplayedName =		"",
		DisplayPriority =	0,                                                    
		Description =		"",
		UpgradeType =		Modifier,
		TargetType =		Family,
		TargetName =		"Capital",
		UpgradeName =		"BUILDSPEED",
		UpgradeValue =		1.7,
	},	
	{ 
		Name =			"AllShipBuildSpeedHard",
		RequiredResearch =	"",                       
		RequiredSubSystems =	"",                               
		Cost = 			1,
		Time = 			1,
		DisplayedName =		"",
		DisplayPriority =	0,                                                    
		Description =		"",
		UpgradeType =		Modifier,
		TargetType =		Family,
		TargetName =		"Capital",
		UpgradeName =		"BUILDSPEED",
		UpgradeValue =		1.725,
	},	
	{ 
		Name =			"AllShipBuildSpeedExpert",
		RequiredResearch =	"",                       
		RequiredSubSystems =	"",                               
		Cost = 			1,
		Time = 			1,
		DisplayedName =		"",
		DisplayPriority =	0,                                                    
		Description =		"",
		UpgradeType =		Modifier,
		TargetType =		Family,
		TargetName =		"Capital",
		UpgradeName =		"BUILDSPEED",
		UpgradeValue =		1.75,
	},	
--AI resource rate
	{ 
		Name =			"ResourceCollectionRateHard",
		RequiredResearch =	"",                       
		RequiredSubSystems =	"",                               
		Cost = 			1,
		Time = 			1,
		DisplayedName =		"",
		DisplayPriority =	0,                                                    
		Description =		"",
		UpgradeType =		Modifier,
		TargetType =		Ship,
		TargetName = "kus_resourcecollector",
		UpgradeName =		"ResourceCollectionRate",
		UpgradeValue =		1.04,
	},	
	{ 
		Name =			"ResourceCollectionRateExpert",
		RequiredResearch =	"",                       
		RequiredSubSystems =	"",                               
		Cost = 			1,
		Time = 			1,
		DisplayedName =		"",
		DisplayPriority =	0,                                                    
		Description =		"",
		UpgradeType =		Modifier,
		TargetType =		Ship,
		TargetName = "kus_resourcecollector",
		UpgradeName =		"ResourceCollectionRate",
		UpgradeValue =		1.08,
	},
	--Special		
	{ 
		Name =			"MissileDestroyerVolley",
		RequiredResearch =	"",
		RequiredSubSystems =	"",
		Cost = 			1,
		Time = 			1,
		DisplayedName =		"",
		DisplayPriority =	0,
		Description =		"",
		UpgradeType =		Ability,
		TargetType =		Ship,
		TargetName =		"Kus_MissileDestroyer",
		UpgradeName =		"UseSpecialWeaponsInNormalAttack",		
	},
	{ 
		Name =			"HeavyCorvetteAttackBurst",
		RequiredResearch =	"",
		RequiredSubSystems =	"Research",
		Cost = 			1,
		Time = 			1,
		DisplayedName =		"",
		DisplayPriority =	0,
		Description =		"",
		UpgradeType =		Ability,
		TargetType =		Ship,
		TargetName =		"Kus_HeavyCorvette",
		UpgradeName =		"UseSpecialWeaponsInNormalAttack",		
	},		
}