flightManeuvers = { }

flightManeuvers[0] =
{
    name = "BarrelRoll",
    points =
    {
        {
           forward                           = {0, 0, 1},
           up                                = {0, 1, 0},
           wishForwardBackwardSpeed          = 1,
           wishLeftRightSpeed                = -2,
           wishUpDownSpeed                   = 0,
           wishRotationXSpeed                = 0,
           wishRotationYSpeed                = 0,
           wishRotationZSpeed                = 0,
           timeDelay                         = 0.04,
           ignoreOrientation                 = 0,
accelerationMultiplier=3,
rotationAccelerationMultiplier=6,
        },
        {
           forward                           = {0, 0, 1},
           up                                = {1, 0, 0},
           wishForwardBackwardSpeed          = 1,
           wishLeftRightSpeed                = -2,
           wishUpDownSpeed                   = 0,
           wishRotationXSpeed                = 0,
           wishRotationYSpeed                = 0,
           wishRotationZSpeed                = 0,
           timeDelay                         = 0.04,
           ignoreOrientation                 = 0,
accelerationMultiplier=3,
rotationAccelerationMultiplier=6,
        },
        {
           forward                           = {0, 0, 1},
           up                                = {0, -1, 0},
           wishForwardBackwardSpeed          = 1,
           wishLeftRightSpeed                = -2,
           wishUpDownSpeed                   = 0,
           wishRotationXSpeed                = 0,
           wishRotationYSpeed                = 0,
           wishRotationZSpeed                = 0,
           timeDelay                         = 0.04,
           ignoreOrientation                 = 0,
accelerationMultiplier=3,
rotationAccelerationMultiplier=6,
        },
        {
           forward                           = {0, 0, 1},
           up                                = {-1, -0, 0},
           wishForwardBackwardSpeed          = 1,
           wishLeftRightSpeed                = -2,
           wishUpDownSpeed                   = 0,
           wishRotationXSpeed                = 0,
           wishRotationYSpeed                = 0,
           wishRotationZSpeed                = 0,
           timeDelay                         = 0.04,
           ignoreOrientation                 = 0,
accelerationMultiplier=3,
rotationAccelerationMultiplier=6,
        },
        {
           forward                           = {0, 0, 1},
           up                                = {-0, 1, 0},
           wishForwardBackwardSpeed          = 1,
           wishLeftRightSpeed                = -2,
           wishUpDownSpeed                   = 0,
           wishRotationXSpeed                = 0,
           wishRotationYSpeed                = 0,
           wishRotationZSpeed                = 0,
           timeDelay                         = 0.04,
           ignoreOrientation                 = 0,
accelerationMultiplier=4,
rotationAccelerationMultiplier=6,
        },
    },
}

flightManeuvers[1] =
{
    name = "Loop",
    points =
    {
        {
           forward                           = {0, 0, 1},
           up                                = {0, 1, 0},
           wishForwardBackwardSpeed          = 0.3,
           wishLeftRightSpeed                = 0,
           wishUpDownSpeed                   = 0,
           wishRotationXSpeed                = 0,
           wishRotationYSpeed                = 0,
           wishRotationZSpeed                = 0,
           timeDelay                         = 0,
           ignoreOrientation                 = 0,
           accelerationMultiplier            = 1,
           rotationAccelerationMultiplier    = 2,
        },
        {
           forward                           = {0, 1, 0},
           up                                = {0, 0, -1},
           wishForwardBackwardSpeed          = 0.3,
           wishLeftRightSpeed                = 0,
           wishUpDownSpeed                   = 0,
           wishRotationXSpeed                = 0,
           wishRotationYSpeed                = 0,
           wishRotationZSpeed                = 0,
           timeDelay                         = 0,
           ignoreOrientation                 = 0,
           accelerationMultiplier            = 1,
           rotationAccelerationMultiplier    = 2,
        },
        {
           forward                           = {0, 0, -1},
           up                                = {0, -1, -0},
           wishForwardBackwardSpeed          = 0.3,
           wishLeftRightSpeed                = 0,
           wishUpDownSpeed                   = 0,
           wishRotationXSpeed                = 0,
           wishRotationYSpeed                = 0,
           wishRotationZSpeed                = 0,
           timeDelay                         = 0,
           ignoreOrientation                 = 0,
           accelerationMultiplier            = 1,
           rotationAccelerationMultiplier    = 2,
        },
        {
           forward                           = {0, -1, -0},
           up                                = {0, -0, 1},
           wishForwardBackwardSpeed          = 0.3,
           wishLeftRightSpeed                = 0,
           wishUpDownSpeed                   = 0,
           wishRotationXSpeed                = 0,
           wishRotationYSpeed                = 0,
           wishRotationZSpeed                = 0,
           timeDelay                         = 0,
           ignoreOrientation                 = 0,
           accelerationMultiplier            = 1,
           rotationAccelerationMultiplier    = 2,
        },
        {
           forward                           = {0, -0, 1},
           up                                = {0, 1, 0},
           wishForwardBackwardSpeed          = 0.3,
           wishLeftRightSpeed                = 0,
           wishUpDownSpeed                   = 0,
           wishRotationXSpeed                = 0,
           wishRotationYSpeed                = 0,
           wishRotationZSpeed                = 0,
           timeDelay                         = 0,
           ignoreOrientation                 = 0,
           accelerationMultiplier            = 1,
           rotationAccelerationMultiplier    = 2,
        },
    },
}

flightManeuvers[2] =
{
    name = "RollCW",
    points =
    {
        {
           forward                           = {0, 0, 1},
           up                                = {0, 1, 0},
           wishForwardBackwardSpeed          = 1,
           wishLeftRightSpeed                = 0,
           wishUpDownSpeed                   = 0,
           wishRotationXSpeed                = 0,
           wishRotationYSpeed                = 0,
           wishRotationZSpeed                = 360,
           timeDelay                         = 0.5,
           ignoreOrientation                 = 1,
           accelerationMultiplier            = 1,
rotationAccelerationMultiplier=6,
        },
        {
           forward                           = {0, 0, 1},
           up                                = {0, 1, 0},
           wishForwardBackwardSpeed          = 1,
           wishLeftRightSpeed                = 0,
           wishUpDownSpeed                   = 0,
           wishRotationXSpeed                = 0,
           wishRotationYSpeed                = 0,
           wishRotationZSpeed                = 0,
           timeDelay                         = 0.3,
           ignoreOrientation                 = 1,
           accelerationMultiplier            = 1,
rotationAccelerationMultiplier=7.2,
        },
    },
}

flightManeuvers[3] =
{
    name = "ImmelMann",
    points =
    {
        {
           forward                           = {0, 0, 1},
           up                                = {0, 1, 0},
           wishForwardBackwardSpeed          = 1,
           wishLeftRightSpeed                = 0,
           wishUpDownSpeed                   = 0,
           wishRotationXSpeed                = 0,
           wishRotationYSpeed                = 0,
           wishRotationZSpeed                = 0,
           timeDelay                         = 0,
           ignoreOrientation                 = 0,
accelerationMultiplier=4,
           rotationAccelerationMultiplier    = 3,
        },
        {
           forward                           = {0, 1, 0},
           up                                = {0, 0, -1},
           wishForwardBackwardSpeed          = 1,
           wishLeftRightSpeed                = 0,
           wishUpDownSpeed                   = 0,
           wishRotationXSpeed                = 0,
           wishRotationYSpeed                = 0,
           wishRotationZSpeed                = 0,
           timeDelay                         = 0,
           ignoreOrientation                 = 0,
accelerationMultiplier=4,
           rotationAccelerationMultiplier    = 3,
        },
        {
           forward                           = {0, 0, -1},
           up                                = {0, -1, -0},
           wishForwardBackwardSpeed          = 1,
           wishLeftRightSpeed                = 0,
           wishUpDownSpeed                   = 0,
           wishRotationXSpeed                = 0,
           wishRotationYSpeed                = 0,
           wishRotationZSpeed                = 0,
           timeDelay                         = 0,
           ignoreOrientation                 = 0,
accelerationMultiplier=4,
           rotationAccelerationMultiplier    = 3,
        },
        {
           forward                           = {-0, 0, -1},
           up                                = {1, -0, -0},
           wishForwardBackwardSpeed          = 1,
           wishLeftRightSpeed                = 0,
           wishUpDownSpeed                   = 0,
           wishRotationXSpeed                = 0,
           wishRotationYSpeed                = 0,
           wishRotationZSpeed                = 0,
           timeDelay                         = 0,
           ignoreOrientation                 = 0,
accelerationMultiplier=4,
           rotationAccelerationMultiplier    = 3,
        },
        {
           forward                           = {-0, -0, -1},
           up                                = {0, 1, -0},
           wishForwardBackwardSpeed          = 1,
           wishLeftRightSpeed                = 0,
           wishUpDownSpeed                   = 0,
           wishRotationXSpeed                = 0,
           wishRotationYSpeed                = 0,
           wishRotationZSpeed                = 0,
           timeDelay                         = 0.2,
           ignoreOrientation                 = 0,
accelerationMultiplier=4,
rotationAccelerationMultiplier=6,
        },
    },
}

flightManeuvers[4] =
{
    name = "Split_S",
    points =
    {
        {
           forward                           = {0, 0, 1},
           up                                = {0, 1, 0},
           wishForwardBackwardSpeed          = 0.2,
           wishLeftRightSpeed                = 0,
           wishUpDownSpeed                   = 0,
           wishRotationXSpeed                = 0,
           wishRotationYSpeed                = 0,
           wishRotationZSpeed                = 0,
           timeDelay                         = 0,
           ignoreOrientation                 = 0,
           accelerationMultiplier            = 1,
           rotationAccelerationMultiplier    = 2,
        },
        {
           forward                           = {0, 0, 1},
           up                                = {-1, 0, 0},
           wishForwardBackwardSpeed          = 0.2,
           wishLeftRightSpeed                = 0,
           wishUpDownSpeed                   = 0,
           wishRotationXSpeed                = 0,
           wishRotationYSpeed                = 0,
           wishRotationZSpeed                = 0,
           timeDelay                         = 0,
           ignoreOrientation                 = 0,
           accelerationMultiplier            = 1,
           rotationAccelerationMultiplier    = 2,
        },
        {
           forward                           = {-0, -0.651771, 0.758416},
           up                                = {-0, -0.758416, -0.651771},
           wishForwardBackwardSpeed          = 0.2,
           wishLeftRightSpeed                = 0,
           wishUpDownSpeed                   = 0,
           wishRotationXSpeed                = 0,
           wishRotationYSpeed                = 0,
           wishRotationZSpeed                = 0,
           timeDelay                         = 0,
           ignoreOrientation                 = 0,
           accelerationMultiplier            = 1,
           rotationAccelerationMultiplier    = 2,
        },
        {
           forward                           = {-0, -1, 0},
           up                                = {-0, -0, -1},
           wishForwardBackwardSpeed          = 0.2,
           wishLeftRightSpeed                = 0,
           wishUpDownSpeed                   = 0,
           wishRotationXSpeed                = 0,
           wishRotationYSpeed                = 0,
           wishRotationZSpeed                = 0,
           timeDelay                         = 0,
           ignoreOrientation                 = 0,
           accelerationMultiplier            = 1,
           rotationAccelerationMultiplier    = 2,
        },
        {
           forward                           = {-0, -0.573576, -0.819152},
           up                                = {0, 0.819152, -0.573576},
           wishForwardBackwardSpeed          = 0.2,
           wishLeftRightSpeed                = 0,
           wishUpDownSpeed                   = 0,
           wishRotationXSpeed                = 0,
           wishRotationYSpeed                = 0,
           wishRotationZSpeed                = 0,
           timeDelay                         = 0.3,
           ignoreOrientation                 = 0,
           accelerationMultiplier            = 1,
           rotationAccelerationMultiplier    = 2,
        },
    },
}

flightManeuvers[5] =
{
    name = "HalfRollCCW",
    points =
    {
        {
           forward                           = {0, 0, 1},
           up                                = {0, 1, 0},
           wishForwardBackwardSpeed          = 0.3,
           wishLeftRightSpeed                = 0,
           wishUpDownSpeed                   = 0,
           wishRotationXSpeed                = 0,
           wishRotationYSpeed                = 0,
           wishRotationZSpeed                = 0,
           timeDelay                         = 0,
           ignoreOrientation                 = 0,
           accelerationMultiplier            = 1,
           rotationAccelerationMultiplier    = 2,
        },
        {
           forward                           = {0, 0, 1},
           up                                = {1, 0, 0},
           wishForwardBackwardSpeed          = 0.3,
           wishLeftRightSpeed                = 0,
           wishUpDownSpeed                   = 0,
           wishRotationXSpeed                = 0,
           wishRotationYSpeed                = 0,
           wishRotationZSpeed                = 0,
           timeDelay                         = 0,
           ignoreOrientation                 = 0,
           accelerationMultiplier            = 1,
           rotationAccelerationMultiplier    = 2,
        },
        {
           forward                           = {0, 0, 1},
           up                                = {0, -1, 0},
           wishForwardBackwardSpeed          = 0.3,
           wishLeftRightSpeed                = 0,
           wishUpDownSpeed                   = 0,
           wishRotationXSpeed                = 0,
           wishRotationYSpeed                = 0,
           wishRotationZSpeed                = 0,
           timeDelay                         = 0,
           ignoreOrientation                 = 0,
           accelerationMultiplier            = 1,
           rotationAccelerationMultiplier    = 2,
        },
        {
           forward                           = {0, 0, 1},
           up                                = {0, -1, 0},
           wishForwardBackwardSpeed          = 0.3,
           wishLeftRightSpeed                = 0,
           wishUpDownSpeed                   = 0,
           wishRotationXSpeed                = 0,
           wishRotationYSpeed                = 0,
           wishRotationZSpeed                = 0,
           timeDelay                         = 0,
           ignoreOrientation                 = 0,
           accelerationMultiplier            = 1,
           rotationAccelerationMultiplier    = 2,
        },
    },
}

flightManeuvers[6] =
{
    name = "HalfRollCW",
    points =
    {
        {
           forward                           = {0, 0, 1},
           up                                = {0, 1, 0},
           wishForwardBackwardSpeed          = 0.3,
           wishLeftRightSpeed                = 0,
           wishUpDownSpeed                   = 0,
           wishRotationXSpeed                = 0,
           wishRotationYSpeed                = 0,
           wishRotationZSpeed                = 0,
           timeDelay                         = 0,
           ignoreOrientation                 = 0,
           accelerationMultiplier            = 1,
           rotationAccelerationMultiplier    = 2,
        },
        {
           forward                           = {0, 0, 1},
           up                                = {-1, 0, 0},
           wishForwardBackwardSpeed          = 0.3,
           wishLeftRightSpeed                = 0,
           wishUpDownSpeed                   = 0,
           wishRotationXSpeed                = 0,
           wishRotationYSpeed                = 0,
           wishRotationZSpeed                = 0,
           timeDelay                         = 0,
           ignoreOrientation                 = 0,
           accelerationMultiplier            = 1,
           rotationAccelerationMultiplier    = 2,
        },
        {
           forward                           = {0, 0, 1},
           up                                = {-0, -1, 0},
           wishForwardBackwardSpeed          = 0.3,
           wishLeftRightSpeed                = 0,
           wishUpDownSpeed                   = 0,
           wishRotationXSpeed                = 0,
           wishRotationYSpeed                = 0,
           wishRotationZSpeed                = 0,
           timeDelay                         = 0,
           ignoreOrientation                 = 0,
           accelerationMultiplier            = 1,
           rotationAccelerationMultiplier    = 2,
        },
        {
           forward                           = {0, 0, 1},
           up                                = {-0, -1, 0},
           wishForwardBackwardSpeed          = 0.3,
           wishLeftRightSpeed                = 0,
           wishUpDownSpeed                   = 0,
           wishRotationXSpeed                = 0,
           wishRotationYSpeed                = 0,
           wishRotationZSpeed                = 0,
           timeDelay                         = 0,
           ignoreOrientation                 = 0,
           accelerationMultiplier            = 1,
           rotationAccelerationMultiplier    = 2,
        },
    },
}

flightManeuvers[7] =
{
    name = "WingWaggle",
    points =
    {
        {
           forward                           = {0, 0, 1},
           up                                = {0, 1, 0},
           wishForwardBackwardSpeed          = 1,
           wishLeftRightSpeed                = 0,
           wishUpDownSpeed                   = 0,
           wishRotationXSpeed                = 0,
           wishRotationYSpeed                = 0,
           wishRotationZSpeed                = 360,
           timeDelay                         = 0.1,
           ignoreOrientation                 = 1,
           accelerationMultiplier            = 1,
           rotationAccelerationMultiplier    = 8,
        },
        {
           forward                           = {0, 0, 1},
           up                                = {0, 1, 0},
           wishForwardBackwardSpeed          = 1,
           wishLeftRightSpeed                = 0,
           wishUpDownSpeed                   = 0,
           wishRotationXSpeed                = 0,
           wishRotationYSpeed                = 0,
           wishRotationZSpeed                = 0,
           timeDelay                         = 0.3,
           ignoreOrientation                 = 1,
           accelerationMultiplier            = 1,
           rotationAccelerationMultiplier    = 7.2,
        },
    },
}

flightManeuvers[8] =
{
    name = "RollCCW",
    points =
    {
        {
           forward                           = {0, 0, 1},
           up                                = {0, 1, 0},
           wishForwardBackwardSpeed          = 1,
           wishLeftRightSpeed                = 0,
           wishUpDownSpeed                   = 0,
           wishRotationXSpeed                = 0,
           wishRotationYSpeed                = 0,
           wishRotationZSpeed                = -360,
           timeDelay                         = 0.5,
           ignoreOrientation                 = 1,
           accelerationMultiplier            = 1,
rotationAccelerationMultiplier=6,
        },
        {
           forward                           = {0, 0, 1},
           up                                = {0, 1, 0},
           wishForwardBackwardSpeed          = 1,
           wishLeftRightSpeed                = 0,
           wishUpDownSpeed                   = 0,
           wishRotationXSpeed                = 0,
           wishRotationYSpeed                = 0,
           wishRotationZSpeed                = 0,
           timeDelay                         = 0.3,
           ignoreOrientation                 = 1,
           accelerationMultiplier            = 1,
rotationAccelerationMultiplier=7.2,
        },
    },
}

flightManeuvers[9] =
{
    name = "BarrelRollCW",
    points =
    {
        {
           forward                           = {0, 0, 1},
           up                                = {0, 1, 0},
           wishForwardBackwardSpeed          = 1,
           wishLeftRightSpeed                = 2,
           wishUpDownSpeed                   = 0,
           wishRotationXSpeed                = 0,
           wishRotationYSpeed                = 0,
           wishRotationZSpeed                = 360,
           timeDelay                         = 0.6,
           ignoreOrientation                 = 1,
accelerationMultiplier=3,
rotationAccelerationMultiplier=6,
        },
        {
           forward                           = {0, 0, 1},
           up                                = {0, 1, 0},
           wishForwardBackwardSpeed          = 1,
           wishLeftRightSpeed                = 0,
           wishUpDownSpeed                   = 0,
           wishRotationXSpeed                = 0,
           wishRotationYSpeed                = 0,
           wishRotationZSpeed                = 0,
           timeDelay                         = 0.3,
           ignoreOrientation                 = 1,
accelerationMultiplier=3,
rotationAccelerationMultiplier=12,
        },
    },
}

flightManeuvers[10] =
{
    name = "JinkLeft",
    points =
    {
        {
           forward                           = {0, 0, 1},
           up                                = {0, 1, 0},
           wishForwardBackwardSpeed          = 0.6,
           wishLeftRightSpeed                = 1.3,
           wishUpDownSpeed                   = 0,
           wishRotationXSpeed                = 0,
           wishRotationYSpeed                = 0,
           wishRotationZSpeed                = 360,
           timeDelay                         = 0.1,
           ignoreOrientation                 = 1,
           accelerationMultiplier            = 1,
rotationAccelerationMultiplier=5,
        },
        {
           forward                           = {0, 0, 1},
           up                                = {0, 1, 0},
           wishForwardBackwardSpeed          = 1,
           wishLeftRightSpeed                = 0,
           wishUpDownSpeed                   = 0,
           wishRotationXSpeed                = 0,
           wishRotationYSpeed                = 0,
           wishRotationZSpeed                = 0,
           timeDelay                         = 0.3,
           ignoreOrientation                 = 1,
           accelerationMultiplier            = 1,
           rotationAccelerationMultiplier    = 2,
        },
    },
}

flightManeuvers[11] =
{
    name = "JinkLeftAndBack",
    points =
    {
        {
           forward                           = {0, 0, 1},
           up                                = {0, 1, 0},
           wishForwardBackwardSpeed          = 0.6,
           wishLeftRightSpeed                = 1.5,
           wishUpDownSpeed                   = 0,
           wishRotationXSpeed                = 0,
           wishRotationYSpeed                = 0,
           wishRotationZSpeed                = 360,
           timeDelay                         = 0.1,
           ignoreOrientation                 = 1,
           accelerationMultiplier            = 1.5,
rotationAccelerationMultiplier=9,
        },
        {
           forward                           = {0, 0, 1},
           up                                = {0, 1, 0},
           wishForwardBackwardSpeed          = 0.6,
           wishLeftRightSpeed                = -1.5,
           wishUpDownSpeed                   = 0,
           wishRotationXSpeed                = 0,
           wishRotationYSpeed                = 0,
           wishRotationZSpeed                = 0,
           timeDelay                         = 0.3,
           ignoreOrientation                 = 1,
           accelerationMultiplier            = 1.5,
rotationAccelerationMultiplier=7.2,
        },
    },
}

flightManeuvers[12] =
{
    name = "JinkRight",
    points =
    {
        {
           forward                           = {0, 0, 1},
           up                                = {0, 1, 0},
           wishForwardBackwardSpeed          = 0.6,
           wishLeftRightSpeed                = -1.3,
           wishUpDownSpeed                   = 0,
           wishRotationXSpeed                = 0,
           wishRotationYSpeed                = 0,
           wishRotationZSpeed                = -360,
           timeDelay                         = 0.1,
           ignoreOrientation                 = 1,
           accelerationMultiplier            = 1,
           rotationAccelerationMultiplier    = 5,
        },
        {
           forward                           = {0, 0, 1},
           up                                = {0, 1, 0},
           wishForwardBackwardSpeed          = 1,
           wishLeftRightSpeed                = 0,
           wishUpDownSpeed                   = 0,
           wishRotationXSpeed                = 0,
           wishRotationYSpeed                = 0,
           wishRotationZSpeed                = 0,
           timeDelay                         = 0.3,
           ignoreOrientation                 = 1,
           accelerationMultiplier            = 1,
           rotationAccelerationMultiplier    = 2,
        },
    },
}

flightManeuvers[13] =
{
    name = "ImmelMann_speedy",
    points =
    {
        {
           forward                           = {0, 0, 1},
           up                                = {0, 1, 0},
           wishForwardBackwardSpeed          = 0.7,
           wishLeftRightSpeed                = 0,
           wishUpDownSpeed                   = 0,
           wishRotationXSpeed                = -360,
           wishRotationYSpeed                = 0,
           wishRotationZSpeed                = 0,
           timeDelay                         = 0.1,
           ignoreOrientation                 = 1,
           accelerationMultiplier            = 1,
rotationAccelerationMultiplier=6,
        },
        {
           forward                           = {0, 0, 1},
           up                                = {0, 1, 0},
           wishForwardBackwardSpeed          = 0.7,
           wishLeftRightSpeed                = 0,
           wishUpDownSpeed                   = 2,
           wishRotationXSpeed                = -360,
           wishRotationYSpeed                = 0,
           wishRotationZSpeed                = -25.396826,
           timeDelay                         = 0.2,
           ignoreOrientation                 = 1,
           accelerationMultiplier            = 1.5,
rotationAccelerationMultiplier=6,
        },
        {
           forward                           = {-0, 0, -1},
           up                                = {0, 1, 0},
           wishForwardBackwardSpeed          = 0.7,
           wishLeftRightSpeed                = 0,
           wishUpDownSpeed                   = 0,
           wishRotationXSpeed                = 0,
           wishRotationYSpeed                = 0,
           wishRotationZSpeed                = 0,
           timeDelay                         = 0.04,
           ignoreOrientation                 = 0,
accelerationMultiplier=3,
rotationAccelerationMultiplier=12,
        },
        {
           forward                           = {-0, 0, -1},
           up                                = {0, 1, 0},
           wishForwardBackwardSpeed          = 0.7,
           wishLeftRightSpeed                = 0,
           wishUpDownSpeed                   = 0,
           wishRotationXSpeed                = 0,
           wishRotationYSpeed                = 0,
           wishRotationZSpeed                = 360,
           timeDelay                         = 0.04,
           ignoreOrientation                 = 1,
           accelerationMultiplier            = 1,
rotationAccelerationMultiplier=6,
        },
        {
           forward                           = {-0, 0, -1},
           up                                = {0, 1, 0},
           wishForwardBackwardSpeed          = 0.7,
           wishLeftRightSpeed                = 0,
           wishUpDownSpeed                   = 0,
           wishRotationXSpeed                = 0,
           wishRotationYSpeed                = 0,
           wishRotationZSpeed                = 0,
           timeDelay                         = 0.04,
           ignoreOrientation                 = 1,
           accelerationMultiplier            = 1,
rotationAccelerationMultiplier=8,
        },
    },
}

flightManeuvers[14] =
{
    name = "Split_S_speedy",
    points =
    {
        {
           forward                           = {0, 0, 1},
           up                                = {0, 1, 0},
           wishForwardBackwardSpeed          = 0.7,
           wishLeftRightSpeed                = 0,
           wishUpDownSpeed                   = 0,
           wishRotationXSpeed                = 0,
           wishRotationYSpeed                = 0,
           wishRotationZSpeed                = 370,
           timeDelay                         = 0.35,
           ignoreOrientation                 = 1,
           accelerationMultiplier            = 1,
rotationAccelerationMultiplier=6,
        },
        {
           forward                           = {0, 0, 1},
           up                                = {0, 1, 0},
           wishForwardBackwardSpeed          = 0.7,
           wishLeftRightSpeed                = 0,
           wishUpDownSpeed                   = 0,
           wishRotationXSpeed                = 0,
           wishRotationYSpeed                = 0,
           wishRotationZSpeed                = 0,
           timeDelay                         = 0.1,
           ignoreOrientation                 = 1,
           accelerationMultiplier            = 1,
rotationAccelerationMultiplier=10,
        },
        {
           forward                           = {0, 0, 1},
           up                                = {0, 1, 0},
           wishForwardBackwardSpeed          = 0.7,
           wishLeftRightSpeed                = 0,
           wishUpDownSpeed                   = 0,
           wishRotationXSpeed                = -360,
           wishRotationYSpeed                = 0,
           wishRotationZSpeed                = 0,
           timeDelay                         = 0.1,
           ignoreOrientation                 = 1,
           accelerationMultiplier            = 1,
rotationAccelerationMultiplier=6,
        },
        {
           forward                           = {0, 0, 1},
           up                                = {0, 1, 0},
           wishForwardBackwardSpeed          = 0.7,
           wishLeftRightSpeed                = 0,
           wishUpDownSpeed                   = 2,
           wishRotationXSpeed                = -360,
           wishRotationYSpeed                = 0,
           wishRotationZSpeed                = 0,
           timeDelay                         = 0.2,
           ignoreOrientation                 = 1,
           accelerationMultiplier            = 1.5,
rotationAccelerationMultiplier=6,
        },
        {
           forward                           = {-0, 0, -1},
           up                                = {0, 1, 0},
           wishForwardBackwardSpeed          = 0.7,
           wishLeftRightSpeed                = 0,
           wishUpDownSpeed                   = 0,
           wishRotationXSpeed                = 0,
           wishRotationYSpeed                = 0,
           wishRotationZSpeed                = 0,
           timeDelay                         = 0.04,
           ignoreOrientation                 = 0,
accelerationMultiplier=3,
rotationAccelerationMultiplier=12,
        },
    },
}

flightManeuvers[15] =
{
    name = "OneEightyDegRightTurn",
    points =
    {
        {
           forward                           = {0, 0, 1},
           up                                = {0, 1, 0},
           wishForwardBackwardSpeed          = 0.7,
           wishLeftRightSpeed                = 0,
           wishUpDownSpeed                   = 0,
           wishRotationXSpeed                = 0,
           wishRotationYSpeed                = 0,
           wishRotationZSpeed                = 360,
           timeDelay                         = 0.2,
           ignoreOrientation                 = 1,
           accelerationMultiplier            = 1,
rotationAccelerationMultiplier=6,
        },
        {
           forward                           = {0, 0, 1},
           up                                = {0, 1, 0},
           wishForwardBackwardSpeed          = 0.7,
           wishLeftRightSpeed                = 0,
           wishUpDownSpeed                   = 0,
           wishRotationXSpeed                = 0,
           wishRotationYSpeed                = 0,
           wishRotationZSpeed                = 0,
           timeDelay                         = 0.04,
           ignoreOrientation                 = 1,
           accelerationMultiplier            = 1,
rotationAccelerationMultiplier=8,
        },
        {
           forward                           = {0, 0, 1},
           up                                = {0, 1, 0},
           wishForwardBackwardSpeed          = 0.7,
           wishLeftRightSpeed                = 0,
           wishUpDownSpeed                   = 0,
           wishRotationXSpeed                = -360,
           wishRotationYSpeed                = 0,
           wishRotationZSpeed                = 0,
           timeDelay                         = 0.1,
           ignoreOrientation                 = 1,
           accelerationMultiplier            = 1,
rotationAccelerationMultiplier=6,
        },
        {
           forward                           = {0, 0, 1},
           up                                = {0, 1, 0},
           wishForwardBackwardSpeed          = 0.7,
           wishLeftRightSpeed                = 0,
           wishUpDownSpeed                   = 2,
           wishRotationXSpeed                = -360,
           wishRotationYSpeed                = 0,
           wishRotationZSpeed                = 0,
           timeDelay                         = 0.2,
           ignoreOrientation                 = 1,
           accelerationMultiplier            = 1.5,
rotationAccelerationMultiplier=6,
        },
        {
           forward                           = {-0, 0, -1},
           up                                = {0, 1, 0},
           wishForwardBackwardSpeed          = 0.7,
           wishLeftRightSpeed                = 0,
           wishUpDownSpeed                   = 0,
           wishRotationXSpeed                = 0,
           wishRotationYSpeed                = 0,
           wishRotationZSpeed                = 0,
           timeDelay                         = 0.04,
           ignoreOrientation                 = 0,
accelerationMultiplier=3,
rotationAccelerationMultiplier=12,
        },
    },
}

flightManeuvers[16] =
{
    name = "RollCW_slow",
    points =
    {
        {
           forward                           = {0, 0, 1},
           up                                = {0, 1, 0},
           wishForwardBackwardSpeed          = 1,
           wishLeftRightSpeed                = 0,
           wishUpDownSpeed                   = 0,
           wishRotationXSpeed                = 0,
           wishRotationYSpeed                = 0,
           wishRotationZSpeed                = 115,
           timeDelay                         = 1.5,
           ignoreOrientation                 = 1,
           accelerationMultiplier            = 1,
rotationAccelerationMultiplier=1.46,
        },
        {
           forward                           = {0, 0, 1},
           up                                = {0, 1, 0},
           wishForwardBackwardSpeed          = 1,
           wishLeftRightSpeed                = 0,
           wishUpDownSpeed                   = 0,
           wishRotationXSpeed                = 0,
           wishRotationYSpeed                = 0,
           wishRotationZSpeed                = 0,
           timeDelay                         = 0.3,
           ignoreOrientation                 = 1,
           accelerationMultiplier            = 1,
rotationAccelerationMultiplier=7.2,
        },
    },
}

flightManeuvers[17] =
{
    name = "Empty",
    points =
    {
        {
           forward                           = {0, 0, 1},
           up                                = {0, 1, 0},
           wishForwardBackwardSpeed          = 0.7,
           wishLeftRightSpeed                = 0,
           wishUpDownSpeed                   = 0,
           wishRotationXSpeed                = 0,
           wishRotationYSpeed                = 0,
           wishRotationZSpeed                = 0,
           timeDelay                         = 0.04,
           ignoreOrientation                 = 1,
           accelerationMultiplier            = 1,
           rotationAccelerationMultiplier    = 2,
        },
    },
}

flightManeuvers[18] =
{
    name = "OneEightyDegLeftTurn",
    points =
    {
        {
           forward                           = {0, 0, 1},
           up                                = {0, 1, 0},
           wishForwardBackwardSpeed          = 0.7,
           wishLeftRightSpeed                = 0,
           wishUpDownSpeed                   = 0,
           wishRotationXSpeed                = 0,
           wishRotationYSpeed                = 0,
           wishRotationZSpeed                = -360,
           timeDelay                         = 0.2,
           ignoreOrientation                 = 1,
           accelerationMultiplier            = 1,
rotationAccelerationMultiplier=6,
        },
        {
           forward                           = {0, 0, 1},
           up                                = {0, 1, 0},
           wishForwardBackwardSpeed          = 0.7,
           wishLeftRightSpeed                = 0,
           wishUpDownSpeed                   = 0,
           wishRotationXSpeed                = 0,
           wishRotationYSpeed                = 0,
           wishRotationZSpeed                = 0,
           timeDelay                         = 0.04,
           ignoreOrientation                 = 1,
           accelerationMultiplier            = 1,
rotationAccelerationMultiplier=8,
        },
        {
           forward                           = {0, 0, 1},
           up                                = {0, 1, 0},
           wishForwardBackwardSpeed          = 0.7,
           wishLeftRightSpeed                = 0,
           wishUpDownSpeed                   = 0,
           wishRotationXSpeed                = -360,
           wishRotationYSpeed                = 0,
           wishRotationZSpeed                = 0,
           timeDelay                         = 0.1,
           ignoreOrientation                 = 1,
           accelerationMultiplier            = 1,
rotationAccelerationMultiplier=6,
        },
        {
           forward                           = {0, 0, 1},
           up                                = {0, 1, 0},
           wishForwardBackwardSpeed          = 0.7,
           wishLeftRightSpeed                = 0,
           wishUpDownSpeed                   = 2,
           wishRotationXSpeed                = -360,
           wishRotationYSpeed                = 0,
           wishRotationZSpeed                = 0,
           timeDelay                         = 0.2,
           ignoreOrientation                 = 1,
           accelerationMultiplier            = 1.5,
rotationAccelerationMultiplier=6,
        },
        {
           forward                           = {-0, 0, -1},
           up                                = {0, 1, 0},
           wishForwardBackwardSpeed          = 0.7,
           wishLeftRightSpeed                = 0,
           wishUpDownSpeed                   = 0,
           wishRotationXSpeed                = 0,
           wishRotationYSpeed                = 0,
           wishRotationZSpeed                = 0,
           timeDelay                         = 0.04,
           ignoreOrientation                 = 0,
accelerationMultiplier=3,
rotationAccelerationMultiplier=12,
        },
    },
}

flightManeuvers[19] =
{
    name = "RollCCW_slow",
    points =
    {
        {
           forward                           = {0, 0, 1},
           up                                = {0, 1, 0},
           wishForwardBackwardSpeed          = 1,
           wishLeftRightSpeed                = 0,
           wishUpDownSpeed                   = 0,
           wishRotationXSpeed                = 0,
           wishRotationYSpeed                = 0,
           wishRotationZSpeed                = -115,
           timeDelay                         = 1.5,
           ignoreOrientation                 = 1,
           accelerationMultiplier            = 1,
rotationAccelerationMultiplier=1.46,
        },
        {
           forward                           = {0, 0, 1},
           up                                = {0, 1, 0},
           wishForwardBackwardSpeed          = 1,
           wishLeftRightSpeed                = 0,
           wishUpDownSpeed                   = 0,
           wishRotationXSpeed                = 0,
           wishRotationYSpeed                = 0,
           wishRotationZSpeed                = 0,
           timeDelay                         = 0.3,
           ignoreOrientation                 = 1,
           accelerationMultiplier            = 1,
           rotationAccelerationMultiplier    = 7.2,
        },
    },
}

flightManeuvers[20] =
{
    name = "NinetyDegRightTurn",
    points =
    {
        {
           forward                           = {0, 0, 1},
           up                                = {0, 1, 0},
           wishForwardBackwardSpeed          = 0.7,
           wishLeftRightSpeed                = 0,
           wishUpDownSpeed                   = 0,
           wishRotationXSpeed                = 0,
           wishRotationYSpeed                = 0,
           wishRotationZSpeed                = 360,
           timeDelay                         = 0.2,
           ignoreOrientation                 = 1,
           accelerationMultiplier            = 1,
rotationAccelerationMultiplier=6,
        },
        {
           forward                           = {0, 0, 1},
           up                                = {0, 1, 0},
           wishForwardBackwardSpeed          = 0.7,
           wishLeftRightSpeed                = 0,
           wishUpDownSpeed                   = 0,
           wishRotationXSpeed                = 0,
           wishRotationYSpeed                = 0,
           wishRotationZSpeed                = 0,
           timeDelay                         = 0.04,
           ignoreOrientation                 = 1,
           accelerationMultiplier            = 1,
rotationAccelerationMultiplier=8,
        },
        {
           forward                           = {0, 0, 1},
           up                                = {0, 1, 0},
           wishForwardBackwardSpeed          = 0.7,
           wishLeftRightSpeed                = 0,
           wishUpDownSpeed                   = 0,
           wishRotationXSpeed                = -360,
           wishRotationYSpeed                = 0,
           wishRotationZSpeed                = 0,
           timeDelay                         = 0.1,
           ignoreOrientation                 = 1,
           accelerationMultiplier            = 1,
rotationAccelerationMultiplier=6,
        },
        {
           forward                           = {0, 0, 1},
           up                                = {0, 1, 0},
           wishForwardBackwardSpeed          = 0.7,
           wishLeftRightSpeed                = 0,
           wishUpDownSpeed                   = 2,
           wishRotationXSpeed                = -360,
           wishRotationYSpeed                = 0,
           wishRotationZSpeed                = 0,
           timeDelay                         = 0.1,
           ignoreOrientation                 = 1,
           accelerationMultiplier            = 1.5,
rotationAccelerationMultiplier=6,
        },
        {
           forward                           = {-1, 0, 0},
           up                                = {0, 1, 0},
           wishForwardBackwardSpeed          = 0.7,
           wishLeftRightSpeed                = 0,
           wishUpDownSpeed                   = 0,
           wishRotationXSpeed                = 0,
           wishRotationYSpeed                = 0,
           wishRotationZSpeed                = 0,
           timeDelay                         = 0.04,
           ignoreOrientation                 = 0,
accelerationMultiplier=3,
rotationAccelerationMultiplier=12,
        },
    },
}

flightManeuvers[21] =
{
    name = "NinetyDegLeftTurn",
    points =
    {
        {
           forward                           = {0, 0, 1},
           up                                = {0, 1, 0},
           wishForwardBackwardSpeed          = 0.7,
           wishLeftRightSpeed                = 0,
           wishUpDownSpeed                   = 0,
           wishRotationXSpeed                = 0,
           wishRotationYSpeed                = 0,
           wishRotationZSpeed                = -360,
           timeDelay                         = 0.2,
           ignoreOrientation                 = 1,
           accelerationMultiplier            = 1,
rotationAccelerationMultiplier=6,
        },
        {
           forward                           = {0, 0, 1},
           up                                = {0, 1, 0},
           wishForwardBackwardSpeed          = 0.7,
           wishLeftRightSpeed                = 0,
           wishUpDownSpeed                   = 0,
           wishRotationXSpeed                = 0,
           wishRotationYSpeed                = 0,
           wishRotationZSpeed                = 0,
           timeDelay                         = 0.04,
           ignoreOrientation                 = 1,
           accelerationMultiplier            = 1,
rotationAccelerationMultiplier=8,
        },
        {
           forward                           = {0, 0, 1},
           up                                = {0, 1, 0},
           wishForwardBackwardSpeed          = 0.7,
           wishLeftRightSpeed                = 0,
           wishUpDownSpeed                   = 0,
           wishRotationXSpeed                = -360,
           wishRotationYSpeed                = 0,
           wishRotationZSpeed                = 0,
           timeDelay                         = 0.1,
           ignoreOrientation                 = 1,
           accelerationMultiplier            = 1,
rotationAccelerationMultiplier=6,
        },
        {
           forward                           = {0, 0, 1},
           up                                = {0, 1, 0},
           wishForwardBackwardSpeed          = 0.7,
           wishLeftRightSpeed                = 0,
           wishUpDownSpeed                   = 2,
           wishRotationXSpeed                = -360,
           wishRotationYSpeed                = 0,
           wishRotationZSpeed                = 0,
           timeDelay                         = 0.1,
           ignoreOrientation                 = 1,
           accelerationMultiplier            = 1.5,
rotationAccelerationMultiplier=6,
        },
        {
           forward                           = {1, 0, 0},
           up                                = {0, 1, 0},
           wishForwardBackwardSpeed          = 0.7,
           wishLeftRightSpeed                = 0,
           wishUpDownSpeed                   = 0,
           wishRotationXSpeed                = 0,
           wishRotationYSpeed                = 0,
           wishRotationZSpeed                = 0,
           timeDelay                         = 0.04,
           ignoreOrientation                 = 0,
accelerationMultiplier=3,
rotationAccelerationMultiplier=12,
        },
    },
}

flightManeuvers[22] =
{
    name = "JinkRightAndBack",
    points =
    {
        {
           forward                           = {0, 0, 1},
           up                                = {0, 1, 0},
           wishForwardBackwardSpeed          = 0.6,
           wishLeftRightSpeed                = -1.5,
           wishUpDownSpeed                   = 0,
           wishRotationXSpeed                = 0,
           wishRotationYSpeed                = 0,
           wishRotationZSpeed                = -360,
           timeDelay                         = 0.1,
           ignoreOrientation                 = 1,
           accelerationMultiplier            = 1.5,
rotationAccelerationMultiplier=10,
        },
        {
           forward                           = {0, 0, 1},
           up                                = {0, 1, 0},
           wishForwardBackwardSpeed          = 0.6,
           wishLeftRightSpeed                = 1.5,
           wishUpDownSpeed                   = 0,
           wishRotationXSpeed                = 0,
           wishRotationYSpeed                = 0,
           wishRotationZSpeed                = 0,
           timeDelay                         = 0.3,
           ignoreOrientation                 = 1,
           accelerationMultiplier            = 1.5,
rotationAccelerationMultiplier=7.2,
        },
    },
}


flightManeuvers[23]={name="HW1BarrelRoll",
points={{forward={0,0,1},
up={0,1,0},
wishForwardBackwardSpeed=1,
wishLeftRightSpeed=0,
wishUpDownSpeed=0,
wishRotationXSpeed=0,
wishRotationYSpeed=0,
wishRotationZSpeed=0,
timeDelay=0.3,
ignoreOrientation=0,
accelerationMultiplier=1,
rotationAccelerationMultiplier=1},

	{forward={0,0,1},
up={0,1,0},
wishForwardBackwardSpeed=1,
wishLeftRightSpeed=-2,
wishUpDownSpeed=0,
wishRotationXSpeed=0,
wishRotationYSpeed=0,
wishRotationZSpeed=0,
timeDelay=0.04,
ignoreOrientation=0,
accelerationMultiplier=1,
rotationAccelerationMultiplier=1},

	{forward={0,0,1},
up={1,0,0},
wishForwardBackwardSpeed=1,
wishLeftRightSpeed=-2,
wishUpDownSpeed=0,
wishRotationXSpeed=0,
wishRotationYSpeed=0,
wishRotationZSpeed=0,
timeDelay=0.04,
ignoreOrientation=0,
accelerationMultiplier=1,
rotationAccelerationMultiplier=1},

	{forward={0,0,1},
up={0,-1,0},
wishForwardBackwardSpeed=1,
wishLeftRightSpeed=-2,
wishUpDownSpeed=0,
wishRotationXSpeed=0,
wishRotationYSpeed=0,
wishRotationZSpeed=0,
timeDelay=0.04,
ignoreOrientation=0,
accelerationMultiplier=1,
rotationAccelerationMultiplier=1},

	{forward={0,0,1},
up={-1,0,0},
wishForwardBackwardSpeed=1,
wishLeftRightSpeed=-2,
wishUpDownSpeed=0,
wishRotationXSpeed=0,
wishRotationYSpeed=0,
wishRotationZSpeed=0,
timeDelay=0.04,
ignoreOrientation=0,
accelerationMultiplier=1,
rotationAccelerationMultiplier=1},

	{forward={0,0,1},
up={0,1,0},
wishForwardBackwardSpeed=1,
wishLeftRightSpeed=-2,
wishUpDownSpeed=0,
wishRotationXSpeed=0,
wishRotationYSpeed=0,
wishRotationZSpeed=0,
timeDelay=0.04,
ignoreOrientation=0,
accelerationMultiplier=1,
rotationAccelerationMultiplier=1}}};

flightManeuvers[24]={name="HW1Loop",
points={{forward={0,0,1},
up={0,1,0},
wishForwardBackwardSpeed=0.3,
wishLeftRightSpeed=0,
wishUpDownSpeed=0,
wishRotationXSpeed=0,
wishRotationYSpeed=0,
wishRotationZSpeed=0,
timeDelay=0,
ignoreOrientation=0,
accelerationMultiplier=1,
rotationAccelerationMultiplier=1},

	{forward={0,1,0},
up={0,0,-1},
wishForwardBackwardSpeed=0.3,
wishLeftRightSpeed=0,
wishUpDownSpeed=0,
wishRotationXSpeed=0,
wishRotationYSpeed=0,
wishRotationZSpeed=0,
timeDelay=0,
ignoreOrientation=0,
accelerationMultiplier=1,
rotationAccelerationMultiplier=1},

	{forward={0,0,-1},
up={0,-1,0},
wishForwardBackwardSpeed=0.3,
wishLeftRightSpeed=0,
wishUpDownSpeed=0,
wishRotationXSpeed=0,
wishRotationYSpeed=0,
wishRotationZSpeed=0,
timeDelay=0,
ignoreOrientation=0,
accelerationMultiplier=1,
rotationAccelerationMultiplier=1},

	{forward={0,-1,0},
up={0,0,1},
wishForwardBackwardSpeed=0.3,
wishLeftRightSpeed=0,
wishUpDownSpeed=0,
wishRotationXSpeed=0,
wishRotationYSpeed=0,
wishRotationZSpeed=0,
timeDelay=0,
ignoreOrientation=0,
accelerationMultiplier=1,
rotationAccelerationMultiplier=1},

	{forward={0,0,1},
up={0,1,0},
wishForwardBackwardSpeed=0.3,
wishLeftRightSpeed=0,
wishUpDownSpeed=0,
wishRotationXSpeed=0,
wishRotationYSpeed=0,
wishRotationZSpeed=0,
timeDelay=0,
ignoreOrientation=0,
accelerationMultiplier=1,
rotationAccelerationMultiplier=1}}};

flightManeuvers[25]={name="HW1RollCW",
points={{forward={0,
	0,
	1},
up={0,
	1,
	0},
wishForwardBackwardSpeed=1,
wishLeftRightSpeed=0,
wishUpDownSpeed=0,
wishRotationXSpeed=0,
wishRotationYSpeed=0,
wishRotationZSpeed=360,
timeDelay=0.5,
ignoreOrientation=1,
accelerationMultiplier=1,
rotationAccelerationMultiplier=1},
	{forward={0,
	0,
	1},
up={0,
	1,
	0},
wishForwardBackwardSpeed=1,
wishLeftRightSpeed=0,
wishUpDownSpeed=0,
wishRotationXSpeed=0,
wishRotationYSpeed=0,
wishRotationZSpeed=0,
timeDelay=0.3,
ignoreOrientation=1,
accelerationMultiplier=1,
rotationAccelerationMultiplier=1}}};

flightManeuvers[26]={name="HW1ImmelMann",
points={{forward={0,0,1},
up={0,1,0},
wishForwardBackwardSpeed=0.7,
wishLeftRightSpeed=0,
wishUpDownSpeed=0,
wishRotationXSpeed=0,
wishRotationYSpeed=0,
wishRotationZSpeed=0,
timeDelay=0,
ignoreOrientation=0,
accelerationMultiplier=0.5,
rotationAccelerationMultiplier=1},

	{forward={0,1,0},
up={0,0,-1},
wishForwardBackwardSpeed=1,
wishLeftRightSpeed=0,
wishUpDownSpeed=0,
wishRotationXSpeed=0,
wishRotationYSpeed=0,
wishRotationZSpeed=0,
timeDelay=0,
ignoreOrientation=0,
accelerationMultiplier=0.5,
rotationAccelerationMultiplier=1},
	{forward={0,0,-1},
up={0,-1,0},
wishForwardBackwardSpeed=1,
wishLeftRightSpeed=0,
wishUpDownSpeed=0,
wishRotationXSpeed=0,
wishRotationYSpeed=0,
wishRotationZSpeed=0,
timeDelay=0,
ignoreOrientation=0,
accelerationMultiplier=0.5,
rotationAccelerationMultiplier=1},
	{forward={0,0,-1},
up={1,0,0},
wishForwardBackwardSpeed=1,
wishLeftRightSpeed=0,
wishUpDownSpeed=0,
wishRotationXSpeed=0,
wishRotationYSpeed=0,
wishRotationZSpeed=0,
timeDelay=0,
ignoreOrientation=0,
accelerationMultiplier=0.5,
rotationAccelerationMultiplier=1},
	{forward={0,0,-1},
up={0,1,0},
wishForwardBackwardSpeed=1,
wishLeftRightSpeed=0,
wishUpDownSpeed=0,
wishRotationXSpeed=0,
wishRotationYSpeed=0,
wishRotationZSpeed=0,
timeDelay=0.2,
ignoreOrientation=0,
accelerationMultiplier=0.5,
rotationAccelerationMultiplier=1}}};

flightManeuvers[27]={name="HW1Split_S",
points={{forward={0,0,1},
up={0,1,0},
wishForwardBackwardSpeed=0.7,
wishLeftRightSpeed=0,
wishUpDownSpeed=0,
wishRotationXSpeed=0,
wishRotationYSpeed=0,
wishRotationZSpeed=0,
timeDelay=0,
ignoreOrientation=0,
accelerationMultiplier=0.5,
rotationAccelerationMultiplier=1},

	{forward={0,0,1},
up={-1,0,0},
wishForwardBackwardSpeed=1,
wishLeftRightSpeed=0,
wishUpDownSpeed=0,
wishRotationXSpeed=0,
wishRotationYSpeed=0,
wishRotationZSpeed=0,
timeDelay=0,
ignoreOrientation=0,
accelerationMultiplier=0.5,
rotationAccelerationMultiplier=1},

	{forward={0,-0.651771,0.758416},
up={0,-0.758416,-0.651771},
wishForwardBackwardSpeed=1,
wishLeftRightSpeed=0,
wishUpDownSpeed=0,
wishRotationXSpeed=0,
wishRotationYSpeed=0,
wishRotationZSpeed=0,
timeDelay=0,
ignoreOrientation=0,
accelerationMultiplier=0.5,
rotationAccelerationMultiplier=1},

	{forward={0,-1,0},
up={0,0,-1},
wishForwardBackwardSpeed=1,
wishLeftRightSpeed=0,
wishUpDownSpeed=0,
wishRotationXSpeed=0,
wishRotationYSpeed=0,
wishRotationZSpeed=0,
timeDelay=0,
ignoreOrientation=0,
accelerationMultiplier=0.5,
rotationAccelerationMultiplier=1},

	{forward={0,-0.573576,-0.819152},
up={0,0.819152,-0.573576},
wishForwardBackwardSpeed=1,
wishLeftRightSpeed=0,
wishUpDownSpeed=0,
wishRotationXSpeed=0,
wishRotationYSpeed=0,
wishRotationZSpeed=0,
timeDelay=0.3,
ignoreOrientation=0,
accelerationMultiplier=0.5,
rotationAccelerationMultiplier=1}}};

flightManeuvers[28]={name="HW1HalfRollCCW",
points={{forward={0,
	0,
	1},
up={0,
	1,
	0},
wishForwardBackwardSpeed=0.3,
wishLeftRightSpeed=0,
wishUpDownSpeed=0,
wishRotationXSpeed=0,
wishRotationYSpeed=0,
wishRotationZSpeed=0,
timeDelay=0,
ignoreOrientation=0,
accelerationMultiplier=1,
rotationAccelerationMultiplier=1},
	{forward={0,
	0,
	1},
up={1,
	0,
	0},
wishForwardBackwardSpeed=0.3,
wishLeftRightSpeed=0,
wishUpDownSpeed=0,
wishRotationXSpeed=0,
wishRotationYSpeed=0,
wishRotationZSpeed=0,
timeDelay=0,
ignoreOrientation=0,
accelerationMultiplier=1,
rotationAccelerationMultiplier=1},
	{forward={0,
	0,
	1},
up={0,
	-1,
	0},
wishForwardBackwardSpeed=0.3,
wishLeftRightSpeed=0,
wishUpDownSpeed=0,
wishRotationXSpeed=0,
wishRotationYSpeed=0,
wishRotationZSpeed=0,
timeDelay=0,
ignoreOrientation=0,
accelerationMultiplier=1,
rotationAccelerationMultiplier=1},
	{forward={0,
	0,
	1},
up={0,
	-1,
	0},
wishForwardBackwardSpeed=0.3,
wishLeftRightSpeed=0,
wishUpDownSpeed=0,
wishRotationXSpeed=0,
wishRotationYSpeed=0,
wishRotationZSpeed=0,
timeDelay=0,
ignoreOrientation=0,
accelerationMultiplier=1,
rotationAccelerationMultiplier=1}}};

flightManeuvers[29]={name="HW1HalfRollCW",
points={{forward={0,
	0,
	1},
up={0,
	1,
	0},
wishForwardBackwardSpeed=0.3,
wishLeftRightSpeed=0,
wishUpDownSpeed=0,
wishRotationXSpeed=0,
wishRotationYSpeed=0,
wishRotationZSpeed=0,
timeDelay=0,
ignoreOrientation=0,
accelerationMultiplier=1,
rotationAccelerationMultiplier=1},
	{forward={0,
	0,
	1},
up={-1,
	0,
	0},
wishForwardBackwardSpeed=0.3,
wishLeftRightSpeed=0,
wishUpDownSpeed=0,
wishRotationXSpeed=0,
wishRotationYSpeed=0,
wishRotationZSpeed=0,
timeDelay=0,
ignoreOrientation=0,
accelerationMultiplier=1,
rotationAccelerationMultiplier=1},
	{forward={0,
	0,
	1},
up={0,
	-1,
	0},
wishForwardBackwardSpeed=0.3,
wishLeftRightSpeed=0,
wishUpDownSpeed=0,
wishRotationXSpeed=0,
wishRotationYSpeed=0,
wishRotationZSpeed=0,
timeDelay=0,
ignoreOrientation=0,
accelerationMultiplier=1,
rotationAccelerationMultiplier=1},
	{forward={0,
	0,
	1},
up={0,
	-1,
	0},
wishForwardBackwardSpeed=0.3,
wishLeftRightSpeed=0,
wishUpDownSpeed=0,
wishRotationXSpeed=0,
wishRotationYSpeed=0,
wishRotationZSpeed=0,
timeDelay=0,
ignoreOrientation=0,
accelerationMultiplier=1,
rotationAccelerationMultiplier=1}}};

flightManeuvers[30]={name="HW1WingWaggle",
points={{forward={0,0,1},
up={0,1,0},
wishForwardBackwardSpeed=1,
wishLeftRightSpeed=0,
wishUpDownSpeed=0,
wishRotationXSpeed=0,
wishRotationYSpeed=0,
wishRotationZSpeed=360,
timeDelay=0.1,
ignoreOrientation=1,
accelerationMultiplier=1,
rotationAccelerationMultiplier=1},

	{forward={0,0,1},
up={0,1,0},
wishForwardBackwardSpeed=1,
wishLeftRightSpeed=0,
wishUpDownSpeed=0,
wishRotationXSpeed=0,
wishRotationYSpeed=0,
wishRotationZSpeed=0,
timeDelay=0.3,
ignoreOrientation=1,
accelerationMultiplier=1,
rotationAccelerationMultiplier=1}}};

flightManeuvers[31]={name="HW1RollCCW",
points={{forward={0,
	0,
	1},
up={0,
	1,
	0},
wishForwardBackwardSpeed=1,
wishLeftRightSpeed=0,
wishUpDownSpeed=0,
wishRotationXSpeed=0,
wishRotationYSpeed=0,
wishRotationZSpeed=-360,
timeDelay=0.5,
ignoreOrientation=1,
accelerationMultiplier=1,
rotationAccelerationMultiplier=1},
	{forward={0,
	0,
	1},
up={0,
	1,
	0},
wishForwardBackwardSpeed=1,
wishLeftRightSpeed=0,
wishUpDownSpeed=0,
wishRotationXSpeed=0,
wishRotationYSpeed=0,
wishRotationZSpeed=0,
timeDelay=0.3,
ignoreOrientation=1,
accelerationMultiplier=1,
rotationAccelerationMultiplier=1}}};

flightManeuvers[32]={name="HW1BarrelRollCW",
points={{forward={0,0,1},
up={0,1,0},
wishForwardBackwardSpeed=1,
wishLeftRightSpeed=2,
wishUpDownSpeed=0,
wishRotationXSpeed=0,
wishRotationYSpeed=0,
wishRotationZSpeed=360,
timeDelay=0.6,
ignoreOrientation=1,
accelerationMultiplier=1,
rotationAccelerationMultiplier=1},

	{forward={0,0,1},
up={0,1,0},
wishForwardBackwardSpeed=1,
wishLeftRightSpeed=0,
wishUpDownSpeed=0,
wishRotationXSpeed=0,
wishRotationYSpeed=0,
wishRotationZSpeed=0,
timeDelay=0.3,
ignoreOrientation=1,
accelerationMultiplier=1,
rotationAccelerationMultiplier=1}}};

flightManeuvers[33]={name="HW1JinkLeft",
points={{forward={0,0,1},
up={0,1,0},
wishForwardBackwardSpeed=0.6,
wishLeftRightSpeed=1.3,
wishUpDownSpeed=0,
wishRotationXSpeed=0,
wishRotationYSpeed=0,
wishRotationZSpeed=360,
timeDelay=0.1,
ignoreOrientation=1,
accelerationMultiplier=1,
rotationAccelerationMultiplier=1},

	{forward={0,0,1},
up={0,1,0},
wishForwardBackwardSpeed=1,
wishLeftRightSpeed=0,
wishUpDownSpeed=0,
wishRotationXSpeed=0,
wishRotationYSpeed=0,
wishRotationZSpeed=0,
timeDelay=0.3,
ignoreOrientation=1,
accelerationMultiplier=1,
rotationAccelerationMultiplier=1}}};

flightManeuvers[34]={name="HW1JinkLeftAndBack",
points={{forward={0,0,1},
up={0,1,0},
wishForwardBackwardSpeed=0.6,
wishLeftRightSpeed=1.5,
wishUpDownSpeed=0,
wishRotationXSpeed=0,
wishRotationYSpeed=0,
wishRotationZSpeed=360,
timeDelay=0.1,
ignoreOrientation=1,
accelerationMultiplier=1.5,
rotationAccelerationMultiplier=1},

	{forward={0,0,1},
up={0,1,0},
wishForwardBackwardSpeed=0.6,
wishLeftRightSpeed=-1.5,
wishUpDownSpeed=0,
wishRotationXSpeed=0,
wishRotationYSpeed=0,
wishRotationZSpeed=0,
timeDelay=0.3,
ignoreOrientation=1,
accelerationMultiplier=1.5,
rotationAccelerationMultiplier=1}}};

flightManeuvers[35]={name="HW1JinkRight",
points={{forward={0,0,1},
up={0,1,0},
wishForwardBackwardSpeed=0.6,
wishLeftRightSpeed=-1.3,
wishUpDownSpeed=0,
wishRotationXSpeed=0,
wishRotationYSpeed=0,
wishRotationZSpeed=-360,
timeDelay=0.1,
ignoreOrientation=1,
accelerationMultiplier=1,
rotationAccelerationMultiplier=1},

	{forward={0,0,1},
up={0,1,0},
wishForwardBackwardSpeed=1,
wishLeftRightSpeed=0,
wishUpDownSpeed=0,
wishRotationXSpeed=0,
wishRotationYSpeed=0,
wishRotationZSpeed=0,
timeDelay=0.3,
ignoreOrientation=1,
accelerationMultiplier=1,
rotationAccelerationMultiplier=1}}};

flightManeuvers[36]={name="HW1ImmelMann_speedy",
points={{forward={0,
	0,
	1},
up={0,
	1,
	0},
wishForwardBackwardSpeed=0.7,
wishLeftRightSpeed=0,
wishUpDownSpeed=0,
wishRotationXSpeed=-360,
wishRotationYSpeed=0,
wishRotationZSpeed=0,
timeDelay=0.1,
ignoreOrientation=1,
accelerationMultiplier=1,
rotationAccelerationMultiplier=1},
	{forward={0,
	0,
	1},
up={0,
	1,
	0},
wishForwardBackwardSpeed=0.7,
wishLeftRightSpeed=0,
wishUpDownSpeed=2,
wishRotationXSpeed=-360,
wishRotationYSpeed=0,
wishRotationZSpeed=-25.396826,
timeDelay=0.2,
ignoreOrientation=1,
accelerationMultiplier=1.5,
rotationAccelerationMultiplier=1},
	{forward={0,
	0,
	-1},
up={0,
	1,
	0},
wishForwardBackwardSpeed=0.7,
wishLeftRightSpeed=0,
wishUpDownSpeed=0,
wishRotationXSpeed=0,
wishRotationYSpeed=0,
wishRotationZSpeed=0,
timeDelay=0.04,
ignoreOrientation=0,
accelerationMultiplier=2,
rotationAccelerationMultiplier=1},
	{forward={0,
	0,
	-1},
up={0,
	1,
	0},
wishForwardBackwardSpeed=0.7,
wishLeftRightSpeed=0,
wishUpDownSpeed=0,
wishRotationXSpeed=0,
wishRotationYSpeed=0,
wishRotationZSpeed=360,
timeDelay=0.04,
ignoreOrientation=1,
accelerationMultiplier=1,
rotationAccelerationMultiplier=1},
	{forward={0,
	0,
	-1},
up={0,
	1,
	0},
wishForwardBackwardSpeed=0.7,
wishLeftRightSpeed=0,
wishUpDownSpeed=0,
wishRotationXSpeed=0,
wishRotationYSpeed=0,
wishRotationZSpeed=0,
timeDelay=0.04,
ignoreOrientation=1,
accelerationMultiplier=1,
rotationAccelerationMultiplier=1}}};

flightManeuvers[37]={name="HW1Split_S_speedy",
points={{forward={0,
	0,
	1},
up={0,
	1,
	0},
wishForwardBackwardSpeed=0.7,
wishLeftRightSpeed=0,
wishUpDownSpeed=0,
wishRotationXSpeed=0,
wishRotationYSpeed=0,
wishRotationZSpeed=370,
timeDelay=0.35,
ignoreOrientation=1,
accelerationMultiplier=1,
rotationAccelerationMultiplier=1},
	{forward={0,
	0,
	1},
up={0,
	1,
	0},
wishForwardBackwardSpeed=0.7,
wishLeftRightSpeed=0,
wishUpDownSpeed=0,
wishRotationXSpeed=0,
wishRotationYSpeed=0,
wishRotationZSpeed=0,
timeDelay=0.1,
ignoreOrientation=1,
accelerationMultiplier=1,
rotationAccelerationMultiplier=1},
	{forward={0,
	0,
	1},
up={0,
	1,
	0},
wishForwardBackwardSpeed=0.7,
wishLeftRightSpeed=0,
wishUpDownSpeed=0,
wishRotationXSpeed=-360,
wishRotationYSpeed=0,
wishRotationZSpeed=0,
timeDelay=0.1,
ignoreOrientation=1,
accelerationMultiplier=1,
rotationAccelerationMultiplier=1},

	{forward={0,
	0,
	1},
up={0,
	1,
	0},
wishForwardBackwardSpeed=0.7,
wishLeftRightSpeed=0,
wishUpDownSpeed=2,
wishRotationXSpeed=-360,
wishRotationYSpeed=0,
wishRotationZSpeed=0,
timeDelay=0.2,
ignoreOrientation=1,
accelerationMultiplier=1.5,
rotationAccelerationMultiplier=1},

	{forward={0,
	0,
	-1},
up={0,
	1,
	0},
wishForwardBackwardSpeed=0.7,
wishLeftRightSpeed=0,
wishUpDownSpeed=0,
wishRotationXSpeed=0,
wishRotationYSpeed=0,
wishRotationZSpeed=0,
timeDelay=0.04,
ignoreOrientation=0,
accelerationMultiplier=2,
rotationAccelerationMultiplier=1}}};

flightManeuvers[38]={name="HW1OneEightyDegRightTurn",
points={{forward={0,0,1},
up={0,1,0},
wishForwardBackwardSpeed=0.7,
wishLeftRightSpeed=0,
wishUpDownSpeed=0,
wishRotationXSpeed=0,
wishRotationYSpeed=0,
wishRotationZSpeed=360,
timeDelay=0.2,
ignoreOrientation=1,
accelerationMultiplier=0.5,
rotationAccelerationMultiplier=1},

	{forward={0,0,1},
up={0,1,0},
wishForwardBackwardSpeed=0.7,
wishLeftRightSpeed=0,
wishUpDownSpeed=0,
wishRotationXSpeed=0,
wishRotationYSpeed=0,
wishRotationZSpeed=0,
timeDelay=0.04,
ignoreOrientation=1,
accelerationMultiplier=0.5,
rotationAccelerationMultiplier=1},

	{forward={0,0,1},
up={0,1,0},
wishForwardBackwardSpeed=0.7,
wishLeftRightSpeed=0,
wishUpDownSpeed=0,
wishRotationXSpeed=-360,
wishRotationYSpeed=0,
wishRotationZSpeed=0,
timeDelay=0.1,
ignoreOrientation=1,
accelerationMultiplier=0.5,
rotationAccelerationMultiplier=1},

	{forward={0,0,1},
up={0,1,0},
wishForwardBackwardSpeed=0.7,
wishLeftRightSpeed=0,
wishUpDownSpeed=2,
wishRotationXSpeed=-360,
wishRotationYSpeed=0,
wishRotationZSpeed=0,
timeDelay=0.2,
ignoreOrientation=1,
accelerationMultiplier=0.5,
rotationAccelerationMultiplier=1},

	{forward={0,0,-1},
up={0,1,0},
wishForwardBackwardSpeed=0.7,
wishLeftRightSpeed=0,
wishUpDownSpeed=0,
wishRotationXSpeed=0,
wishRotationYSpeed=0,
wishRotationZSpeed=0,
timeDelay=0.04,
ignoreOrientation=0,
accelerationMultiplier=0.5,
rotationAccelerationMultiplier=1}}};

flightManeuvers[39]={name="HW1RollCW_slow",
points={{forward={0,
	0,
	1},
up={0,
	1,
	0},
wishForwardBackwardSpeed=1,
wishLeftRightSpeed=0,
wishUpDownSpeed=0,
wishRotationXSpeed=0,
wishRotationYSpeed=0,
wishRotationZSpeed=115,
timeDelay=1.5,
ignoreOrientation=1,
accelerationMultiplier=1,
rotationAccelerationMultiplier=1},
	{forward={0,
	0,
	1},
up={0,
	1,
	0},
wishForwardBackwardSpeed=1,
wishLeftRightSpeed=0,
wishUpDownSpeed=0,
wishRotationXSpeed=0,
wishRotationYSpeed=0,
wishRotationZSpeed=0,
timeDelay=0.3,
ignoreOrientation=1,
accelerationMultiplier=1,
rotationAccelerationMultiplier=1}}};

flightManeuvers[40]={name="HW1Empty",
points={{forward={0,0,1},
up={0,1,0},
wishForwardBackwardSpeed=0.7,
wishLeftRightSpeed=0,
wishUpDownSpeed=0,
wishRotationXSpeed=0,
wishRotationYSpeed=0,
wishRotationZSpeed=0,
timeDelay=0.04,
ignoreOrientation=1,
accelerationMultiplier=1,
rotationAccelerationMultiplier=1}}};

flightManeuvers[41]={name="HW1OneEightyDegLeftTurn",
points={{forward={0,0,1},
up={0,1,0},
wishForwardBackwardSpeed=0.7,
wishLeftRightSpeed=0,
wishUpDownSpeed=0,
wishRotationXSpeed=0,
wishRotationYSpeed=0,
wishRotationZSpeed=-360,
timeDelay=0.2,
ignoreOrientation=1,
accelerationMultiplier=0.5,
rotationAccelerationMultiplier=1},

	{forward={0,0,1},
up={0,1,0},
wishForwardBackwardSpeed=0.7,
wishLeftRightSpeed=0,
wishUpDownSpeed=0,
wishRotationXSpeed=0,
wishRotationYSpeed=0,
wishRotationZSpeed=0,
timeDelay=0.04,
ignoreOrientation=1,
accelerationMultiplier=0.5,
rotationAccelerationMultiplier=1},

	{forward={0,0,1},
up={0,1,0},
wishForwardBackwardSpeed=0.7,
wishLeftRightSpeed=0,
wishUpDownSpeed=0,
wishRotationXSpeed=-360,
wishRotationYSpeed=0,
wishRotationZSpeed=0,
timeDelay=0.1,
ignoreOrientation=1,
accelerationMultiplier=0.5,
rotationAccelerationMultiplier=1},

	{forward={0,0,1},
up={0,1,0},
wishForwardBackwardSpeed=0.7,
wishLeftRightSpeed=0,
wishUpDownSpeed=2,
wishRotationXSpeed=-360,
wishRotationYSpeed=0,
wishRotationZSpeed=0,
timeDelay=0.2,
ignoreOrientation=1,
accelerationMultiplier=0.5,
rotationAccelerationMultiplier=1},

	{forward={0,0,-1},
up={0,1,0},
wishForwardBackwardSpeed=0.7,
wishLeftRightSpeed=0,
wishUpDownSpeed=0,
wishRotationXSpeed=0,
wishRotationYSpeed=0,
wishRotationZSpeed=0,
timeDelay=0.04,
ignoreOrientation=0,
accelerationMultiplier=0.5,
rotationAccelerationMultiplier=1}}};

flightManeuvers[42]={name="HW1RollCCW_slow",
points={{forward={0,
	0,
	1},
up={0,
	1,
	0},
wishForwardBackwardSpeed=1,
wishLeftRightSpeed=0,
wishUpDownSpeed=0,
wishRotationXSpeed=0,
wishRotationYSpeed=0,
wishRotationZSpeed=-115,
timeDelay=1.5,
ignoreOrientation=1,
accelerationMultiplier=1,
rotationAccelerationMultiplier=1},
	{forward={0,
	0,
	1},
up={0,
	1,
	0},
wishForwardBackwardSpeed=1,
wishLeftRightSpeed=0,
wishUpDownSpeed=0,
wishRotationXSpeed=0,
wishRotationYSpeed=0,
wishRotationZSpeed=0,
timeDelay=0.3,
ignoreOrientation=1,
accelerationMultiplier=1,
rotationAccelerationMultiplier=1}}};

flightManeuvers[43]={name="HW1NinetyDegRightTurn",
points={{forward={0,
	0,
	1},
up={0,
	1,
	0},
wishForwardBackwardSpeed=0.7,
wishLeftRightSpeed=0,
wishUpDownSpeed=0,
wishRotationXSpeed=0,
wishRotationYSpeed=0,
wishRotationZSpeed=360,
timeDelay=0.2,
ignoreOrientation=1,
accelerationMultiplier=1,
rotationAccelerationMultiplier=1},
	{forward={0,
	0,
	1},
up={0,
	1,
	0},
wishForwardBackwardSpeed=0.7,
wishLeftRightSpeed=0,
wishUpDownSpeed=0,
wishRotationXSpeed=0,
wishRotationYSpeed=0,
wishRotationZSpeed=0,
timeDelay=0.04,
ignoreOrientation=1,
accelerationMultiplier=1,
rotationAccelerationMultiplier=1},
	{forward={0,
	0,
	1},
up={0,
	1,
	0},
wishForwardBackwardSpeed=0.7,
wishLeftRightSpeed=0,
wishUpDownSpeed=0,
wishRotationXSpeed=-360,
wishRotationYSpeed=0,
wishRotationZSpeed=0,
timeDelay=0.1,
ignoreOrientation=1,
accelerationMultiplier=1,
rotationAccelerationMultiplier=1},
	{forward={0,
	0,
	1},
up={0,
	1,
	0},
wishForwardBackwardSpeed=0.7,
wishLeftRightSpeed=0,
wishUpDownSpeed=2,
wishRotationXSpeed=-360,
wishRotationYSpeed=0,
wishRotationZSpeed=0,
timeDelay=0.1,
ignoreOrientation=1,
accelerationMultiplier=1.5,
rotationAccelerationMultiplier=1},
	{forward={-1,
	0,
	0},
up={0,
	1,
	0},
wishForwardBackwardSpeed=0.7,
wishLeftRightSpeed=0,
wishUpDownSpeed=0,
wishRotationXSpeed=0,
wishRotationYSpeed=0,
wishRotationZSpeed=0,
timeDelay=0.04,
ignoreOrientation=0,
accelerationMultiplier=2,
rotationAccelerationMultiplier=1}}};

flightManeuvers[44]={name="HW1NinetyDegLeftTurn",
points={{forward={0,
	0,
	1},
up={0,
	1,
	0},
wishForwardBackwardSpeed=0.7,
wishLeftRightSpeed=0,
wishUpDownSpeed=0,
wishRotationXSpeed=0,
wishRotationYSpeed=0,
wishRotationZSpeed=-360,
timeDelay=0.2,
ignoreOrientation=1,
accelerationMultiplier=1,
rotationAccelerationMultiplier=1},
	{forward={0,
	0,
	1},
up={0,
	1,
	0},
wishForwardBackwardSpeed=0.7,
wishLeftRightSpeed=0,
wishUpDownSpeed=0,
wishRotationXSpeed=0,
wishRotationYSpeed=0,
wishRotationZSpeed=0,
timeDelay=0.04,
ignoreOrientation=1,
accelerationMultiplier=1,
rotationAccelerationMultiplier=1},
	{forward={0,
	0,
	1},
up={0,
	1,
	0},
wishForwardBackwardSpeed=0.7,
wishLeftRightSpeed=0,
wishUpDownSpeed=0,
wishRotationXSpeed=-360,
wishRotationYSpeed=0,
wishRotationZSpeed=0,
timeDelay=0.1,
ignoreOrientation=1,
accelerationMultiplier=1,
rotationAccelerationMultiplier=1},
	{forward={0,
	0,
	1},
up={0,
	1,
	0},
wishForwardBackwardSpeed=0.7,
wishLeftRightSpeed=0,
wishUpDownSpeed=2,
wishRotationXSpeed=-360,
wishRotationYSpeed=0,
wishRotationZSpeed=0,
timeDelay=0.1,
ignoreOrientation=1,
accelerationMultiplier=1.5,
rotationAccelerationMultiplier=1},
	{forward={1,
	0,
	0},
up={0,
	1,
	0},
wishForwardBackwardSpeed=0.7,
wishLeftRightSpeed=0,
wishUpDownSpeed=0,
wishRotationXSpeed=0,
wishRotationYSpeed=0,
wishRotationZSpeed=0,
timeDelay=0.04,
ignoreOrientation=0,
accelerationMultiplier=2,
rotationAccelerationMultiplier=1}}};

flightManeuvers[45]={name="HW1JinkRightAndBack",
points={{forward={0,
	0,
	1},
up={0,
	1,
	0},
wishForwardBackwardSpeed=0.6,
wishLeftRightSpeed=-1.5,
wishUpDownSpeed=0,
wishRotationXSpeed=0,
wishRotationYSpeed=0,
wishRotationZSpeed=-360,
timeDelay=0.1,
ignoreOrientation=1,
accelerationMultiplier=1.5,
rotationAccelerationMultiplier=1},
	{forward={0,
	0,
	1},
up={0,
	1,
	0},
wishForwardBackwardSpeed=0.6,
wishLeftRightSpeed=1.5,
wishUpDownSpeed=0,
wishRotationXSpeed=0,
wishRotationYSpeed=0,
wishRotationZSpeed=0,
timeDelay=0.3,
ignoreOrientation=1,
accelerationMultiplier=1.5,
rotationAccelerationMultiplier=1}}};

flightManeuvers[46]={name="HW1Slalom",
points={{forward={1,0,1},
up={0,1,0},
wishForwardBackwardSpeed=1,
wishLeftRightSpeed=1,
wishUpDownSpeed=0,
wishRotationXSpeed=0,
wishRotationYSpeed=300,
wishRotationZSpeed=0,
timeDelay=0.5,
ignoreOrientation=1,
accelerationMultiplier=1,
rotationAccelerationMultiplier=1},

	{forward={-1,0,1},
up={0,1,0},
wishForwardBackwardSpeed=1,
wishLeftRightSpeed=-1,
wishUpDownSpeed=0,
wishRotationXSpeed=0,
wishRotationYSpeed=-300,
wishRotationZSpeed=0,
timeDelay=1.0,
ignoreOrientation=1,
accelerationMultiplier=1,
rotationAccelerationMultiplier=1},

{forward={1,0,1},
up={0,1,0},
wishForwardBackwardSpeed=1,
wishLeftRightSpeed=1,
wishUpDownSpeed=0,
wishRotationXSpeed=0,
wishRotationYSpeed=300,
wishRotationZSpeed=0,
timeDelay=1.5,
ignoreOrientation=1,
accelerationMultiplier=1,
rotationAccelerationMultiplier=1},

	{forward={-1,0,1},
up={0,1,0},
wishForwardBackwardSpeed=1,
wishLeftRightSpeed=-1,
wishUpDownSpeed=0,
wishRotationXSpeed=0,
wishRotationYSpeed=-300,
wishRotationZSpeed=0,
timeDelay=2.0,
ignoreOrientation=1,
accelerationMultiplier=1,
rotationAccelerationMultiplier=1}}};

flightManeuvers[47]={name="HW1Cobra",
points={{forward={0,0,1},
up={0,1,0},
wishForwardBackwardSpeed=1,
wishLeftRightSpeed=0,
wishUpDownSpeed=0,
wishRotationXSpeed=0,
wishRotationYSpeed=0,
wishRotationZSpeed=0,
timeDelay=0,
ignoreOrientation=1,
accelerationMultiplier=1,
rotationAccelerationMultiplier=1},

	{forward={0,1,0},
up={0,0,-1},
wishForwardBackwardSpeed=0.5,
wishLeftRightSpeed=0,
wishUpDownSpeed=1,
wishRotationXSpeed=500,
wishRotationYSpeed=0,
wishRotationZSpeed=0,
timeDelay=0.2,
ignoreOrientation=1,
accelerationMultiplier=2,
rotationAccelerationMultiplier=1},

{forward={0,0,1},
up={0,1,0},
wishForwardBackwardSpeed=0.5,
wishLeftRightSpeed=0,
wishUpDownSpeed=-1,
wishRotationXSpeed=500,
wishRotationYSpeed=0,
wishRotationZSpeed=0,
timeDelay=0.5,
ignoreOrientation=1,
accelerationMultiplier=1,
rotationAccelerationMultiplier=1},

{forward={0,0,1},
up={0,1,0},
wishForwardBackwardSpeed=1,
wishLeftRightSpeed=0,
wishUpDownSpeed=0,
wishRotationXSpeed=0,
wishRotationYSpeed=0,
wishRotationZSpeed=0,
timeDelay=0.7,
ignoreOrientation=1,
accelerationMultiplier=1,
rotationAccelerationMultiplier=1}}};

flightManeuvers[48]={name="HW1KadRollCW",
points={{forward={0,
	0,
	1},
up={0,
	1,
	0},
wishForwardBackwardSpeed=0,
wishLeftRightSpeed=0,
wishUpDownSpeed=0,
wishRotationXSpeed=0,
wishRotationYSpeed=0,
wishRotationZSpeed=80,
timeDelay=5,
ignoreOrientation=1,
accelerationMultiplier=1,
rotationAccelerationMultiplier=1}}};

flightManeuvers[49]={name="HW1KadRollCCW",
points={{forward={0,
	0,
	1},
up={0,
	1,
	0},
wishForwardBackwardSpeed=0,
wishLeftRightSpeed=0,
wishUpDownSpeed=0,
wishRotationXSpeed=0,
wishRotationYSpeed=0,
wishRotationZSpeed=-80,
timeDelay=5,
ignoreOrientation=1,
accelerationMultiplier=1,
rotationAccelerationMultiplier=1}}};



