Icon_Speed = "data:ui/newui/research/icons/speed.mres"
Icon_Health = "data:ui/newui/research/icons/health.mres"
Icon_Tech = "data:ui/newui/research/icons/tech.mres"
Icon_Ability = "data:ui/newui/research/icons/ability.mres"
Icon_Build = "data:ui/newui/research/icons/build.mres"
Modifier = 0
Ability = 1
AllShips = 0
Family = 1
Ship = 2

research = 
{
--Fighter Techs
	{
		Name =			"FighterDrive",
		RequiredResearch =	"",
		RequiredSubSystems =	"Research",
		Cost = 			10,
		Time = 			36,
		DisplayedName =		"$11502",
		ShortDisplayedName =	"$11502",
		DisplayPriority =		11,
		Description =		"$11503",
		Icon = 			Icon_Build,
		TargetName =		"Tai_Scout",
	},	
	{
		Name =			"FighterChassis",
		RequiredResearch =	"FighterDrive",
		RequiredSubSystems =	"Research",
		Cost = 			10,
		Time = 			60,
		DisplayedName =		"$11514",
		ShortDisplayedName =	"$11514",
		DisplayPriority =		12,
		Description =		"$11515",
		Icon = 			Icon_Build,
		TargetName =		"Tai_Interceptor",
	},	
	{
		Name =			"DefenderSubSystems",
		RequiredResearch =	"FighterDrive",
		RequiredSubSystems =	"Research",
		Cost = 			10,
		Time = 			120,
		DisplayedName =		"$11528",
		ShortDisplayedName =	"$11528",
		DisplayPriority =		13,
		Description =		"$11529",
		Icon = 			Icon_Build,
		TargetName =		"Tai_Defender",
	},	
	{
		Name =			"PlasmaBombLauncher",
		RequiredResearch =	"FighterChassis",
		RequiredSubSystems =	"Research",
		Cost = 			10,
		Time = 			120,
		DisplayedName =		"$11512",
		ShortDisplayedName =	"$11512",
		DisplayPriority =		14,
		Description =		"$11513",
		Icon = 			Icon_Build,
		TargetName =		"Tai_AttackBomber",
	},		
	{
		Name =			"DefenseFighter",
		RequiredResearch =	"FighterChassis",
		RequiredSubSystems =	"Research",
		Cost = 			10,
		Time = 			160,
		DisplayedName =		"$11508",
		ShortDisplayedName =	"$11508",
		DisplayPriority =		15,
		Description =		"$11509",
		Icon = 			Icon_Build,
		TargetName =		"Tai_DefenseFighter",
	},
--Corvette Techs
	{
		Name =			"CorvetteDrive",
		RequiredResearch =	"",
		RequiredSubSystems =	"Research",
		Cost = 			10,
		Time = 			52,
		DisplayedName =		"$11516",
		ShortDisplayedName =	"$11516",
		DisplayPriority =		21,
		Description =		"$11517",
		Icon = 			Icon_Build,
		TargetName =		"Tai_RepairCorvette",
	},	
	{
		Name =			"CorvetteChassis",
		RequiredResearch =	"CorvetteDrive",
		RequiredSubSystems =	"Research",
		Cost = 			10,
		Time = 			64,
		DisplayedName =		"$11522",
		ShortDisplayedName =	"$11522",
		DisplayPriority =		22,
		Description =		"$11523",
		Icon = 			Icon_Build,
		TargetName =		"Tai_LightCorvette",
	},	
	{
		Name =			"HeavyCorvetteUpgrade",
		RequiredResearch =	"CorvetteChassis",
		RequiredSubSystems =	"Research",
		Cost = 			10,
		Time = 			64,
		DisplayedName =		"$11518",
		ShortDisplayedName =	"$11518",
		DisplayPriority =		23,
		Description =		"$11519",
		Icon = 			Icon_Build,
		TargetName =		"Tai_HeavyCorvette",
	},	
	{
		Name =			"FastTrackingTurrets",
		RequiredResearch =	"CorvetteChassis",
		RequiredSubSystems =	"Research",
		Cost = 			10,
		Time = 			120,
		DisplayedName =		"$11510",
		ShortDisplayedName =	"$11510",
		DisplayPriority =		24,
		Description =		"$11511",
		Icon = 			Icon_Build,
		TargetName =		"Tai_MultiGunCorvette",
	},	
	{
		Name =			"MinelayingTech",
		RequiredResearch =	"CorvetteChassis",
		RequiredSubSystems =	"Research",
		Cost = 			10,
		Time = 			120,
		DisplayedName =		"$11520",
		ShortDisplayedName =	"$11520",
		DisplayPriority =		25,
		Description =		"$11521",
		Icon = 			Icon_Build,
		TargetName =		"Tai_MinelayerCorvette",
	},
--Frigate Techs
	{
		Name =			"CapitalShipDrive",
		RequiredResearch =	"",
		RequiredSubSystems =	"Research",
		Cost = 			10,
		Time = 			80,
		DisplayedName =		"$11526",
		ShortDisplayedName =	"$11526",
		DisplayPriority =		31,
		Description =		"$11527",
		Icon = 			Icon_Build,
		TargetName =		"Tai_SupportFrigate",
	},
	{
		Name =			"CapitalShipChassis",
		RequiredResearch =	"CapitalShipDrive",
		RequiredSubSystems =	"Research",
		Cost = 			10,
		Time = 			68,
		DisplayedName =		"$11540",
		ShortDisplayedName =	"$11540",
		DisplayPriority =		32,
		Description =		"$11541",
		Icon = 			Icon_Build,
		TargetName =		"Tai_AssaultFrigate",
	},
	{
		Name =			"IonCannons",
		RequiredResearch =	"CapitalShipChassis",
		RequiredSubSystems =	"Research",
		Cost = 			10,
		Time = 			180,
		DisplayedName =		"$11534",
		ShortDisplayedName =	"$11534",
		DisplayPriority =		33,
		Description =		"$11535",
		Icon = 			Icon_Build,
		TargetName =		"Tai_IonCannonFrigate",
	},
	{
		Name =			"DefenseField",
		RequiredResearch =	"CapitalShipChassis",
		RequiredSubSystems =	"Research",
		Cost = 			10,
		Time = 			160,
		DisplayedName =		"$11538",
		ShortDisplayedName =	"$11538",
		DisplayPriority =		34,
		Description =		"$11539",
		Icon = 			Icon_Build,
		TargetName =		"Tai_FieldFrigate",
	},
--Super-Capital Ship Techs
	{
		Name =			"SuperCapitalShipDrive",
		RequiredResearch =	"CapitalShipChassis",
		RequiredSubSystems =	"Research",
		Cost = 			10,
		Time = 			120,
		DisplayedName =		"$11542",
		ShortDisplayedName =	"$11542",
		DisplayPriority =		41,
		Description =		"$11543",
		Icon = 			Icon_Build,
		TargetName =		"Tai_Destroyer",
	},
	{
		Name =			"GuidedMissiles",
		RequiredResearch =	"SuperCapitalShipDrive",
		RequiredSubSystems =	"Research",
		Cost = 			10,
		Time = 			120,
		DisplayedName =		"$11546",
		ShortDisplayedName =	"$11546",
		DisplayPriority =		42,
		Description =		"$11547",
		Icon = 			Icon_Build,
		TargetName =		"Tai_MissileDestroyer",
	},
	{
		Name =			"SuperHeavyChassis",
		RequiredResearch =	"SuperCapitalShipDrive",
		RequiredSubSystems =	"Research",
		Cost = 			10,
		Time = 			180,
		DisplayedName =		"$11560",
		ShortDisplayedName =	"$11560",
		DisplayPriority =		43,
		Description =		"$11561",
		Icon = 			Icon_Build,
		TargetName =		"Tai_Carrier",
	},
	{
		Name =			"HeavyGuns",
		RequiredResearch =	"SuperHeavyChassis",
		RequiredSubSystems =	"Research",
		Cost = 			10,
		Time = 			160,
		DisplayedName =		"$11550",
		ShortDisplayedName =	"$11550",
		DisplayPriority =		44,
		Description =		"$11551",
		Icon = 			Icon_Build,
		TargetName =		"Tai_HeavyCruiser",
	},
--Non-Combat Techs
	{
		Name =			"ProximitySensor",
		RequiredResearch =	"",
		RequiredSubSystems =	"Research",
		Cost = 			10,
		Time = 			40,
		DisplayedName =		"$11552",
		ShortDisplayedName =	"$11552",
		DisplayPriority =		51,
		Description =		"$11553",
		Icon = 			Icon_Build,
		TargetName =		"Tai_ProximitySensor",
	},	
	{
		Name =			"SensorArray",
		RequiredResearch =	"ProximitySensor",
		RequiredSubSystems =	"Research",
		Cost = 			10,
		Time = 			160,
		DisplayedName =		"$11554",
		ShortDisplayedName =	"$11554",
		DisplayPriority =		52,
		Description =		"$11555",
		Icon = 			Icon_Build,
		TargetName =		"Tai_SensorArray",
	},	
	{
		Name =			"GravityGenerator",
		RequiredResearch =	"CapitalShipDrive",
		RequiredSubSystems =	"Research",
		Cost = 			10,
		Time = 			180,
		DisplayedName =		"$11556",
		ShortDisplayedName =	"$11556",
		DisplayPriority =		53,
		Description =		"$11557",
		Icon = 			Icon_Build,
		TargetName =		"Tai_GravWellGenerator",
	},	
	{
		Name =			"CloakGenerator",
		RequiredResearch =	"CapitalShipDrive",
		RequiredSubSystems =	"Research",
		Cost = 			10,
		Time = 			180,
		DisplayedName =		"$11558",
		ShortDisplayedName =	"$11558",
		DisplayPriority =		54,
		Description =		"$11559",
		Icon = 			Icon_Build,
		TargetName =		"Tai_CloakGenerator",
	},		
	{
		Name =				"Hyperspace",
		RequiredResearch =		"CapitalShipDrive",
		RequiredSubSystems =		"Research",
		Cost = 				10,
		Time = 				160,
		DisplayedName =			"Hyperspace",
		DisplayPriority =		12,
		Description =			"Enables Hyperspace ",
		UpgradeType =			Ability,
		TargetType =			AllShips,
		TargetName =			"Tai_ResearchShip",
	        UpgradeName =			"HyperSpace",
		Icon = Icon_Hyperspace,
		ShortDisplayedName = "Hyperspace",
	},

	--======================================================================
	-- Frigate Ship Research for HW2 Balance
	--======================================================================
	{
		Name =			"Hw2CapitalShipDrive",
		RequiredResearch =	"CapitalShipDrive",
		RequiredSubSystems =	"Research",
		Cost = 			0,
		Time = 			0,
		DisplayedName =		"$11526",
		ShortDisplayedName =	"$11526",
		DisplayPriority =		31,
		Description =		"$11527",
		Icon = 			Icon_Build,
		TargetName =		"Tai_Hw2SupportFrigate",
	},
	{
		Name =			"Hw2CapitalShipChassis",
		RequiredResearch =	"CapitalShipChassis",
		RequiredSubSystems =	"Research",
		Cost = 			0,
		Time = 			0,
		DisplayedName =		"$11540",
		ShortDisplayedName =	"$11540",
		DisplayPriority =		32,
		Description =		"$11541",
		Icon = 			Icon_Build,
		TargetName =		"Tai_Hw2AssaultFrigate",
	},
	{
		Name =			"Hw2IonCannons",
		RequiredResearch =	"IonCannons",
		RequiredSubSystems =	"Research",
		Cost = 			0,
		Time = 			0,
		DisplayedName =		"$11534",
		ShortDisplayedName =	"$11534",
		DisplayPriority =		33,
		Description =		"$11535",
		Icon = 			Icon_Build,
		TargetName =		"Tai_Hw2IonCannonFrigate",
	},
	--======================================================================
	-- Capital Ship Research for HW2 Balance
	--======================================================================
	{
		Name =			"Hw2SuperCapitalShipDrive",
		RequiredResearch =	"SuperCapitalShipDrive",
		RequiredSubSystems =	"Research",
		Cost = 			0,
		Time = 			0,
		DisplayedName =		"$11542",
		ShortDisplayedName =	"$11542",
		DisplayPriority =		41,
		Description =		"$11543",
		Icon = 			Icon_Build,
		TargetName =		"Tai_Hw2Destroyer",
	},
	{
		Name =			"Hw2GuidedMissiles",
		RequiredResearch =	"GuidedMissiles",
		RequiredSubSystems =	"Research",
		Cost = 			0,
		Time = 			0,
		DisplayedName =		"$11546",
		ShortDisplayedName =	"$11546",
		DisplayPriority =		42,
		Description =		"$11547",
		Icon = 			Icon_Build,
		TargetName =		"Tai_Hw2MissileDestroyer",
	},
	{
		Name =			"Hw2HeavyGuns",
		RequiredResearch =	"HeavyGuns",
		RequiredSubSystems =	"Research",
		Cost = 			0,
		Time = 			0,
		DisplayedName =		"$11550",
		ShortDisplayedName =	"$11550",
		DisplayPriority =		44,
		Description =		"$11551",
		Icon = 			Icon_Build,
		TargetName =		"Tai_Hw2HeavyCruiser",
	},
	
	--======================================================================
	-- Mothership Upgrades
	--======================================================================

	 
	{
		Name =					"MothershipHealthUpgrade1",
		RequiredResearch =		"CapitalShipChassis",
		RequiredSubSystems =	"Research",
		Cost = 					500,
		Time = 					30,
		DisplayedName =			"$7523",
		DisplayPriority =		41,
		Description =			"$7524",
		UpgradeType =			Modifier,
		TargetType =			Ship,
		TargetName =			"Tai_MotherShip",
        UpgradeName =			"MAXHEALTH",
        UpgradeValue =			1.5,
	Icon = Icon_Health,
	ShortDisplayedName = "$7211",
	},

	 
	{
		Name =					"MothershipHealthUpgrade2",
		RequiredResearch =		"MothershipHealthUpgrade1 & SuperHeavyChassis",
		RequiredSubSystems =	"Research",
		Cost = 					750,
		Time = 					40,
		DisplayedName =			"$7525",
		DisplayPriority =		41,
		Description =			"$7526",
		UpgradeType =			Modifier,
		TargetType =			Ship,
		TargetName =			"Tai_MotherShip",
        UpgradeName =			"MAXHEALTH",
        UpgradeValue =			2,
	Icon = Icon_Health,
	ShortDisplayedName = "$7212",
	},

	{
		Name =					"MothershipMAXSPEEDUpgrade1",
		RequiredResearch =		"CapitalShipDrive",
		RequiredSubSystems =	"Research",
		Cost = 					500,
		Time = 					30,
		DisplayedName =			"$7527",
		DisplayPriority =		44,
		Description =			"$7528",
		UpgradeType =			Modifier,
		TargetType =			Ship,
		TargetName =			"Tai_MotherShip",
        UpgradeName =			"MAXSPEED",
        UpgradeValue =			1.2,
	Icon = Icon_Speed,
	ShortDisplayedName = "$7211",
	},

	 
	{
		Name =					"MothershipMAXSPEEDUpgrade2",
		RequiredResearch =		"MothershipMAXSPEEDUpgrade1 & SuperCapitalShipDrive",
		RequiredSubSystems =	"Research",
		Cost = 					750,
		Time = 					40,
		DisplayedName =			"$7529",
		DisplayPriority =		44,
		Description =			"$7530",
		UpgradeType =			Modifier,
		TargetType =			Ship,
		TargetName =			"Tai_MotherShip",
        UpgradeName =			"MAXSPEED",
        UpgradeValue =			1.35,
	Icon = Icon_Speed,
	ShortDisplayedName = "$7212",
	},

	{
		Name =				"MothershipBUILDSPEEDUpgrade1",
		RequiredResearch =		"",
		RequiredSubSystems =		"Research1",
		Cost = 				0,
		Time = 				0,
		DisplayedName =			"$7800",
		DisplayPriority =		45,
		Description =			"$7801",
		UpgradeType =			Modifier,
		TargetType =			Ship,
		TargetName =			"Tai_MotherShip",
	        UpgradeName =			"BUILDSPEED",
        	UpgradeValue =			1.075,
		Icon = Icon_Build,
		ShortDisplayedName = "$7240",
	},
	{
		Name =				"MothershipBUILDSPEEDUpgrade2",
		RequiredResearch =		"",
		RequiredSubSystems =		"Research2",
		Cost = 				0,
		Time = 				0,
		DisplayedName =			"$7800",
		DisplayPriority =		45,
		Description =			"$7801",
		UpgradeType =			Modifier,
		TargetType =			Ship,
		TargetName =			"Tai_MotherShip",
	        UpgradeName =			"BUILDSPEED",
        	UpgradeValue =			1.15,
		Icon = Icon_Build,
		ShortDisplayedName = "$7240",
	},
	{
		Name =				"MothershipBUILDSPEEDUpgrade3",
		RequiredResearch =		"",
		RequiredSubSystems =		"Research3",
		Cost = 				0,
		Time = 				0,
		DisplayedName =			"$7800",
		DisplayPriority =		45,
		Description =			"$7801",
		UpgradeType =			Modifier,
		TargetType =			Ship,
		TargetName =			"Tai_MotherShip",
	        UpgradeName =			"BUILDSPEED",
        	UpgradeValue =			1.225,
		Icon = Icon_Build,
		ShortDisplayedName = "$7240",
	},
	{
		Name =				"MothershipBUILDSPEEDUpgrade4",
		RequiredResearch =		"",
		RequiredSubSystems =		"Research4",
		Cost = 				0,
		Time = 				0,
		DisplayedName =			"$7800",
		DisplayPriority =		45,
		Description =			"$7801",
		UpgradeType =			Modifier,
		TargetType =			Ship,
		TargetName =			"Tai_MotherShip",
	        UpgradeName =			"BUILDSPEED",
        	UpgradeValue =			1.3,
		Icon = Icon_Build,
		ShortDisplayedName = "$7240",
	},
	{
		Name =				"MothershipBUILDSPEEDUpgrade5",
		RequiredResearch =		"",
		RequiredSubSystems =		"Research5",
		Cost = 				0,
		Time = 				0,
		DisplayedName =			"$7800",
		DisplayPriority =		45,
		Description =			"$7801",
		UpgradeType =			Modifier,
		TargetType =			Ship,
		TargetName =			"Tai_MotherShip",
	        UpgradeName =			"BUILDSPEED",
        	UpgradeValue =			1.4,
		Icon = Icon_Build,
		ShortDisplayedName = "$7240",
	},


	--======================================================================
	-- Mothership Upgrades for HW2 Balance
	--======================================================================

	{
		Name =					"MothershipHW2HealthBaseUp",
		RequiredResearch =		"",
		RequiredSubSystems =	"Research",
		Cost = 					0,
		Time = 					0,
		DisplayedName =			"$7523",
		DisplayPriority =		41,
		Description =			"$7524",
		UpgradeType =			Modifier,
		TargetType =			Ship,
		TargetName =			"Tai_MotherShip",
        UpgradeName =			"MAXHEALTH",
        UpgradeValue =			1.5,
	Icon = Icon_Health,
	ShortDisplayedName = "$7211",
	},
	 
	{
		Name =					"MothershipHealthUpgrade1",
		RequiredResearch =		"MothershipHW2HealthBaseUp & CapitalShipChassis",
		RequiredSubSystems =	"Research",
		Cost = 					500,
		Time = 					30,
		DisplayedName =			"$7523",
		DisplayPriority =		41,
		Description =			"$7524",
		UpgradeType =			Modifier,
		TargetType =			Ship,
		TargetName =			"Tai_MotherShip",
        UpgradeName =			"MAXHEALTH",
        UpgradeValue =			2.25,
	Icon = Icon_Health,
	ShortDisplayedName = "$7211",
	},

	 
	{
		Name =					"MothershipHealthUpgrade2",
		RequiredResearch =		"MothershipHealthUpgrade1 & SuperHeavyChassis",
		RequiredSubSystems =	"Research",
		Cost = 					750,
		Time = 					40,
		DisplayedName =			"$7525",
		DisplayPriority =		41,
		Description =			"$7526",
		UpgradeType =			Modifier,
		TargetType =			Ship,
		TargetName =			"Tai_MotherShip",
        UpgradeName =			"MAXHEALTH",
        UpgradeValue =			3,
	Icon = Icon_Health,
	ShortDisplayedName = "$7212",
	},


	--======================================================================
	-- Carrier Upgrades
	--======================================================================

	
	{
		Name =					"CarrierHealthUpgrade1",
		RequiredResearch =		"SuperHeavyChassis",
		RequiredSubSystems =	"Research",
		Cost = 					750,
		Time = 					40,
		DisplayedName =			"$7531",
		DisplayPriority =		61,
		Description =			"$7532",
		UpgradeType =			Modifier,
		TargetType =			Ship,
		TargetName =			"Tai_Carrier",
        UpgradeName =			"MAXHEALTH",
        UpgradeValue =			1.3,
		Icon = Icon_Health,
	ShortDisplayedName = "$7221",
	},

	 
	{
		Name =					"CarrierHealthUpgrade2",
		RequiredResearch =		"CarrierHealthUpgrade1",
		RequiredSubSystems =	"Research",
		Cost = 					1000,
		Time = 					60,
		DisplayedName =			"$7533",
		DisplayPriority =		61,
		Description =			"$7534",
		UpgradeType =			Modifier,
		TargetType =			Ship,
		TargetName =			"Tai_Carrier",
        UpgradeName =			"MAXHEALTH",
        UpgradeValue =			1.6,
		Icon = Icon_Health,
	ShortDisplayedName = "$7222",
	},

	 
	{
		Name =					"CarrierMAXSPEEDUpgrade1",
		RequiredResearch =		"SuperHeavyChassis",
		RequiredSubSystems =	"Research",
		Cost = 					500,
		Time = 					30,
		DisplayedName =			"$7535",
		DisplayPriority =		64,
		Description =			"$7536",
		UpgradeType =			Modifier,
		TargetType =			Ship,
		TargetName =			"Tai_Carrier",
        UpgradeName =			"MAXSPEED",
        UpgradeValue =			1.2,
		Icon = Icon_Speed,
	ShortDisplayedName = "$7221",
	},

	 
	{
		Name =					"CarrierMAXSPEEDUpgrade2",
		RequiredResearch =		"CarrierMAXSPEEDUpgrade1",
		RequiredSubSystems =	"Research",
		Cost = 					1000,
		Time = 					40,
		DisplayedName =			"$7537",
		DisplayPriority =		64,
		Description =			"$7538",
		UpgradeType =			Modifier,
		TargetType =			Ship,
		TargetName =			"Tai_Carrier",
        UpgradeName =			"MAXSPEED",
        UpgradeValue =			1.35,
	Icon = Icon_Speed,
	ShortDisplayedName = "$7222",
	},

	{
		Name =				"CarrierBUILDSPEEDUpgrade1",
		RequiredResearch =		"",
		RequiredSubSystems =		"Research1",
		Cost = 				0,
		Time = 				0,
		DisplayedName =			"$7800",
		DisplayPriority =		45,
		Description =			"$7801",
		UpgradeType =			Modifier,
		TargetType =			Ship,
		TargetName =			"Tai_Carrier",
	        UpgradeName =			"BUILDSPEED",
        	UpgradeValue =			1.075,
		Icon = Icon_Build,
		ShortDisplayedName = "$7240",
	},
	{
		Name =				"CarrierBUILDSPEEDUpgrade2",
		RequiredResearch =		"",
		RequiredSubSystems =		"Research2",
		Cost = 				0,
		Time = 				0,
		DisplayedName =			"$7800",
		DisplayPriority =		45,
		Description =			"$7801",
		UpgradeType =			Modifier,
		TargetType =			Ship,
		TargetName =			"Tai_Carrier",
	        UpgradeName =			"BUILDSPEED",
        	UpgradeValue =			1.15,
		Icon = Icon_Build,
		ShortDisplayedName = "$7240",
	},
	{
		Name =				"CarrierBUILDSPEEDUpgrade3",
		RequiredResearch =		"",
		RequiredSubSystems =		"Research3",
		Cost = 				0,
		Time = 				0,
		DisplayedName =			"$7800",
		DisplayPriority =		45,
		Description =			"$7801",
		UpgradeType =			Modifier,
		TargetType =			Ship,
		TargetName =			"Tai_Carrier",
	        UpgradeName =			"BUILDSPEED",
        	UpgradeValue =			1.225,
		Icon = Icon_Build,
		ShortDisplayedName = "$7240",
	},
	{
		Name =				"CarrierBUILDSPEEDUpgrade4",
		RequiredResearch =		"",
		RequiredSubSystems =		"Research4",
		Cost = 				0,
		Time = 				0,
		DisplayedName =			"$7800",
		DisplayPriority =		45,
		Description =			"$7801",
		UpgradeType =			Modifier,
		TargetType =			Ship,
		TargetName =			"Tai_Carrier",
	        UpgradeName =			"BUILDSPEED",
        	UpgradeValue =			1.3,
		Icon = Icon_Build,
		ShortDisplayedName = "$7240",
	},
	{
		Name =				"CarrierBUILDSPEEDUpgrade5",
		RequiredResearch =		"",
		RequiredSubSystems =		"Research5",
		Cost = 				0,
		Time = 				0,
		DisplayedName =			"$7800",
		DisplayPriority =		45,
		Description =			"$7801",
		UpgradeType =			Modifier,
		TargetType =			Ship,
		TargetName =			"Tai_Carrier",
	        UpgradeName =			"BUILDSPEED",
        	UpgradeValue =			1.4,
		Icon = Icon_Build,
		ShortDisplayedName = "$7240",
	},
	 
	
	--======================================================================
	-- Fighter Upgrades
	--======================================================================

	 
	{
		Name =					"ScoutMAXSPEEDUpgrade1",
		RequiredResearch =		"FighterDrive",
		RequiredSubSystems =	"Research",
		Cost = 					300,
		Time = 					30,
		DisplayedName =			"Scout Engine 1",
		DisplayPriority =		81,
		Description =			"<b>Description:</b> Improves Scout max speed by 25%",
		UpgradeType =			Modifier,
		TargetType =			Ship,
		TargetName =			"Tai_Scout",
        UpgradeName =			"MAXSPEED",
        UpgradeValue =			1.25,
	
	Icon = Icon_Speed,
	ShortDisplayedName = "Lvl 1 Scout"
	},

	{
		Name =					"ScoutMAXSPEEDUpgrade2",
		RequiredResearch =		"ScoutMAXSPEEDUpgrade1",
		RequiredSubSystems =	"Research",
		Cost = 					500,
		Time = 					40,
		DisplayedName =			"Scout Engine 2",
		DisplayPriority =		81,
		Description =			"<b>Description:</b> Improves Scout max speed by 20%",
		UpgradeType =			Modifier,
		TargetType =			Ship,
		TargetName =			"Tai_Scout",
        UpgradeName =			"MAXSPEED",
        UpgradeValue =			1.5,
	
	Icon = Icon_Speed,
	ShortDisplayedName = "Lvl 2 Scout",
	},
		 
	{
		Name =					"InterceptorMAXSPEEDUpgrade1",
		RequiredResearch =		"FighterChassis",
		RequiredSubSystems =	"Research",
		Cost = 					300,
		Time = 					30,
		DisplayedName =			"$7543",
		DisplayPriority =		82,
		Description =			"<b>Description:</b> Improves Interceptor max speed by 25%",
		UpgradeType =			Modifier,
		TargetType =			Ship,
		TargetName =			"Tai_Interceptor",
        UpgradeName =			"MAXSPEED",
        UpgradeValue =			1.25,
	
	Icon = Icon_Speed,
	ShortDisplayedName = "$7231"
	},

	{
		Name =					"InterceptorMAXSPEEDUpgrade2",
		RequiredResearch =		"InterceptorMAXSPEEDUpgrade1",
		RequiredSubSystems =	"Research",
		Cost = 					500,
		Time = 					40,
		DisplayedName =			"$7545",
		DisplayPriority =		82,
		Description =			"<b>Description:</b> Improves Interceptor max speed by 20%",
		UpgradeType =			Modifier,
		TargetType =			Ship,
		TargetName =			"Tai_Interceptor",
        UpgradeName =			"MAXSPEED",
        UpgradeValue =			1.5,
	
	Icon = Icon_Speed,
	ShortDisplayedName = "$7232",
	},

	{
		Name =					"DefenderMAXSPEEDUpgrade1",
		RequiredResearch =		"DefenderSubSystems",
		RequiredSubSystems =	"Research",
		Cost = 					300,
		Time = 					30,
		DisplayedName =			"Defender Engine 1",
		DisplayPriority =		83,
		Description =			"<b>Description:</b> Improves Defender max speed by 25%",
		UpgradeType =			Modifier,
		TargetType =			Ship,
		TargetName =			"Tai_Defender",
        UpgradeName =			"MAXSPEED",
        UpgradeValue =			1.25,
	
	Icon = Icon_Speed,
	ShortDisplayedName = "Lvl 1 Defender"
	},

	{
		Name =					"DefenderMAXSPEEDUpgrade2",
		RequiredResearch =		"DefenderMAXSPEEDUpgrade1",
		RequiredSubSystems =	"Research",
		Cost = 					500,
		Time = 					40,
		DisplayedName =			"Defender Engine 2",
		DisplayPriority =		83,
		Description =			"<b>Description:</b> Improves Defender max speed by 20%",
		UpgradeType =			Modifier,
		TargetType =			Ship,
		TargetName =			"Tai_Defender",
        UpgradeName =			"MAXSPEED",
        UpgradeValue =			1.5,
	
	Icon = Icon_Speed,
	ShortDisplayedName = "Lvl 2 Defender",
	},

	{
		Name =					"AttackBomberMAXSPEEDUpgrade1",
		RequiredResearch =		"PlasmaBombLauncher",
		RequiredSubSystems =	"Research",
		Cost = 					300,
		Time = 					30,
		DisplayedName =			"$7551",
		DisplayPriority =		84,
		Description =			"<b>Description:</b> Improves Bomber max speed by 25%",
		UpgradeType =			Modifier,
		TargetType =			Ship,
		TargetName =			"Tai_AttackBomber",
        UpgradeName =			"MAXSPEED",
        UpgradeValue =			1.25,
	
	Icon = Icon_Speed,
	ShortDisplayedName = "$7234",
	},

	{
		Name =					"AttackBomberMAXSPEEDUpgrade2",
		RequiredResearch =		"AttackBomberMAXSPEEDUpgrade1",
		RequiredSubSystems =	"Research",
		Cost = 					500,
		Time = 					40,
		DisplayedName =			"$7553",
		DisplayPriority =		84,
		Description =			"<b>Description:</b> Improves Bomber max speed by 20%",
		UpgradeType =			Modifier,
		TargetType =			Ship,
		TargetName =			"Tai_AttackBomber",
        UpgradeName =			"MAXSPEED",
        UpgradeValue =			1.5,
	
	Icon = Icon_Speed,
	ShortDisplayedName = "$7235",
	},
	
	{
		Name =					"DefensefMAXSPEEDUpgrade1",
		RequiredResearch =		"DefenseFighter",
		RequiredSubSystems =	"Research",
		Cost = 					300,
		Time = 					30,
		DisplayedName =			"Defense Fighter Engine 1",
		DisplayPriority =		85,
		Description =			"<b>Description:</b> Improves Defense Fighter max speed by 25%",
		UpgradeType =			Modifier,
		TargetType =			Ship,
		TargetName =			"Tai_DefenseFighter",
        UpgradeName =			"MAXSPEED",
        UpgradeValue =			1.25,
	
	Icon = Icon_Speed,
	ShortDisplayedName = "Lvl 1 Defense Fighter"
	},

	{
		Name =					"DefensefMAXSPEEDUpgrade2",
		RequiredResearch =		"DefensefMAXSPEEDUpgrade1",
		RequiredSubSystems =	"Research",
		Cost = 					500,
		Time = 					40,
		DisplayedName =			"Defense Fighter Engine 2",
		DisplayPriority =		85,
		Description =			"<b>Description:</b> Improves Defense Fighter max speed by 20%",
		UpgradeType =			Modifier,
		TargetType =			Ship,
		TargetName =			"Tai_DefenseFighter",
        UpgradeName =			"MAXSPEED",
        UpgradeValue =			1.5,
	
	Icon = Icon_Speed,
	ShortDisplayedName = "Lvl 2 Defense Fighter",
	},
	
	{
		Name =					"Scout5MAXSPEEDUpgrade1",
		RequiredResearch =		"ScoutMAXSPEEDUpgrade1",
		RequiredSubSystems =	"Research",
		Cost = 					0,
		Time = 					0,
		DisplayedName =			"$7543",
		DisplayPriority =		81,
		Description =			"$7544",
		UpgradeType =			Modifier,
		TargetType =			Ship,
		TargetName =			"Tai_Scout5",
        UpgradeName =			"MAXSPEED",
        UpgradeValue =			1.25,
	
	Icon = Icon_Speed,
	ShortDisplayedName = "$7231"
	},

	{
		Name =					"Scout5MAXSPEEDUpgrade2",
		RequiredResearch =		"ScoutMAXSPEEDUpgrade2",
		RequiredSubSystems =	"Research",
		Cost = 					0,
		Time = 					0,
		DisplayedName =			"$7545",
		DisplayPriority =		81,
		Description =			"$7546",
		UpgradeType =			Modifier,
		TargetType =			Ship,
		TargetName =			"Tai_Scout5",
        UpgradeName =			"MAXSPEED",
        UpgradeValue =			1.5,
	
	Icon = Icon_Speed,
	ShortDisplayedName = "$7232",
	},
		 
	{
		Name =					"Interceptor5MAXSPEEDUpgrade1",
		RequiredResearch =		"InterceptorMAXSPEEDUpgrade1",
		RequiredSubSystems =	"Research",
		Cost = 					0,
		Time = 					0,
		DisplayedName =			"$7543",
		DisplayPriority =		82,
		Description =			"$7544",
		UpgradeType =			Modifier,
		TargetType =			Ship,
		TargetName =			"Tai_Interceptor5",
        UpgradeName =			"MAXSPEED",
        UpgradeValue =			1.25,
	
	Icon = Icon_Speed,
	ShortDisplayedName = "$7231"
	},

	{
		Name =					"Interceptor5MAXSPEEDUpgrade2",
		RequiredResearch =		"InterceptorMAXSPEEDUpgrade2",
		RequiredSubSystems =	"Research",
		Cost = 					0,
		Time = 					0,
		DisplayedName =			"$7545",
		DisplayPriority =		82,
		Description =			"$7546",
		UpgradeType =			Modifier,
		TargetType =			Ship,
		TargetName =			"Tai_Interceptor5",
        UpgradeName =			"MAXSPEED",
        UpgradeValue =			1.5,
	
	Icon = Icon_Speed,
	ShortDisplayedName = "$7232",
	},
	
	{
		Name =					"AttackBomber5MAXSPEEDUpgrade1",
		RequiredResearch =		"AttackBomberMAXSPEEDUpgrade1",
		RequiredSubSystems =	"Research",
		Cost = 					0,
		Time = 					0,
		DisplayedName =			"$7551",
		DisplayPriority =		84,
		Description =			"$7552",
		UpgradeType =			Modifier,
		TargetType =			Ship,
		TargetName =			"Tai_AttackBomber5",
        UpgradeName =			"MAXSPEED",
        UpgradeValue =			1.25,
	
	Icon = Icon_Speed,
	ShortDisplayedName = "$7234",
	},

	{
		Name =					"AttackBomber5MAXSPEEDUpgrade2",
		RequiredResearch =		"AttackBomberMAXSPEEDUpgrade2",
		RequiredSubSystems =	"Research",
		Cost = 					0,
		Time = 					0,
		DisplayedName =			"$7553",
		DisplayPriority =		84,
		Description =			"$7554",
		UpgradeType =			Modifier,
		TargetType =			Ship,
		TargetName =			"Tai_AttackBomber5",
        UpgradeName =			"MAXSPEED",
        UpgradeValue =			1.5,
	
	Icon = Icon_Speed,
	ShortDisplayedName = "$7235",
	},
		
	{
		Name =				"AttackBomberImprovedBombs",
		RequiredResearch =		"PlasmaBombLauncher",
		RequiredSubSystems =		"Research",
		Cost = 				1500,
		Time = 				45,
		DisplayedName =			"$7517",
		DisplayPriority =		30,
		Description =			"$7518",
		UpgradeType =			Ability,
		TargetType =			Ship,
		TargetName =			"Tai_AttackBomber",
	        UpgradeName =			"UseSpecialWeaponsInNormalAttack",
		Icon = Icon_Ability,
		ShortDisplayedName = "$7208",
	},
	{
		Name =				"AttackBomberImprovedBombs5",
		RequiredResearch =		"AttackBomberImprovedBombs",
		RequiredSubSystems =		"Research",
		Cost = 				0,
		Time = 				0,
		DisplayedName =			"$7517",
		DisplayPriority =		30,
		Description =			"$7518",
		UpgradeType =			Ability,
		TargetType =			Ship,
		TargetName =			"Tai_AttackBomber5",
	        UpgradeName =			"UseSpecialWeaponsInNormalAttack",
		Icon = Icon_Ability,
		ShortDisplayedName = "$7208",
	},

	--======================================================================
	-- Corvette Upgrades
	--======================================================================

	{
		Name =					"RepairCorvetteMAXSPEEDUpgrade1",
		RequiredResearch =		"CorvetteDrive",
		RequiredSubSystems =	"Research",
		Cost = 					300,
		Time = 					40,
		DisplayedName =			"Repair Corvette Engine 1",
		DisplayPriority =		201,
		Description =			"<b>Description:</b> Improves Repair Corvette max speed by 20%",
		UpgradeType =			Modifier,
		TargetType =			Ship,
		TargetName =			"Tai_RepairCorvette",
        UpgradeName =			"MAXSPEED",
        UpgradeValue =			1.2,
	Icon = Icon_Speed,
	ShortDisplayedName = "Lvl 1 Repair Corvette",
	},

	{
		Name =					"RepairCorvetteMAXSPEEDUpgrade2",
		RequiredResearch =		"RepairCorvetteMAXSPEEDUpgrade1",     -- <list of prerequisite research items>
		RequiredSubSystems =	"Research",
		Cost = 					500,
		Time = 					50,
		DisplayedName =			"Repair Corvette Engine 2",
		DisplayPriority =		201,                                                   -- <display priority (used to sort on screen)>,
		Description =			"<b>Description:</b> Improves Repair Corvette max speed by 12.5%",
		UpgradeType =			Modifier,
		TargetType =			Ship,
		TargetName =			"Tai_RepairCorvette",
        UpgradeName =			"MAXSPEED",
        UpgradeValue =			1.35,
	Icon = Icon_Speed,
	ShortDisplayedName = "Lvl 2 Repair Corvette",
	},

	{
		Name =					"SalvageCorvetteMAXSPEEDUpgrade1",
		RequiredResearch =		"CorvetteDrive",
		RequiredSubSystems =	"Research",
		Cost = 					300,
		Time = 					40,
		DisplayedName =			"Salvage Corvette Engine 1",
		DisplayPriority =		202,
		Description =			"<b>Description:</b> Improves Salvage Corvette max speed by 20%",
		UpgradeType =			Modifier,
		TargetType =			Ship,
		TargetName =			"Tai_SalvageCorvette",
        UpgradeName =			"MAXSPEED",
        UpgradeValue =			1.2,
	Icon = Icon_Speed,
	ShortDisplayedName = "Lvl 1 Salvage Corvette",
	},

	{
		Name =					"SalvageCorvetteMAXSPEEDUpgrade2",
		RequiredResearch =		"SalvageCorvetteMAXSPEEDUpgrade1",     -- <list of prerequisite research items>
		RequiredSubSystems =	"Research",
		Cost = 					500,
		Time = 					50,
		DisplayedName =			"Salvage Corvette Engine 2",
		DisplayPriority =		202,                                                   -- <display priority (used to sort on screen)>,
		Description =			"<b>Description:</b> Improves Salvage Corvette max speed by 12.5%",
		UpgradeType =			Modifier,
		TargetType =			Ship,
		TargetName =			"Tai_SalvageCorvette",
        UpgradeName =			"MAXSPEED",
        UpgradeValue =			1.35,
	Icon = Icon_Speed,
	ShortDisplayedName = "Lvl 2 Salvage Corvette",
	},
	
	{
		Name =					"LightCorvetteMAXSPEEDUpgrade1",
		RequiredResearch =		"CorvetteDrive",
		RequiredSubSystems =	"Research",
		Cost = 					300,
		Time = 					40,
		DisplayedName =			"Light Corvette Engine 1",
		DisplayPriority =		203,
		Description =			"<b>Description:</b> Improves Light Corvette max speed by 20%",
		UpgradeType =			Modifier,
		TargetType =			Ship,
		TargetName =			"Tai_LightCorvette",
        UpgradeName =			"MAXSPEED",
        UpgradeValue =			1.2,
	Icon = Icon_Speed,
	ShortDisplayedName = "Lvl 1 Light Corvette",
	},

	{
		Name =					"LightCorvetteMAXSPEEDUpgrade2",
		RequiredResearch =		"LightCorvetteMAXSPEEDUpgrade1",     -- <list of prerequisite research items>
		RequiredSubSystems =	"Research",
		Cost = 					500,
		Time = 					50,
		DisplayedName =			"Light Corvette Engine 2",
		DisplayPriority =		203,                                                   -- <display priority (used to sort on screen)>,
		Description =			"<b>Description:</b> Improves Light Corvette max speed by 12.5%",
		UpgradeType =			Modifier,
		TargetType =			Ship,
		TargetName =			"Tai_LightCorvette",
        UpgradeName =			"MAXSPEED",
        UpgradeValue =			1.35,
	Icon = Icon_Speed,
	ShortDisplayedName = "Lvl 2 Light Corvette",
	},

	{
		Name =					"HeavyCorvetteMAXSPEEDUpgrade1",
		RequiredResearch =		"HeavyCorvetteUpgrade",                                         -- <list of prerequisite research items>
		RequiredSubSystems =	"Research",
		Cost = 					300,
		Time = 					40,
		DisplayedName =			"Heavy Corvette Engine 1",
		DisplayPriority =		209,                                                    -- <display priority (used to sort on screen)>,
		Description =			"<b>Description:</b> Improves Heavy Corvette max speed by 20%",
		UpgradeType =			Modifier,
		TargetType =			Ship,
		TargetName =			"Tai_HeavyCorvette",
        UpgradeName =			"MAXSPEED",
        UpgradeValue =			1.2,
	
	Icon = Icon_Speed,
	ShortDisplayedName = "Lvl 1 Heavy Corvette",
	},

	{
		Name =					"HeavyCorvetteMAXSPEEDUpgrade2",
		RequiredResearch =		"HeavyCorvetteMAXSPEEDUpgrade1",     -- <list of prerequisite research items>
		RequiredSubSystems =	"Research",
		Cost = 					750,
		Time = 					50,
		DisplayedName =			"Heavy Corvette Engine 2",
		DisplayPriority =		209,                                                   -- <display priority (used to sort on screen)>,
		Description =			"<b>Description:</b> Improves Heavy Corvette max speed by 12.5%",
		UpgradeType =			Modifier,
		TargetType =			Ship,
		TargetName =			"Tai_HeavyCorvette",
        UpgradeName =			"MAXSPEED",
        UpgradeValue =			1.35,
	
	Icon = Icon_Speed,
	ShortDisplayedName = "Lvl 2 Heavy Corvette",
	},
	
	{
		Name =					"MultigunCorvetteMAXSPEEDUpgrade1",
		RequiredResearch =		"FastTrackingTurrets",                                         -- <list of prerequisite research items>
		RequiredSubSystems =	"Research",
		Cost = 					300,
		Time = 					40,
		DisplayedName =			"Multigun Corvette Engine 1",
		DisplayPriority =		210,                                                    -- <display priority (used to sort on screen)>,
		Description =			"<b>Description:</b> Improves Multigun Corvette max speed by 20%",
		UpgradeType =			Modifier,
		TargetType =			Ship,
		TargetName =			"Tai_MultigunCorvette",
        UpgradeName =			"MAXSPEED",
        UpgradeValue =			1.2,
	
	Icon = Icon_Speed,
	ShortDisplayedName = "Lvl 1 Multigun Corvette",
	},

	{
		Name =					"MultigunCorvetteMAXSPEEDUpgrade2",
		RequiredResearch =		"MultigunCorvetteMAXSPEEDUpgrade1",     -- <list of prerequisite research items>
		RequiredSubSystems =	"Research",
		Cost = 					750,
		Time = 					50,
		DisplayedName =			"Multigun Corvette Engine 2",
		DisplayPriority =		210,                                                   -- <display priority (used to sort on screen)>,
		Description =			"<b>Description:</b> Improves Multigun Corvette max speed by 12.5%",
		UpgradeType =			Modifier,
		TargetType =			Ship,
		TargetName =			"Tai_MultigunCorvette",
        UpgradeName =			"MAXSPEED",
        UpgradeValue =			1.35,
	
	Icon = Icon_Speed,
	ShortDisplayedName = "Lvl 2 Multigun Corvette",
	},
	
	{
		Name =					"MinelayerCorvetteMAXSPEEDUpgrade1",
		RequiredResearch =		"MinelayingTech",                                         -- <list of prerequisite research items>
		RequiredSubSystems =	"Research",
		Cost = 					300,
		Time = 					40,
		DisplayedName =			"Minelayer Corvette Engine 1",
		DisplayPriority =		211,                                                    -- <display priority (used to sort on screen)>,
		Description =			"<b>Description:</b> Improves Minelayer Corvette max speed by 20%",
		UpgradeType =			Modifier,
		TargetType =			Ship,
		TargetName =			"Tai_MinelayerCorvette",
        UpgradeName =			"MAXSPEED",
        UpgradeValue =			1.2,
	
	Icon = Icon_Speed,
	ShortDisplayedName = "Lvl 1 Minelayer Corvette",
	},

	{
		Name =					"MinelayerCorvetteMAXSPEEDUpgrade2",
		RequiredResearch =		"MinelayerCorvetteMAXSPEEDUpgrade1",     -- <list of prerequisite research items>
		RequiredSubSystems =	"Research",
		Cost = 					750,
		Time = 					50,
		DisplayedName =			"Minelayer Corvette Engine 2",
		DisplayPriority =		211,                                                   -- <display priority (used to sort on screen)>,
		Description =			"<b>Description:</b> Improves Minelayer Corvette max speed by 12.5%",
		UpgradeType =			Modifier,
		TargetType =			Ship,
		TargetName =			"Tai_MinelayerCorvette",
        UpgradeName =			"MAXSPEED",
        UpgradeValue =			1.35,
	
	Icon = Icon_Speed,
	ShortDisplayedName = "Lvl 2 Minelayer Corvette",
	},
	
	{
		Name =					"LightCorvette3MAXSPEEDUpgrade1",
		RequiredResearch =		"LightCorvetteMAXSPEEDUpgrade1",
		RequiredSubSystems =	"Research",
		Cost = 					0,
		Time = 					0,
		DisplayedName =			"$7559",
		DisplayPriority =		203,
		Description =			"$7560",
		UpgradeType =			Modifier,
		TargetType =			Ship,
		TargetName =			"Tai_LightCorvette3",
        UpgradeName =			"MAXSPEED",
        UpgradeValue =			1.2,
	Icon = Icon_Speed,
	ShortDisplayedName = "$7237",
	},

	{
		Name =					"LightCorvette3MAXSPEEDUpgrade2",
		RequiredResearch =		"LightCorvetteMAXSPEEDUpgrade2",     -- <list of prerequisite research items>
		RequiredSubSystems =	"Research",
		Cost = 					0,
		Time = 					0,
		DisplayedName =			"$7561",
		DisplayPriority =		203,                                                   -- <display priority (used to sort on screen)>,
		Description =			"$7562",
		UpgradeType =			Modifier,
		TargetType =			Ship,
		TargetName =			"Tai_LightCorvette3",
        UpgradeName =			"MAXSPEED",
        UpgradeValue =			1.35,
	Icon = Icon_Speed,
	ShortDisplayedName = "$7238",
	},

	{
		Name =					"HeavyCorvette3MAXSPEEDUpgrade1",
		RequiredResearch =		"HeavyCorvetteMAXSPEEDUpgrade1",                                         -- <list of prerequisite research items>
		RequiredSubSystems =	"Research",
		Cost = 					0,
		Time = 					0,
		DisplayedName =			"$7567",
		DisplayPriority =		209,                                                    -- <display priority (used to sort on screen)>,
		Description =			"$7568",
		UpgradeType =			Modifier,
		TargetType =			Ship,
		TargetName =			"Tai_HeavyCorvette3",
        UpgradeName =			"MAXSPEED",
        UpgradeValue =			1.2,
	
	Icon = Icon_Speed,
	ShortDisplayedName = "$7241",
	},

	{
		Name =					"HeavyCorvette3MAXSPEEDUpgrade2",
		RequiredResearch =		"HeavyCorvetteMAXSPEEDUpgrade2",     -- <list of prerequisite research items>
		RequiredSubSystems =	"Research",
		Cost = 					0,
		Time = 					0,
		DisplayedName =			"$7569",
		DisplayPriority =		209,                                                   -- <display priority (used to sort on screen)>,
		Description =			"$7570",
		UpgradeType =			Modifier,
		TargetType =			Ship,
		TargetName =			"Tai_HeavyCorvette3",
        UpgradeName =			"MAXSPEED",
        UpgradeValue =			1.35,
	
	Icon = Icon_Speed,
	ShortDisplayedName = "$7242",
	},
	
	{
		Name =					"MultigunCorvette3MAXSPEEDUpgrade1",
		RequiredResearch =		"MultigunCorvetteMAXSPEEDUpgrade1",                                         -- <list of prerequisite research items>
		RequiredSubSystems =	"Research",
		Cost = 					0,
		Time = 					0,
		DisplayedName =			"$7567",
		DisplayPriority =		210,                                                    -- <display priority (used to sort on screen)>,
		Description =			"$7568",
		UpgradeType =			Modifier,
		TargetType =			Ship,
		TargetName =			"Tai_MultigunCorvette3",
        UpgradeName =			"MAXSPEED",
        UpgradeValue =			1.2,
	
	Icon = Icon_Speed,
	ShortDisplayedName = "$7241",
	},

	{
		Name =					"MultigunCorvette3MAXSPEEDUpgrade2",
		RequiredResearch =		"MultigunCorvetteMAXSPEEDUpgrade2",     -- <list of prerequisite research items>
		RequiredSubSystems =	"Research",
		Cost = 					0,
		Time = 					0,
		DisplayedName =			"$7569",
		DisplayPriority =		210,                                                   -- <display priority (used to sort on screen)>,
		Description =			"$7570",
		UpgradeType =			Modifier,
		TargetType =			Ship,
		TargetName =			"Tai_MultigunCorvette3",
        UpgradeName =			"MAXSPEED",
        UpgradeValue =			1.35,
	
	Icon = Icon_Speed,
	ShortDisplayedName = "$7242",
	},


	--======================================================================
	-- Frigate Upgrades
	--======================================================================

	{
		Name =					"SupportFrigateHealthUpgrade1",
		RequiredResearch =		"CapitalShipDrive",                                          -- <list of prerequisite research items>
		RequiredSubSystems =	"Research",
		Cost = 					800,
		Time = 					60,
		DisplayedName =			"Support Frigate Armor 1",
		DisplayPriority =		300,                                                    -- <display priority (used to sort on screen)>,
		Description =			"<b>Description:</b> Improves Support Frigate armor by 30%",
		UpgradeType =			Modifier,
		TargetType =			Ship,
		TargetName =			"Tai_SupportFrigate",
        UpgradeName =			"MAXHEALTH",
        UpgradeValue =			1.3,
		Icon = Icon_Health,
		ShortDisplayedName = "Lvl 1 Support Frigate",
	},

	{
		Name =					"SupportFrigateHealthUpgrade2",
		RequiredResearch =		"SupportFrigateHealthUpgrade1 & CapitalShipChassis",     -- <list of prerequisite research items>
		RequiredSubSystems =	"Research",
		Cost = 					1400,
		Time = 					75,
		DisplayedName =			"Support Frigate Armor 2",
		DisplayPriority =		300,                                                    -- <display priority (used to sort on screen)>,
		Description =			"<b>Description:</b> Improves Support Frigate armor by 23%",
		UpgradeType =			Modifier,
		TargetType =			Ship,
		TargetName =			"Tai_SupportFrigate",
        UpgradeName =			"MAXHEALTH",
        UpgradeValue =			1.6,
		Icon = Icon_Health,
		ShortDisplayedName = "Lvl 2 Support Frigate",
	},

	{
		Name =					"SupportFrigateMAXSPEEDUpgrade1",
		RequiredResearch =		"CapitalShipDrive",                                         -- <list of prerequisite research items>
		RequiredSubSystems =	"Research",
		Cost = 					500,
		Time = 					50,
		DisplayedName =			"Support Frigate Engine 1",
		DisplayPriority =		303,                                                    -- <display priority (used to sort on screen)>,
		Description =			"<b>Description:</b> Improves Support Frigate max speed by 20%",
		UpgradeType =			Modifier,
		TargetType =			Ship,
		TargetName =			"Tai_SupportFrigate",
        UpgradeName =			"MAXSPEED",
        UpgradeValue =			1.2,
		Icon = Icon_Speed,
		ShortDisplayedName = "Lvl 1 Support Frigate",
	},

	{
		Name =					"SupportFrigateMAXSPEEDUpgrade2",
		RequiredResearch =		"SupportFrigateMAXSPEEDUpgrade1",     -- <list of prerequisite research items>
		RequiredSubSystems =	"Research",
		Cost = 					750,
		Time = 					70,
		DisplayedName =			"Support Frigate Engine 2",
		DisplayPriority =		303,                                                   -- <display priority (used to sort on screen)>,
		Description =			"<b>Description:</b> Improves Support Frigate max speed by 12.5%",
		UpgradeType =			Modifier,
		TargetType =			Ship,
		TargetName =			"Tai_SupportFrigate",
        UpgradeName =			"MAXSPEED",
        UpgradeValue =			1.35,
		Icon = Icon_Speed,
		ShortDisplayedName = "Lvl 2 Support Frigate",
	},
	
	{
		Name =					"AssaultFrigateHealthUpgrade1",
		RequiredResearch =		"CapitalShipChassis",                                         -- <list of prerequisite research items>
		RequiredSubSystems =	"Research",
		Cost = 					800,
		Time = 					60,
		DisplayedName =			"Assault Frigate Armor 1",
		DisplayPriority =		304,                                                    -- <display priority (used to sort on screen)>,
		Description =			"<b>Description:</b> Improves Assault Frigate armor by 30%",
		UpgradeType =			Modifier,
		TargetType =			Ship,
		TargetName =			"Tai_AssaultFrigate",
        	UpgradeName =			"MAXHEALTH",
       		UpgradeValue =			1.3,
		Icon = Icon_Health,
		ShortDisplayedName = "Lvl 1 Assault Frigate",
	},

	{
		Name =					"AssaultFrigateHealthUpgrade2",
		RequiredResearch =		"AssaultFrigateHealthUpgrade1",     -- <list of prerequisite research items>
		RequiredSubSystems =	"Research",
		Cost = 					1400,
		Time = 					75,
		DisplayedName =			"Assault Frigate Armor 2",
		DisplayPriority =		304,                                                    -- <display priority (used to sort on screen)>,
		Description =			"<b>Description:</b> Improves Assault Frigate armor by 23%",
		UpgradeType =			Modifier,
		TargetType =			Ship,
		TargetName =			"Tai_AssaultFrigate",
        	UpgradeName =			"MAXHEALTH",
        	UpgradeValue =			1.6,
		Icon = Icon_Health,
		ShortDisplayedName = "Lvl 2 Assault Frigate",
	},

	{
		Name =					"AssaultFrigateMAXSPEEDUpgrade1",
		RequiredResearch =		"CapitalShipChassis",                                         -- <list of prerequisite research items>
		RequiredSubSystems =	"Research",
		Cost = 					500,
		Time = 					50,
		DisplayedName =			"Assault Frigate Engine 1",
		DisplayPriority =		305,                                                    -- <display priority (used to sort on screen)>,
		Description =			"<b>Description:</b> Improves Assault Frigate max speed by 20%",
		UpgradeType =			Modifier,
		TargetType =			Ship,
		TargetName =			"Tai_AssaultFrigate",
      		UpgradeName =			"MAXSPEED",
        	UpgradeValue =			1.2,
		Icon = Icon_Speed,
		ShortDisplayedName = "Lvl 1 Assault Frigate",

	},

	{
		Name =					"AssaultFrigateMAXSPEEDUpgrade2",
		RequiredResearch =		"AssaultFrigateMAXSPEEDUpgrade1",     -- <list of prerequisite research items>
		RequiredSubSystems =	"Research",
		Cost = 					750,
		Time = 					70,
		DisplayedName =			"Assault Frigate Engine 2",
		DisplayPriority =		305,                                                   -- <display priority (used to sort on screen)>,
		Description =			"<b>Description:</b> Improves Assault Frigate max speed by 12.5%",
		UpgradeType =			Modifier,
		TargetType =			Ship,
		TargetName =			"Tai_AssaultFrigate",
        UpgradeName =			"MAXSPEED",
        UpgradeValue =			1.35,
		Icon = Icon_Speed,
		ShortDisplayedName = "Lvl 2 Assault Frigate",
	},

	{
		Name =					"IonCannonFrigateHealthUpgrade1",
		RequiredResearch =		"IonCannons",                                         -- <list of prerequisite research items>
		RequiredSubSystems =	"Research",
		Cost = 					800,
		Time = 					60,
		DisplayedName =			"IonCannon Frigate Armor 1",
		DisplayPriority =		306,                                                    -- <display priority (used to sort on screen)>,
		Description =			"<b>Description:</b> Improves IonCannon Frigate armor by 30%",
		UpgradeType =			Modifier,
		TargetType =			Ship,
		TargetName =			"Tai_IonCannonFrigate",
        UpgradeName =			"MAXHEALTH",
        UpgradeValue =			1.3,
		Icon = Icon_Health,
		ShortDisplayedName = "Lvl 1 IonCannon Frigate",
	},

	{
		Name =					"IonCannonFrigateHealthUpgrade2",
		RequiredResearch =		"IonCannonFrigateHealthUpgrade1",     -- <list of prerequisite research items>
		RequiredSubSystems =	"Research",
		Cost = 					1400,
		Time = 					75,
		DisplayedName =			"IonCannon Frigate Armor 2",
		DisplayPriority =		306,                                                    -- <display priority (used to sort on screen)>,
		Description =			"<b>Description:</b> Improves IonCannon Frigate armor by 23%",
		UpgradeType =			Modifier,
		TargetType =			Ship,
		TargetName =			"Tai_IonCannonFrigate",
        UpgradeName =			"MAXHEALTH",
        UpgradeValue =			1.6,
		Icon = Icon_Health,
		ShortDisplayedName = "Lvl 2 IonCannon Frigate",
	},

	{
		Name =					"IonCannonFrigateMAXSPEEDUpgrade1",
		RequiredResearch =		"IonCannons",                                         -- <list of prerequisite research items>
		RequiredSubSystems =	"Research",
		Cost = 					500,
		Time = 					50,
		DisplayedName =			"IonCannon Frigate Engine 1",
		DisplayPriority =		309,                                                    -- <display priority (used to sort on screen)>,
		Description =			"<b>Description:</b> Improves IonCannon Frigate max speed by 20%",
		UpgradeType =			Modifier,
		TargetType =			Ship,
		TargetName =			"Tai_IonCannonFrigate",
        UpgradeName =			"MAXSPEED",
        UpgradeValue =			1.2,
		Icon = Icon_Speed,
		ShortDisplayedName = "Lvl 1 IonCannon Frigate",

	},

	{
		Name =					"IonCannonFrigateMAXSPEEDUpgrade2",
		RequiredResearch =		"IonCannonFrigateMAXSPEEDUpgrade1",     -- <list of prerequisite research items>
		RequiredSubSystems =	"Research",
		Cost = 					750,
		Time = 					70,
		DisplayedName =			"IonCannon Frigate Engine 2",
		DisplayPriority =		309,                                                   -- <display priority (used to sort on screen)>,
		Description =			"<b>Description:</b> Improves IonCannon Frigate max speed by 12.5%",
		UpgradeType =			Modifier,
		TargetType =			Ship,
		TargetName =			"Tai_IonCannonFrigate",
        UpgradeName =			"MAXSPEED",
        UpgradeValue =			1.35,
		Icon = Icon_Speed,
		ShortDisplayedName = "Lvl 2 IonCannon Frigate",

	},

	{
		Name =					"FieldFrigateHealthUpgrade1",
		RequiredResearch =		"DefenseField",                                         -- <list of prerequisite research items>
		RequiredSubSystems =	"Research",
		Cost = 					800,
		Time = 					60,
		DisplayedName =			"Defense Frigate Armor 1",
		DisplayPriority =		312,                                                    -- <display priority (used to sort on screen)>,
		Description =			"<b>Description:</b> Improves Defense Frigate armor by 30%",
		UpgradeType =			Modifier,
		TargetType =			Ship,
		TargetName =			"Tai_FieldFrigate",
        	UpgradeName =			"MAXHEALTH",
       		UpgradeValue =			1.3,
		Icon = Icon_Health,
		ShortDisplayedName = "Lvl 1 Defense Frigate",
	},

	{
		Name =					"FieldFrigateHealthUpgrade2",
		RequiredResearch =		"FieldFrigateHealthUpgrade1",     -- <list of prerequisite research items>
		RequiredSubSystems =	"Research",
		Cost = 					1400,
		Time = 					75,
		DisplayedName =			"Defense Frigate Armor 2",
		DisplayPriority =		312,                                                    -- <display priority (used to sort on screen)>,
		Description =			"<b>Description:</b> Improves Defense Frigate armor by 23%",
		UpgradeType =			Modifier,
		TargetType =			Ship,
		TargetName =			"Tai_FieldFrigate",
        	UpgradeName =			"MAXHEALTH",
        	UpgradeValue =			1.6,
		Icon = Icon_Health,
		ShortDisplayedName = "Lvl 2 Defense Frigate",
	},

	{
		Name =					"FieldFrigateMAXSPEEDUpgrade1",
		RequiredResearch =		"DefenseField",                                         -- <list of prerequisite research items>
		RequiredSubSystems =	"Research",
		Cost = 					500,
		Time = 					50,
		DisplayedName =			"Defense Frigate Engine 1",
		DisplayPriority =		315,                                                    -- <display priority (used to sort on screen)>,
		Description =			"<b>Description:</b> Improves Defense Frigate max speed by 20%",
		UpgradeType =			Modifier,
		TargetType =			Ship,
		TargetName =			"Tai_FieldFrigate",
      		UpgradeName =			"MAXSPEED",
        	UpgradeValue =			1.2,
		Icon = Icon_Speed,
		ShortDisplayedName = "Lvl 1 Defense Frigate",

	},

	{
		Name =					"FieldFrigateMAXSPEEDUpgrade2",
		RequiredResearch =		"FieldFrigateMAXSPEEDUpgrade1",     -- <list of prerequisite research items>
		RequiredSubSystems =	"Research",
		Cost = 					750,
		Time = 					70,
		DisplayedName =			"Defense Frigate Engine 2",
		DisplayPriority =		315,                                                   -- <display priority (used to sort on screen)>,
		Description =			"<b>Description:</b> Improves Defense Frigate max speed by 12.5%",
		UpgradeType =			Modifier,
		TargetType =			Ship,
		TargetName =			"Tai_FieldFrigate",
        UpgradeName =			"MAXSPEED",
        UpgradeValue =			1.35,
		Icon = Icon_Speed,
		ShortDisplayedName = "Lvl 2 Defense Frigate",
	},

	--======================================================================
	-- Frigate Upgrades for HW2 Balance
	--======================================================================

	{
		Name =					"Hw2SupportFrigateHealthUpgrade1",
		RequiredResearch =		"SupportFrigateHealthUpgrade1",                                          -- <list of prerequisite research items>
		RequiredSubSystems =	"Research",
		Cost = 					0,
		Time = 					0,
		DisplayedName =			"$7571",
		DisplayPriority =		300,                                                    -- <display priority (used to sort on screen)>,
		Description =			"$7572",
		UpgradeType =			Modifier,
		TargetType =			Ship,
		TargetName =			"Tai_Hw2SupportFrigate",
        UpgradeName =			"MAXHEALTH",
        UpgradeValue =			1.3,
		Icon = Icon_Health,
	ShortDisplayedName = "$7244",
	},

	{
		Name =					"Hw2SupportFrigateHealthUpgrade2",
		RequiredResearch =		"SupportFrigateHealthUpgrade2",     -- <list of prerequisite research items>
		RequiredSubSystems =	"Research",
		Cost = 					0,
		Time = 					0,
		DisplayedName =			"$7573",
		DisplayPriority =		300,                                                    -- <display priority (used to sort on screen)>,
		Description =			"$7574",
		UpgradeType =			Modifier,
		TargetType =			Ship,
		TargetName =			"Tai_Hw2SupportFrigate",
        UpgradeName =			"MAXHEALTH",
        UpgradeValue =			1.6,
		Icon = Icon_Health,
	ShortDisplayedName = "$7245",
	},

	{
		Name =					"Hw2SupportFrigateMAXSPEEDUpgrade1",
		RequiredResearch =		"SupportFrigateMAXSPEEDUpgrade1",                                         -- <list of prerequisite research items>
		RequiredSubSystems =	"Research",
		Cost = 					0,
		Time = 					0,
		DisplayedName =			"$7575",
		DisplayPriority =		303,                                                    -- <display priority (used to sort on screen)>,
		Description =			"$7576",
		UpgradeType =			Modifier,
		TargetType =			Ship,
		TargetName =			"Tai_Hw2SupportFrigate",
        UpgradeName =			"MAXSPEED",
        UpgradeValue =			1.2,
		Icon = Icon_Speed,
	ShortDisplayedName = "$7244",
	},

	{
		Name =					"Hw2SupportFrigateMAXSPEEDUpgrade2",
		RequiredResearch =		"SupportFrigateMAXSPEEDUpgrade2",     -- <list of prerequisite research items>
		RequiredSubSystems =	"Research",
		Cost = 					0,
		Time = 					0,
		DisplayedName =			"$7577",
		DisplayPriority =		303,                                                   -- <display priority (used to sort on screen)>,
		Description =			"$7578",
		UpgradeType =			Modifier,
		TargetType =			Ship,
		TargetName =			"Tai_Hw2SupportFrigate",
        UpgradeName =			"MAXSPEED",
        UpgradeValue =			1.35,
		Icon = Icon_Speed,
	ShortDisplayedName = "$7245",
	},
	
	{
		Name =					"Hw2AssaultFrigateHealthUpgrade1",
		RequiredResearch =		"AssaultFrigateHealthUpgrade1",                                         -- <list of prerequisite research items>
		RequiredSubSystems =	"Research",
		Cost = 					0,
		Time = 					0,
		DisplayedName =			"$7587",
		DisplayPriority =		304,                                                    -- <display priority (used to sort on screen)>,
		Description =			"$7588",
		UpgradeType =			Modifier,
		TargetType =			Ship,
		TargetName =			"Tai_Hw2AssaultFrigate",
        	UpgradeName =			"MAXHEALTH",
       		UpgradeValue =			1.3,
		Icon = Icon_Health,
		ShortDisplayedName = "$7251",
	},

	{
		Name =					"Hw2AssaultFrigateHealthUpgrade2",
		RequiredResearch =		"AssaultFrigateHealthUpgrade2",     -- <list of prerequisite research items>
		RequiredSubSystems =	"Research",
		Cost = 					0,
		Time = 					0,
		DisplayedName =			"$7589",
		DisplayPriority =		304,                                                    -- <display priority (used to sort on screen)>,
		Description =			"$7590",
		UpgradeType =			Modifier,
		TargetType =			Ship,
		TargetName =			"Tai_Hw2AssaultFrigate",
        	UpgradeName =			"MAXHEALTH",
        	UpgradeValue =			1.6,
		Icon = Icon_Health,
		ShortDisplayedName = "$7252",
	},

	{
		Name =					"Hw2AssaultFrigateMAXSPEEDUpgrade1",
		RequiredResearch =		"AssaultFrigateMAXSPEEDUpgrade1",                                         -- <list of prerequisite research items>
		RequiredSubSystems =	"Research",
		Cost = 					0,
		Time = 					0,
		DisplayedName =			"$7591",
		DisplayPriority =		305,                                                    -- <display priority (used to sort on screen)>,
		Description =			"$7592",
		UpgradeType =			Modifier,
		TargetType =			Ship,
		TargetName =			"Tai_Hw2AssaultFrigate",
      		UpgradeName =			"MAXSPEED",
        	UpgradeValue =			1.2,
		Icon = Icon_Speed,
		ShortDisplayedName = "$7251",

	},

	{
		Name =					"Hw2AssaultFrigateMAXSPEEDUpgrade2",
		RequiredResearch =		"AssaultFrigateMAXSPEEDUpgrade2",     -- <list of prerequisite research items>
		RequiredSubSystems =	"Research",
		Cost = 					0,
		Time = 					0,
		DisplayedName =			"$7593",
		DisplayPriority =		305,                                                   -- <display priority (used to sort on screen)>,
		Description =			"$7594",
		UpgradeType =			Modifier,
		TargetType =			Ship,
		TargetName =			"Tai_Hw2AssaultFrigate",
        UpgradeName =			"MAXSPEED",
        UpgradeValue =			1.35,
		Icon = Icon_Speed,
	ShortDisplayedName = "$7252",
	},

	{
		Name =					"Hw2IonCannonFrigateHealthUpgrade1",
		RequiredResearch =		"IonCannonFrigateHealthUpgrade1",                                         -- <list of prerequisite research items>
		RequiredSubSystems =	"Research",
		Cost = 					0,
		Time = 					0,
		DisplayedName =			"$7579",
		DisplayPriority =		306,                                                    -- <display priority (used to sort on screen)>,
		Description =			"$7580",
		UpgradeType =			Modifier,
		TargetType =			Ship,
		TargetName =			"Tai_Hw2IonCannonFrigate",
        UpgradeName =			"MAXHEALTH",
        UpgradeValue =			1.3,
		Icon = Icon_Health,
	ShortDisplayedName = "$7247",
	},

	{
		Name =					"Hw2IonCannonFrigateHealthUpgrade2",
		RequiredResearch =		"IonCannonFrigateHealthUpgrade2",     -- <list of prerequisite research items>
		RequiredSubSystems =	"Research",
		Cost = 					0,
		Time = 					0,
		DisplayedName =			"$7581",
		DisplayPriority =		306,                                                    -- <display priority (used to sort on screen)>,
		Description =			"$7582",
		UpgradeType =			Modifier,
		TargetType =			Ship,
		TargetName =			"Tai_Hw2IonCannonFrigate",
        UpgradeName =			"MAXHEALTH",
        UpgradeValue =			1.6,
		Icon = Icon_Health,
	ShortDisplayedName = "$7248",
	},

	{
		Name =					"Hw2IonCannonFrigateMAXSPEEDUpgrade1",
		RequiredResearch =		"IonCannonFrigateMAXSPEEDUpgrade1",                                         -- <list of prerequisite research items>
		RequiredSubSystems =	"Research",
		Cost = 					0,
		Time = 					0,
		DisplayedName =			"$7583",
		DisplayPriority =		309,                                                    -- <display priority (used to sort on screen)>,
		Description =			"$7584",
		UpgradeType =			Modifier,
		TargetType =			Ship,
		TargetName =			"Tai_Hw2IonCannonFrigate",
        UpgradeName =			"MAXSPEED",
        UpgradeValue =			1.2,
		Icon = Icon_Speed,
	ShortDisplayedName = "$7247",

	},

	{
		Name =					"Hw2IonCannonFrigateMAXSPEEDUpgrade2",
		RequiredResearch =		"IonCannonFrigateMAXSPEEDUpgrade2",     -- <list of prerequisite research items>
		RequiredSubSystems =	"Research",
		Cost = 					0,
		Time = 					0,
		DisplayedName =			"$7585",
		DisplayPriority =		309,                                                   -- <display priority (used to sort on screen)>,
		Description =			"$7586",
		UpgradeType =			Modifier,
		TargetType =			Ship,
		TargetName =			"Tai_Hw2IonCannonFrigate",
        UpgradeName =			"MAXSPEED",
        UpgradeValue =			1.35,
		Icon = Icon_Speed,
	ShortDisplayedName = "$7248",

	},

	{
		Name =					"Hw2FieldFrigateHealthUpgrade1",
		RequiredResearch =		"FieldFrigateHealthUpgrade1",                                         -- <list of prerequisite research items>
		RequiredSubSystems =	"Research",
		Cost = 					0,
		Time = 					0,
		DisplayedName =			"$7587",
		DisplayPriority =		312,                                                    -- <display priority (used to sort on screen)>,
		Description =			"$7588",
		UpgradeType =			Modifier,
		TargetType =			Ship,
		TargetName =			"Tai_Hw2FieldFrigate",
        	UpgradeName =			"MAXHEALTH",
       		UpgradeValue =			1.3,
		Icon = Icon_Health,
		ShortDisplayedName = "$7251",
	},

	{
		Name =					"Hw2FieldFrigateHealthUpgrade2",
		RequiredResearch =		"FieldFrigateHealthUpgrade2",     -- <list of prerequisite research items>
		RequiredSubSystems =	"Research",
		Cost = 					0,
		Time = 					0,
		DisplayedName =			"$7589",
		DisplayPriority =		312,                                                    -- <display priority (used to sort on screen)>,
		Description =			"$7590",
		UpgradeType =			Modifier,
		TargetType =			Ship,
		TargetName =			"Tai_Hw2FieldFrigate",
        	UpgradeName =			"MAXHEALTH",
        	UpgradeValue =			1.6,
		Icon = Icon_Health,
		ShortDisplayedName = "$7252",
	},

	{
		Name =					"Hw2FieldFrigateMAXSPEEDUpgrade1",
		RequiredResearch =		"FieldFrigateMAXSPEEDUpgrade1",                                         -- <list of prerequisite research items>
		RequiredSubSystems =	"Research",
		Cost = 					0,
		Time = 					0,
		DisplayedName =			"$7591",
		DisplayPriority =		315,                                                    -- <display priority (used to sort on screen)>,
		Description =			"$7592",
		UpgradeType =			Modifier,
		TargetType =			Ship,
		TargetName =			"Tai_Hw2FieldFrigate",
      		UpgradeName =			"MAXSPEED",
        	UpgradeValue =			1.2,
		Icon = Icon_Speed,
		ShortDisplayedName = "$7251",

	},

	{
		Name =					"Hw2FieldFrigateMAXSPEEDUpgrade2",
		RequiredResearch =		"FieldFrigateMAXSPEEDUpgrade2",     -- <list of prerequisite research items>
		RequiredSubSystems =	"Research",
		Cost = 					0,
		Time = 					0,
		DisplayedName =			"$7593",
		DisplayPriority =		315,                                                   -- <display priority (used to sort on screen)>,
		Description =			"$7594",
		UpgradeType =			Modifier,
		TargetType =			Ship,
		TargetName =			"Tai_Hw2FieldFrigate",
        UpgradeName =			"MAXSPEED",
        UpgradeValue =			1.35,
		Icon = Icon_Speed,
	ShortDisplayedName = "$7252",
	},

	--======================================================================
	-- Capital Ship Upgrades
	--======================================================================

	{
		Name =					"HeavycruiserHealthUpgrade1",
		RequiredResearch =		"HeavyGuns & IonCannons",                             -- <list of prerequisite research items>
		RequiredSubSystems =	"Research",
		Cost = 					2000,
		Time = 					60,
		DisplayedName =			"Heavy Cruiser Armor 1",
		DisplayPriority =		401,                                                    -- <display priority (used to sort on screen)>,
		Description =			"<b>Description:</b> Improves Heavy Cruiser armor by 30%",
		UpgradeType =			Modifier,
		TargetType =			Ship,
		TargetName =			"Tai_Heavycruiser",
		UpgradeName =			"MAXHEALTH",
		UpgradeValue =			1.3,
		Icon = Icon_Health,
		ShortDisplayedName = 		"Lvl 1 Heavy Cruiser",
	},

	{
		Name =					"HeavycruiserHealthUpgrade2",
		RequiredResearch =		"HeavycruiserHealthUpgrade1",                 -- <list of prerequisite research items>
		RequiredSubSystems =	"Research",
		Cost = 					3000,
		Time = 					75,
		DisplayedName =			"Heavy Cruiser Armor 1",
		DisplayPriority =		401,                                                    -- <display priority (used to sort on screen)>,
		Description =			"<b>Description:</b> Improves Heavy Cruiser armor by 23%",
		UpgradeType =			Modifier,
		TargetType =			Ship,
		TargetName =			"Tai_Heavycruiser",
		UpgradeName =			"MAXHEALTH",
		UpgradeValue =			1.6,
		Icon = Icon_Health,
		ShortDisplayedName = 		"Lvl 2 Heavy Cruiser",
	},

	{
		Name =					"HeavycruiserMAXSPEEDUpgrade1",
		RequiredResearch =		"HeavyGuns & IonCannons",                             -- <list of prerequisite research items>
		RequiredSubSystems =	"Research",
		Cost = 					1000,
		Time = 					30,
		DisplayedName =			"Heavy Cruiser Engine 1",
		DisplayPriority =		404,                                                   -- <display priority (used to sort on screen)>,
		Description =			"<b>Description:</b> Improves Heavy Cruiser max speed by 20%",
		UpgradeType =			Modifier,
		TargetType =			Ship,
		TargetName =			"Tai_Heavycruiser",
		UpgradeName =			"MAXSPEED",
		UpgradeValue =			1.2,
		Icon = Icon_Speed,
		ShortDisplayedName = 		"Lvl 1 Heavy Cruiser",

	},

	{
		Name =					"HeavycruiserMAXSPEEDUpgrade2",
		RequiredResearch =		"HeavycruiserMAXSPEEDUpgrade1",                  -- <list of prerequisite research items>
		RequiredSubSystems =	"Research",
		Cost = 					1500,
		Time = 					40,
		DisplayedName =			"Heavy Cruiser Engine 1",
		DisplayPriority =		404,                                                   -- <display priority (used to sort on screen)>,
		Description =			"<b>Description:</b> Improves Heavy Cruiser max speed by 12.5%",
		UpgradeType =			Modifier,
		TargetType =			Ship,
		TargetName =			"Tai_Heavycruiser",
		UpgradeName =			"MAXSPEED",
		UpgradeValue =			1.35,
		Icon = Icon_Speed,
		ShortDisplayedName = 		"Lvl 2 Heavy Cruiser",

	},


{
		Name =				"DestroyerHealthUpgrade1",
		RequiredResearch =		"SuperCapitalShipDrive & IonCannons",                             -- <list of prerequisite research items>
		RequiredSubSystems =	"Research",
		Cost = 					1000,
		Time = 					60,
		DisplayedName =			"$7639",
		DisplayPriority =			405,                                                    -- <display priority (used to sort on screen)>,
		Description =			"<b>Description:</b> Improves Destroyer armor by 30%",
		UpgradeType =			Modifier,
		TargetType =			Ship,
		TargetName =			"Tai_Destroyer",
		UpgradeName =			"MAXHEALTH",
		UpgradeValue =			1.3,
		ShortDisplayedName = 		"$7274",
		Icon = 				Icon_Health,	
	},

	{
		Name =				"DestroyerHealthUpgrade2",
		RequiredResearch =		"DestroyerHealthUpgrade1",                 -- <list of prerequisite research items>
		RequiredSubSystems =	"Research",
		Cost = 					1500,
		Time = 					75,
		DisplayedName =			"$7641",
		DisplayPriority =			405,                                                    -- <display priority (used to sort on screen)>,
		Description =			"<b>Description:</b> Improves Destroyer armor by 23%",
		UpgradeType =			Modifier,
		TargetType =			Ship,
		TargetName =			"Tai_Destroyer",
		UpgradeName =			"MAXHEALTH",
		UpgradeValue =			1.6,
		Icon = 				Icon_Health,
		ShortDisplayedName = 		"$7275",
	},

	{
		Name =					"DestroyerMAXSPEEDUpgrade1",
		RequiredResearch =		"SuperCapitalShipDrive & IonCannons",                             -- <list of prerequisite research items>
		RequiredSubSystems =	"Research",
		Cost = 					1000,
		Time = 					30,
		DisplayedName =			"$7643",
		DisplayPriority =		406,                                                   -- <display priority (used to sort on screen)>,
		Description =			"<b>Description:</b> Improves Destroyer max speed by 20%",
		UpgradeType =			Modifier,
		TargetType =			Ship,
		TargetName =			"Tai_Destroyer",
		UpgradeName =			"MAXSPEED",
		UpgradeValue =			1.2,
		Icon = Icon_Speed,
		ShortDisplayedName = 		"$7274",

	},

	{
		Name =					"DestroyerMAXSPEEDUpgrade2",
		RequiredResearch =		"DestroyerMAXSPEEDUpgrade1",                  -- <list of prerequisite research items>
		RequiredSubSystems =	"Research",
		Cost = 					1500,
		Time = 					40,
		DisplayedName =			"$7645",
		DisplayPriority =		406,                                                   -- <display priority (used to sort on screen)>,
		Description =			"<b>Description:</b> Improves Destroyer max speed by 12.5%",
		UpgradeType =			Modifier,
		TargetType =			Ship,
		TargetName =			"Tai_Destroyer",
		UpgradeName =			"MAXSPEED",
		UpgradeValue =			1.35,
		Icon = Icon_Speed,
		ShortDisplayedName = 		"$7275",

	},

{
		Name =				"MissileDestroyerHealthUpgrade1",
		RequiredResearch =		"GuidedMissiles",                             -- <list of prerequisite research items>
		RequiredSubSystems =	"Research",
		Cost = 					1000,
		Time = 					60,
		DisplayedName =			"Missile Destroyer Armor 1",
		DisplayPriority =			407,                                                    -- <display priority (used to sort on screen)>,
		Description =			"<b>Description:</b> Improves Missile Destroyer armor by 30%",
		UpgradeType =			Modifier,
		TargetType =			Ship,
		TargetName =			"Tai_MissileDestroyer",
		UpgradeName =			"MAXHEALTH",
		UpgradeValue =			1.3,
		Icon = 				Icon_Health,
		ShortDisplayedName = 		"Lvl 1 Missile Destroyer",
	},

	{
		Name =				"MissileDestroyerHealthUpgrade2",
		RequiredResearch =		"MissileDestroyerHealthUpgrade1",                 -- <list of prerequisite research items>
		RequiredSubSystems =	"Research",
		Cost = 					1500,
		Time = 					75,
		DisplayedName =			"Missile Destroyer Armor 1",
		DisplayPriority =			407,                                                    -- <display priority (used to sort on screen)>,
		Description =			"<b>Description:</b> Improves Missile Destroyer armor by 23%",
		UpgradeType =			Modifier,
		TargetType =			Ship,
		TargetName =			"Tai_MissileDestroyer",
		UpgradeName =			"MAXHEALTH",
		UpgradeValue =			1.6,
		Icon = 				Icon_Health,
		ShortDisplayedName = 		"Lvl 2 Missile Destroyer",
	},

	{
		Name =					"MissileDestroyerMAXSPEEDUpgrade1",
		RequiredResearch =		"GuidedMissiles",                             -- <list of prerequisite research items>
		RequiredSubSystems =	"Research",
		Cost = 					1000,
		Time = 					30,
		DisplayedName =			"Missile Destroyer Engine 1",
		DisplayPriority =		408,                                                   -- <display priority (used to sort on screen)>,
		Description =			"<b>Description:</b> Improves Missile Destroyer max speed by 20%",
		UpgradeType =			Modifier,
		TargetType =			Ship,
		TargetName =			"Tai_MissileDestroyer",
		UpgradeName =			"MAXSPEED",
		UpgradeValue =			1.2,
		Icon = Icon_Speed,
		ShortDisplayedName = 		"Lvl 1 Missile Destroyer",

	},

	{
		Name =					"MissileDestroyerMAXSPEEDUpgrade2",
		RequiredResearch =		"MissileDestroyerMAXSPEEDUpgrade1",                  -- <list of prerequisite research items>
		RequiredSubSystems =	"Research",
		Cost = 					1500,
		Time = 					40,
		DisplayedName =			"Missile Destroyer Engine 1",
		DisplayPriority =		409,                                                   -- <display priority (used to sort on screen)>,
		Description =			"<b>Description:</b> Improves Missile Destroyer max speed by 12.5%",
		UpgradeType =			Modifier,
		TargetType =			Ship,
		TargetName =			"Tai_MissileDestroyer",
		UpgradeName =			"MAXSPEED",
		UpgradeValue =			1.35,
		Icon = Icon_Speed,
		ShortDisplayedName = 		"Lvl 2 Missile Destroyer",

	},

	--======================================================================
	-- Capital Ship Upgrades for HW2 Balance
	--======================================================================

	{
		Name =					"HeavycruiserHW2HealthUpgrade1",
		RequiredResearch =		"HeavycruiserHealthUpgrade1",                             -- <list of prerequisite research items>
		RequiredSubSystems =	"Research",
		Cost = 					0,
		Time = 					0,
		DisplayedName =			"$7595",
		DisplayPriority =		401,                                                    -- <display priority (used to sort on screen)>,
		Description =			"$7596",
		UpgradeType =			Modifier,
		TargetType =			Ship,
		TargetName =			"Tai_Hw2Heavycruiser",
		UpgradeName =			"MAXHEALTH",
		UpgradeValue =			1.3,
		Icon = Icon_Health,
		ShortDisplayedName = "$7254",
	},

	{
		Name =					"HeavycruiserHW2HealthUpgrade2",
		RequiredResearch =		"HeavycruiserHealthUpgrade2",                 -- <list of prerequisite research items>
		RequiredSubSystems =	"Research",
		Cost = 					0,
		Time = 					0,
		DisplayedName =			"$7597",
		DisplayPriority =		401,                                                    -- <display priority (used to sort on screen)>,
		Description =			"$7598",
		UpgradeType =			Modifier,
		TargetType =			Ship,
		TargetName =			"Tai_Hw2Heavycruiser",
		UpgradeName =			"MAXHEALTH",
		UpgradeValue =			1.6,
		Icon = Icon_Health,
		ShortDisplayedName = "$7255",
	},
	
	{
		Name =					"Hw2HeavycruiserMAXSPEEDUpgrade1",
		RequiredResearch =		"HeavycruiserMAXSPEEDUpgrade1",                             -- <list of prerequisite research items>
		RequiredSubSystems =	"Research",
		Cost = 					0,
		Time = 					0,
		DisplayedName =			"Heavy Cruiser Engine 1",
		DisplayPriority =		404,                                                   -- <display priority (used to sort on screen)>,
		Description =			"<b>Description:</b> Improves Heavy Cruiser max speed by 20%",
		UpgradeType =			Modifier,
		TargetType =			Ship,
		TargetName =			"Tai_Hw2Heavycruiser",
		UpgradeName =			"MAXSPEED",
		UpgradeValue =			1.2,
		Icon = Icon_Speed,
		ShortDisplayedName = 		"Lvl 1 Heavy Cruiser",

	},

	{
		Name =					"Hw2HeavycruiserMAXSPEEDUpgrade2",
		RequiredResearch =		"HeavycruiserMAXSPEEDUpgrade2",                  -- <list of prerequisite research items>
		RequiredSubSystems =	"Research",
		Cost = 					0,
		Time = 					0,
		DisplayedName =			"Heavy Cruiser Engine 1",
		DisplayPriority =		404,                                                   -- <display priority (used to sort on screen)>,
		Description =			"<b>Description:</b> Improves Heavy Cruiser max speed by 12.5%",
		UpgradeType =			Modifier,
		TargetType =			Ship,
		TargetName =			"Tai_Hw2Heavycruiser",
		UpgradeName =			"MAXSPEED",
		UpgradeValue =			1.35,
		Icon = Icon_Speed,
		ShortDisplayedName = 		"Lvl 2 Heavy Cruiser",

	},


	{
		Name =				"DestroyerHW2HealthUpgrade1",
		RequiredResearch =		"DestroyerHealthUpgrade1",                             -- <list of prerequisite research items>
		RequiredSubSystems =	"Research",
		Cost = 					0,
		Time = 					0,
		DisplayedName =			"$7639",
		DisplayPriority =			405,                                                    -- <display priority (used to sort on screen)>,
		Description =			"$7640",
		UpgradeType =			Modifier,
		TargetType =			Ship,
		TargetName =			"Tai_Hw2Destroyer",
		UpgradeName =			"MAXHEALTH",
		UpgradeValue =			1.3,
		ShortDisplayedName = 		"$7274",
		Icon = 				Icon_Health,	
	},

	{
		Name =				"DestroyerHW2HealthUpgrade2",
		RequiredResearch =		"DestroyerHealthUpgrade2",                 -- <list of prerequisite research items>
		RequiredSubSystems =	"Research",
		Cost = 					0,
		Time = 					0,
		DisplayedName =			"$7641",
		DisplayPriority =			405,                                                    -- <display priority (used to sort on screen)>,
		Description =			"$7642",
		UpgradeType =			Modifier,
		TargetType =			Ship,
		TargetName =			"Tai_Hw2Destroyer",
		UpgradeName =			"MAXHEALTH",
		UpgradeValue =			1.6,
		Icon = 				Icon_Health,
		ShortDisplayedName = 		"$7275",
	},

	{
		Name =					"Hw2DestroyerMAXSPEEDUpgrade1",
		RequiredResearch =		"DestroyerMAXSPEEDUpgrade1",                             -- <list of prerequisite research items>
		RequiredSubSystems =	"Research",
		Cost = 					0,
		Time = 					0,
		DisplayedName =			"$7643",
		DisplayPriority =		406,                                                   -- <display priority (used to sort on screen)>,
		Description =			"<b>Description:</b> Improves Destroyer max speed by 20%",
		UpgradeType =			Modifier,
		TargetType =			Ship,
		TargetName =			"Tai_Hw2Destroyer",
		UpgradeName =			"MAXSPEED",
		UpgradeValue =			1.2,
		Icon = Icon_Speed,
		ShortDisplayedName = 		"$7274",

	},

	{
		Name =					"Hw2DestroyerMAXSPEEDUpgrade2",
		RequiredResearch =		"DestroyerMAXSPEEDUpgrade2",                  -- <list of prerequisite research items>
		RequiredSubSystems =	"Research",
		Cost = 					0,
		Time = 					0,
		DisplayedName =			"$7645",
		DisplayPriority =		406,                                                   -- <display priority (used to sort on screen)>,
		Description =			"<b>Description:</b> Improves Destroyer max speed by 12.5%",
		UpgradeType =			Modifier,
		TargetType =			Ship,
		TargetName =			"Tai_Hw2Destroyer",
		UpgradeName =			"MAXSPEED",
		UpgradeValue =			1.35,
		Icon = Icon_Speed,
		ShortDisplayedName = 		"$7275",

	},


	{
		Name =				"MissileDestroyerHW2HealthUpgrade1",
		RequiredResearch =		"MissileDestroyerHealthUpgrade1",                             -- <list of prerequisite research items>
		RequiredSubSystems =	"Research",
		Cost = 					0,
		Time = 					0,
		DisplayedName =			"$7639",
		DisplayPriority =			407,                                                    -- <display priority (used to sort on screen)>,
		Description =			"$7640",
		UpgradeType =			Modifier,
		TargetType =			Ship,
		TargetName =			"Tai_Hw2MissileDestroyer",
		UpgradeName =			"MAXHEALTH",
		UpgradeValue =			1.3,
		ShortDisplayedName = 		"$7274",
		Icon = 				Icon_Health,	
	},

	{
		Name =				"MissileDestroyerHW2HealthUpgrade2",
		RequiredResearch =		"MissileDestroyerHealthUpgrade2",                 -- <list of prerequisite research items>
		RequiredSubSystems =	"Research",
		Cost = 					0,
		Time = 					0,
		DisplayedName =			"$7641",
		DisplayPriority =			407,                                                    -- <display priority (used to sort on screen)>,
		Description =			"$7642",
		UpgradeType =			Modifier,
		TargetType =			Ship,
		TargetName =			"Tai_Hw2MissileDestroyer",
		UpgradeName =			"MAXHEALTH",
		UpgradeValue =			1.6,
		Icon = 				Icon_Health,
		ShortDisplayedName = 		"$7275",
	},

	{
		Name =					"Hw2MissileDestroyerMAXSPEEDUpgrade1",
		RequiredResearch =		"MissileDestroyerMAXSPEEDUpgrade1",                             -- <list of prerequisite research items>
		RequiredSubSystems =	"Research",
		Cost = 					0,
		Time = 				0,
		DisplayedName =			"Missile Destroyer Engine 1",
		DisplayPriority =		408,                                                   -- <display priority (used to sort on screen)>,
		Description =			"<b>Description:</b> Improves Missile Destroyer max speed by 20%",
		UpgradeType =			Modifier,
		TargetType =			Ship,
		TargetName =			"Tai_Hw2MissileDestroyer",
		UpgradeName =			"MAXSPEED",
		UpgradeValue =			1.2,
		Icon = Icon_Speed,
		ShortDisplayedName = 		"Lvl 1 Missile Destroyer",

	},

	{
		Name =					"Hw2MissileDestroyerMAXSPEEDUpgrade2",
		RequiredResearch =		"MissileDestroyerMAXSPEEDUpgrade2",                  -- <list of prerequisite research items>
		RequiredSubSystems =	"Research",
		Cost = 					0,
		Time = 					0,
		DisplayedName =			"Missile Destroyer Engine 1",
		DisplayPriority =		409,                                                   -- <display priority (used to sort on screen)>,
		Description =			"<b>Description:</b> Improves Missile Destroyer max speed by 12.5%",
		UpgradeType =			Modifier,
		TargetType =			Ship,
		TargetName =			"Tai_Hw2MissileDestroyer",
		UpgradeName =			"MAXSPEED",
		UpgradeValue =			1.35,
		Icon = Icon_Speed,
		ShortDisplayedName = 		"Lvl 2 Missile Destroyer",

	},

	
--AI behaviour 	
	{ 
		Name = "cpuplayers_defensive", 
		RequiredResearch = "", 
		RequiredSubSystems = "", 
		Cost = 1, 
		Time = 1, 
		DisplayedName = "", 
		DisplayPriority = 0,        
		Description = "",             
		TargetName = "",
	},	
	{ 
		Name = "cpuplayers_aggressive", 
		RequiredResearch = "", 
		RequiredSubSystems = "", 
		Cost = 1, 
		Time = 1, 
		DisplayedName = "", 
		DisplayPriority = 0,        
		Description = "",             
		TargetName = "",
	},	
	{ 
		Name = "cpuplayers_dynamic", 
		RequiredResearch = "", 
		RequiredSubSystems = "", 
		Cost = 1, 
		Time = 1, 
		DisplayedName = "", 
		DisplayPriority = 0,        
		Description = "",             
		TargetName = "",
	},
--AI no-rush	
	{ 
		Name = "cpuplayers_norushtime5", 
		RequiredResearch = "", 
		RequiredSubSystems = "", 
		Cost = 1, 
		Time = 1, 
		DisplayedName = "", 
		DisplayPriority = 0,        
		Description = "",             
		TargetName = "",
	},		
	{ 
		Name = "cpuplayers_norushtime10", 
		RequiredResearch = "", 
		RequiredSubSystems = "", 
		Cost = 1, 
		Time = 1, 
		DisplayedName = "", 
		DisplayPriority = 0,        
		Description = "",             
		TargetName = "",
	},		
	{ 
		Name = "cpuplayers_norushtime15", 
		RequiredResearch = "", 
		RequiredSubSystems = "", 
		Cost = 1, 
		Time = 1, 
		DisplayedName = "", 
		DisplayPriority = 0,        
		Description = "",             
		TargetName = "",
	},	
--AI build speed
	{ 
		Name =			"AllShipBuildSpeed",
		RequiredResearch =	"",                       
		RequiredSubSystems =	"",                               
		Cost = 			1,
		Time = 			1,
		DisplayedName =		"",
		DisplayPriority =	0,                                                    
		Description =		"",
		UpgradeType =		Modifier,
		TargetType =		Family,
		TargetName =		"Capital",
		UpgradeName =		"BUILDSPEED",
		UpgradeValue =		1.7,
	},	
	{ 
		Name =			"AllShipBuildSpeedHard",
		RequiredResearch =	"",                       
		RequiredSubSystems =	"",                               
		Cost = 			1,
		Time = 			1,
		DisplayedName =		"",
		DisplayPriority =	0,                                                    
		Description =		"",
		UpgradeType =		Modifier,
		TargetType =		Family,
		TargetName =		"Capital",
		UpgradeName =		"BUILDSPEED",
		UpgradeValue =		1.725,
	},	
	{ 
		Name =			"AllShipBuildSpeedExpert",
		RequiredResearch =	"",                       
		RequiredSubSystems =	"",                               
		Cost = 			1,
		Time = 			1,
		DisplayedName =		"",
		DisplayPriority =	0,                                                    
		Description =		"",
		UpgradeType =		Modifier,
		TargetType =		Family,
		TargetName =		"Capital",
		UpgradeName =		"BUILDSPEED",
		UpgradeValue =		1.75,
	},	
--AI resource rate
	{ 
		Name =			"ResourceCollectionRateHard",
		RequiredResearch =	"",                       
		RequiredSubSystems =	"",                               
		Cost = 			1,
		Time = 			1,
		DisplayedName =		"",
		DisplayPriority =	0,                                                    
		Description =		"",
		UpgradeType =		Modifier,
		TargetType =		Ship,
		TargetName = "tai_resourcecollector",
		UpgradeName =		"ResourceCollectionRate",
		UpgradeValue =		1.04,
	},	
	{ 
		Name =			"ResourceCollectionRateExpert",
		RequiredResearch =	"",                       
		RequiredSubSystems =	"",                               
		Cost = 			1,
		Time = 			1,
		DisplayedName =		"",
		DisplayPriority =	0,                                                    
		Description =		"",
		UpgradeType =		Modifier,
		TargetType =		Ship,
		TargetName = "tai_resourcecollector",
		UpgradeName =		"ResourceCollectionRate",
		UpgradeValue =		1.08,
	},	
	--Special		
	{ 
		Name =			"MissileDestroyerVolley",
		RequiredResearch =	"",
		RequiredSubSystems =	"",
		Cost = 			1,
		Time = 			1,
		DisplayedName =		"",
		DisplayPriority =	0,
		Description =		"",
		UpgradeType =		Ability,
		TargetType =		Ship,
		TargetName =		"Tai_MissileDestroyer",
		UpgradeName =		"UseSpecialWeaponsInNormalAttack",		
	},
	{ 
		Name =			"HeavyCorvetteAttackBurst",
		RequiredResearch =	"",
		RequiredSubSystems =	"Research",
		Cost = 			1,
		Time = 			1,
		DisplayedName =		"",
		DisplayPriority =	0,
		Description =		"",
		UpgradeType =		Ability,
		TargetType =		Ship,
		TargetName =		"Tai_HeavyCorvette",
		UpgradeName =		"UseSpecialWeaponsInNormalAttack",		
	},		
}