Ship = 0
SubSystem = 1
build =
{
	----------------------------------------
-- Turanic Raiders --
----------------------------------------
	{
		Type = Ship,
		ThingToBuild = "Tur_Scout",
		RequiredResearch = "",
		RequiredShipSubSystems = "",
		DisplayPriority = 210,
		DisplayedName = "Scout",
		Description = "<b>Description:</b> Scout ship with limited firepower.  \n\n<b>Strong Vs:</b> None \n\n<b>Prerequisites:</b> None",
	},
	{
		Type = Ship,
		ThingToBuild = "tur_fighter",
		RequiredResearch = "PRTFighterChassis",
		RequiredShipSubSystems = "",
		DisplayPriority = 211,
		DisplayedName = "Bandit",
		Description = "<b>Description:</b> Small strike craft designed to take down enemy fighters and corvettes.  \n\n<b>Strong Vs:</b> Fighters & Corvettes \n\n<b>Prerequisites:</b> PrtFighterDrive & FighterChassis",
	},
	{
		Type = Ship,
		ThingToBuild = "Tur_attackbomber",
		RequiredResearch = "PRTPlasmaBombLauncher",
		RequiredShipSubSystems = "",
		DisplayPriority = 213,
		DisplayedName = "Attack Bomber",
		Description = "<b>Description:</b> Fighter Equipped with Anti Frigate and Anti Capital Weapons\n\n<b>Strong Vs:</b> Frigates, Subsystems & Capital Ships \n\n<b>Weak Vs:</b> Flak Frigates, Destroyers & Battlecruisers \n\n<b>Prerequisites:</b> FighterChassis & PlasmaBombLauncher",
	},
	{
		Type = Ship,
		ThingToBuild = "Tur_Researchship",
		RequiredResearch = "",
		RequiredShipSubSystems = "",
		DisplayPriority = 60,
		DisplayedName = "Research Ship",
		Description = "<b>Description:</b> Allows research of all types. \n\n<b>Strong Vs:</b> None \n\n<b>Weak Vs:</b> Most \n\n<b>Prerequisites:</b> None",
	},
	{
		Type = Ship,
		ThingToBuild = "Tur_Gravwellgenerator",
		RequiredResearch = "PRTGravityGenerator",
        RequiredShipSubSystems = "",
		DisplayPriority = 61,
		DisplayedName = "Gravity Well Generator",
		Description = "<b>Description:</b> Portable Gravity Well Generator, currently prevents enemy ships from Hyperspacing into a limited radius around itself.  \n\n<b>Strong Vs:</b> None \n\n<b>Weak Vs:</b> All \n\n<b>Prerequisites:</b> PRTCapitalShipDrive & Gravity Generator",
	},
	{
		Type = Ship,
		ThingToBuild = "Tur_ionarrayfrigate",
		RequiredResearch = "PRTIonCannons",
		RequiredShipSubSystems = "",
		DisplayPriority = 62,
		DisplayedName = "Ion Array Frigate",
		Description = "<b>Description:</b> Another resurrected derelict ship of the Turanic arsenal featuring a Ion Array Cannon as it's only weapon. \n\n<b>Strong Vs:</b> Undecided \n\n<b>Prerequisites:</b> Capital Ship Chassis & Ion Cannons",
	},
	{
		Type = Ship,
		ThingToBuild = "Tur_StandardFrigate",
		RequiredResearch = "PRTCapitalShipChassis",
		RequiredShipSubSystems = "",
		DisplayPriority = 63,
		DisplayedName = "Assault Frigate",
		Description = "<b>Description:</b> Assault Frigate used to defend against swarms of Fighters & Corvettes.  \n\n<b>Strong Vs:</b> Fighters & Corvettes \n\n<b>Weak Vs:</b> Capital Ships \n\n<b>Prerequisites:</b> Capital Ship Drive & Capital Ship Chassis",
	},
	{
		Type = Ship,
		ThingToBuild = "Tur_plasmafrigate",
		RequiredResearch = "PRTQuadPlasma",
		RequiredShipSubSystems = "",
		DisplayPriority = 64,
		DisplayedName = "PlasmaFrigate",
		Description = "<b>Description:</b> Frigate armed with 4 forward plasma launchers Effective against Corvettes and Frigates.  \n\n<b>Strong Vs:</b> Corvettes & Frigates \n\n<b>Weak Vs:</b> Capital Ships \n\n<b>Prerequisites:</b> Capital Ship Chassis & Quad Plasma Launcher",
	},
	{
		Type = Ship,
		ThingToBuild = "Tur_supportfrigate",
		RequiredResearch = "PRTCapitalShipDrive",
		RequiredShipSubSystems = "",
		DisplayPriority = 65,
		DisplayedName = "SupportFrigate",
		Description = "<b>Description:</b> Frigate designed to speed up Regeneration Rate.  \n\n<b>Strong Vs:</b> \n\n<b>Weak Vs:</b> Capital Ships \n\n<b>Prerequisites:</b> Capital Ship Drive",
	},
	{
		Type = Ship,
		ThingToBuild = "Tur_missilecorvette",
		RequiredResearch = "PRTHeavyCorvetteUpgrade",
		RequiredShipSubSystems = "",
		DisplayPriority = 50,
		DisplayedName = "Missile Corvette",
		Description = "<b>Description:</b> Comparable to the Vaygr version in weapons and armor \n\n<b>Strong Vs:</b>Undecided \n\n<b>Prerequisites:</b> Corvette Chassis & Missile Corvette Launchers",
	},
	{
		Type = Ship,
		ThingToBuild = "tur_standardcorvette",
		RequiredResearch = "PRTCorvetteDrive",
		RequiredShipSubSystems = "",
		DisplayPriority = 51,
		DisplayedName = "General Corvette",
		Description = "<b>Description:</b> All use corvette \n\n<b>Strong Vs:</b> Fighters \n\n<b>Prerequisites:</b> Corvette Drive",
	},
	{
		Type = Ship,
		ThingToBuild = "tur_repaircorvette",
		RequiredResearch = "PrtCorvetteDrive",
		RequiredShipSubSystems = "",
		DisplayPriority = 56,
		DisplayedName = "Repair Corvette",
		Description = "<b>Description:</b> Corvette used to repair frigates and caps in the field",	
	},
	{
		Type = Ship,
		ThingToBuild = "Tur_SalvageCorvette",
		RequiredResearch = "PRTCorvetteChassis",
		RequiredShipSubSystems = "",
		DisplayPriority = 52,
		DisplayedName = "Salvage Corvette",
		Description = "<b>Description:</b> Corvette designed to capture enemy ships\n\n<b>Strong Vs:</b>Frigates and Capital Ships \n\n<b>Prerequisites:</b> Corvette Drive & Corvette Chassis",
	},
	{
		Type = Ship,
		ThingToBuild = "Tur_MinelayerCorvette",
		RequiredResearch = "PRTMineLayingTech",
		RequiredShipSubSystems = "",
		DisplayPriority = 53,
		DisplayedName = "Minelayer Corvette",
		Description = "<b>Description:</b> Corvette designed to Create Minefields\n\n<b>Strong Vs:</b>Frigates and Capital Ships \n\n<b>Prerequisites:</b> Corvette Chassis & MineLayingTech",
	},
	{
		Type = Ship,
		ThingToBuild = "Tur_salvagecollector",
		RequiredResearch = "",
		RequiredShipSubSystems = "",
		DisplayPriority = 140,
		DisplayedName = "Resource Collector",
		Description = "<b>Description:</b> Vessel Designed to collect Resources and deliver them to be converted at a receiving station. \n\n<b>Strong Vs:</b> None \n\n<b>Prerequisites:</b> None",
	},
	{
		Type = Ship,
		ThingToBuild = "Tur_resourcecontroller",
		RequiredResearch = "",
		RequiredShipSubSystems = "",
		DisplayPriority = 145,
		DisplayedName = "Resource Controller",
		Description = "<b>Description:</b> Turanic Resource Controller. \n\n<b>Strong Vs:</b> None \n\n<b>Prerequisites:</b> None",
	},
	{
		Type = Ship,
		ThingToBuild = "Tur_probe",
		RequiredResearch = "",
		RequiredShipSubSystems = "",
		DisplayPriority = 146,
		DisplayedName = "Probe",
		Description = "<b>Description:</b> Single Shot probe. \n\n<b>Strong Vs:</b> None \n\n<b>Prerequisites:</b> None",
	},
	{
		Type = Ship,
		ThingToBuild = "Tur_proximitysensor",
		RequiredResearch = "PrtSensDisProbe",
		RequiredShipSubSystems = "",
		DisplayPriority = 147,
		DisplayedName = "ProximitySensor",
		Description = "<b>Description:</b> Utility ship designed to detect cloaked ships. \n\n<b>Strong Vs:</b> None \n\n<b>Prerequisites:</b> Proximity Sensor",
	},
	{
		Type = Ship,
		ThingToBuild = "tur_autogunl",
		RequiredResearch = "Prtlargejunkgun",
		RequiredShipSubSystems = "",
		DisplayPriority = 62,
		DisplayedName = "Large Auto Gun",
		Description = "<b>Description:</b> Large stationary automatic weapon, useful for protecting base territories. \n\n<b>Strong Vs:</b> Undecided \n\n<b>Prerequisites:</b> Smalljunkgun & largejunkgun",
	},
	{
		Type = Ship,
		ThingToBuild = "tur_autoguns",
		RequiredResearch = "PrtSmalljunkgun",
		RequiredShipSubSystems = "",
		DisplayPriority = 63,
		DisplayedName = "Small Auto Gun",
		Description = "<b>Description:</b> Small stationary automatic weapon, useful for protecting base territories. \n\n<b>Strong Vs:</b> Undecided \n\n<b>Prerequisites:</b> Capital Ship Drive & Smalljunkgun",
	},
	{
		Type = Ship,
		ThingToBuild = "Tur_carrier",
		RequiredResearch = "PRTSuperHeavyChassis",
		RequiredShipSubSystems = "",
		DisplayPriority = 120,
		DisplayedName = "Carrier",
		Description = "<b>Description:</b> Found derelict  \n\n<b>Strong Vs:</b> Undecided \n\n<b>Prerequisites:</b> Super Capital Ship Drive & Super-Heavy Chassis",
	},
	{
		Type = Ship,
		ThingToBuild = "Tur_destroyer",
		RequiredResearch = "PRTSuperCapitalShipDrive & PRTIonCannons",
		RequiredShipSubSystems = "",
		DisplayPriority = 125,
		DisplayedName = "Destroyer",
		Description = "<b>Description:</b> Destroyer Armed with Triple Ion Cannons and 2 PDS guns.  \n\n<b>Strong Vs:</b> Most \n\n<b>Weak Vs:</b> Battlecruisers \n\n<b>Prerequisites:</b> Super Capital Ship Drive & Ion Cannons",
	},
	{
		Type = Ship,
		ThingToBuild = "Tur_MissileDestroyer",
		RequiredResearch = "PRTGuidedMissiles",
		RequiredShipSubSystems = "",
		DisplayPriority = 126,
		DisplayedName = "Missile Destroyer",
		Description = "<b>Description:</b> Destroyer Armed with Dual Ion cannons, 4 anti fighter and corvette missiles and 4 PDS guns.  \n\n<b>Strong Vs:</b> Most \n\n<b>Weak Vs:</b> Battlecruisers \n\n<b>Prerequisites:</b> Super Capital Ship Drive & Guided Missiles",
	},
	{
		Type = Ship,
		ThingToBuild = "Tur_Outpost",
		RequiredResearch = "PRThyperspaceTech",
		RequiredShipSubSystems = "",
		DisplayPriority = 115,
		DisplayedName = "Outpost",
		Description = "<b>Description:</b> Found derelict & resurrected.  \n\n<b>Strong Vs:</b> Undecided \n\n<b>Prerequisites:</b> Capital Ship Drive & hyperspaceTech",
	},
	{
		Type = Ship,
		ThingToBuild = "Tur_Heavycruiser",
		RequiredResearch = "PRTHeavyGuns",
		RequiredShipSubSystems = "",
		DisplayPriority = 135,
		DisplayedName = "Heavy Cruiser",
		Description = "<b>Description:</b> Cruiser armed with 4 forward ion cannons, 2 side ion cannons and 5 PDS guns.  \n\n<b>Strong Vs:</b> Most \n\n<b>Weak Vs:</b> Battlecruisers \n\n<b>Prerequisites:</b> Super-Heavy Chassis & Heavy Guns",
	},

}

