Ship = 0
SubSystem = 1
build = {
    { 
        Type = Ship, 
        ThingToBuild = "kad_ambassador", 
        DisplayPriority = 1, 
        DisplayedName = "Ambassador", 
        Description = "$7031", 
    }, 
    { 
        Type = Ship, 
        ThingToBuild = "kad_swarmer", 
		RequiredResearch =		"FighterProduction",
		RequiredShipSubSystems =	"",
        DisplayPriority = 2, 
        DisplayedName = "$10076", 
        Description = "$10077", 
    }, 
    { 
        Type = Ship, 
        ThingToBuild = "kad_advancedswarmer",
		RequiredResearch =		"AdvancedSwarmerUpgrade",
		RequiredShipSubSystems =	"",
        DisplayPriority = 10,
        DisplayedName = "$10078",
        Description = "$10079", 
    },
    { 
        Type = Ship, 
        ThingToBuild = "kad_fuelpod", 
        DisplayPriority = 20, 
        DisplayedName = "$10084", 
        Description = "$10085", 
    }, 
    { 
        Type = Ship, 
        ThingToBuild = "kad_multibeamfrigate", 
		RequiredResearch =		"FrigateProduction",
		RequiredShipSubSystems =	"",
        DisplayPriority = 23, 
        DisplayedName = "$10080", 
        Description = "$10081", 
    }, 
     { 
        Type = Ship, 
        ThingToBuild = "kad_p2mothership", 
		RequiredResearch =		"CapitalProduction",
		RequiredShipSubSystems =	"",
        DisplayPriority = 55, 
        DisplayedName = "$10042", 
        Description = "$10043", 
    },
    { 
        Type = Ship, 
        ThingToBuild = "kad_Hw2multibeamfrigate", 
		RequiredResearch =		"FrigateProduction",
		RequiredShipSubSystems =	"",
        DisplayPriority = 23, 
        DisplayedName = "$10080", 
        Description = "$10081", 
    }, 
    { 
        Type = Ship, 
        ThingToBuild = "kad_utilityswarmer",
        DisplayPriority = 61,
        DisplayedName = "Utility Swarmer",
        Description = "$7067", 
    },

}