Icon_Speed = "data:ui/newui/research/icons/speed.mres"
Icon_Health = "data:ui/newui/research/icons/health.mres"
Icon_Tech = "data:ui/newui/research/icons/tech.mres"
Icon_Ability = "data:ui/newui/research/icons/ability.mres"
Icon_Build = "data:ui/newui/research/icons/build.mres"
Modifier = 0
Ability = 1
AllShips = 0
Family = 1
Ship = 2
research =
  {
	{
		Name =			"FighterProduction",
		RequiredResearch =	"",
		RequiredSubSystems =	"",
		Cost = 			800,
		Time = 			260, --60
		DisplayedName =		"$7000",
		ShortDisplayedName =	"Swarmer Production",
		DisplayPriority =		11,
		Description =		"Swarmer Production",
		Icon = 			Icon_Build,
		TargetName =		"Kad_Swarmer",
	},
	{
		Name =			"AdvancedSwarmerUpgrade",
		RequiredResearch =	"CorvetteProduction",
		RequiredSubSystems =	"",
		Cost = 			900,
		Time = 			320, --65
		DisplayedName =		"$11518",
		ShortDisplayedName =	"Advanced Upgrade",
		DisplayPriority =		12,
		Description =		"$11519",
		Icon = 			Icon_Build,
		TargetName =		"Kad_AdvancedSwarmer",
	},
	{
		Name =			"FrigateProduction",
		RequiredResearch =	"",
		RequiredSubSystems =	"",
		Cost = 			2000,
		Time = 			600, --100
		DisplayedName =		"$7004",
		ShortDisplayedName =	"Frigate Production",
		DisplayPriority =		31,
		Description =		"$7005",
		Icon = 			Icon_Build,
		TargetName =		"Kad_MultibeamFrigate",
	},
	{
		Name =			"CapitalProduction",
		RequiredResearch =	"",
		RequiredSubSystems =	"",
		Cost = 			2000,
		Time = 			600, --80
		DisplayedName =		"$7006",
		ShortDisplayedName =	"Capital Reinforcements",
		DisplayPriority =		41,
		Description =		"$7007",
		Icon = 			Icon_Build,
		TargetName =		"Kad_P2Mothership",
	},
	{
		Name =				"Hyperspace",
		RequiredResearch =		"",
		RequiredSubSystems =		"",
		Cost = 				3000,
		Time = 				800,
		DisplayedName =			"Hyperspace",
		DisplayPriority =		90,
		Description =			"Enables Hyperspace",
		UpgradeType =			Ability,
		TargetType =			AllShips,
		TargetName =			"Kad_P2Mothership",
	        UpgradeName =			"HyperSpace",
		Icon = Icon_Hyperspace,
		ShortDisplayedName = "Hyperspace",
	},
{
    Name = "NeedleshipBUILDSPEED",
    RequiredResearch = "",
    RequiredSubSystems = "",
    Cost = 0,
    Time = 0,
    DisplayedName = "$7800",
    DisplayPriority = 45,
    Description = "$7801",
    UpgradeType = Modifier,
    TargetType = Ship,
    TargetName = "Kad_p2MotherShip",
    UpgradeName = "BUILDSPEED",
    UpgradeValue = 1,
    Icon = Icon_Build,
    ShortDisplayedName = "Motheship Production",
  },

	{
		Name =					"MultibeamFrigateHealthUpgrade1",
		RequiredResearch =		"FrigateProduction",                                         -- <list of prerequisite research items>
		RequiredSubSystems =	"",
		Cost = 					800,
		Time = 					60,
		DisplayedName =			"Multibeam Frigate Armor 1",
		DisplayPriority =		306,                                                    -- <display priority (used to sort on screen)>,
		Description =			"<b>Description:</b> Improves Multibeam Frigate armor by 30%",
		UpgradeType =			Modifier,
		TargetType =			Ship,
		TargetName =			"Kad_MultibeamFrigate",
        UpgradeName =			"MAXHEALTH",
        UpgradeValue =			1.3,
		Icon = Icon_Health,
		ShortDisplayedName = "Lvl 1 Multibeam Frigate",
	},

	{
		Name =					"MultibeamFrigateHealthUpgrade2",
		RequiredResearch =		"MultibeamFrigateHealthUpgrade1",     -- <list of prerequisite research items>
		RequiredSubSystems =	"",
		Cost = 					1400,
		Time = 					75,
		DisplayedName =			"Multibeam Frigate Armor 2",
		DisplayPriority =		306,                                                    -- <display priority (used to sort on screen)>,
		Description =			"<b>Description:</b> Improves Multibeam Frigate armor by 23%",
		UpgradeType =			Modifier,
		TargetType =			Ship,
		TargetName =			"Kad_MultibeamFrigate",
        UpgradeName =			"MAXHEALTH",
        UpgradeValue =			1.6,
		Icon = Icon_Health,
		ShortDisplayedName = "Lvl 2 Multibeam Frigate",
	},

	{
		Name =					"MultibeamFrigateMAXSPEEDUpgrade1",
		RequiredResearch =		"FrigateProduction",                                         -- <list of prerequisite research items>
		RequiredSubSystems =	"",
		Cost = 					500,
		Time = 					50,
		DisplayedName =			"Multibeam Frigate Engine 1",
		DisplayPriority =		309,                                                    -- <display priority (used to sort on screen)>,
		Description =			"<b>Description:</b> Improves Multibeam Frigate max speed by 20%",
		UpgradeType =			Modifier,
		TargetType =			Ship,
		TargetName =			"Kad_MultibeamFrigate",
        UpgradeName =			"MAXSPEED",
        UpgradeValue =			1.2,
		Icon = Icon_Speed,
		ShortDisplayedName = "Lvl 1 Multibeam Frigate",

	},

	{
		Name =					"MultibeamFrigateMAXSPEEDUpgrade2",
		RequiredResearch =		"MultibeamFrigateMAXSPEEDUpgrade1",     -- <list of prerequisite research items>
		RequiredSubSystems =	"",
		Cost = 					750,
		Time = 					70,
		DisplayedName =			"Multibeam Frigate Engine 2",
		DisplayPriority =		309,                                                   -- <display priority (used to sort on screen)>,
		Description =			"<b>Description:</b> Improves Multibeam Frigate max speed by 12.5%",
		UpgradeType =			Modifier,
		TargetType =			Ship,
		TargetName =			"Kad_MultibeamFrigate",
        UpgradeName =			"MAXSPEED",
        UpgradeValue =			1.35,
		Icon = Icon_Speed,
		ShortDisplayedName = "Lvl 2 Multibeam Frigate",

	},

	{
		Name =					"Hw2MultibeamFrigateHealthUpgrade1",
		RequiredResearch =		"MultibeamFrigateHealthUpgrade1",                                         -- <list of prerequisite research items>
		RequiredSubSystems =	"",
		Cost = 					0,
		Time = 					0,
		DisplayedName =			"$7579",
		DisplayPriority =		306,                                                    -- <display priority (used to sort on screen)>,
		Description =			"$7580",
		UpgradeType =			Modifier,
		TargetType =			Ship,
		TargetName =			"Kad_Hw2MultibeamFrigate",
        UpgradeName =			"MAXHEALTH",
        UpgradeValue =			1.3,
		Icon = Icon_Health,
	ShortDisplayedName = "$7247",
	},

	{
		Name =					"Hw2MultibeamFrigateHealthUpgrade2",
		RequiredResearch =		"MultibeamFrigateHealthUpgrade2",     -- <list of prerequisite research items>
		RequiredSubSystems =	"",
		Cost = 					0,
		Time = 					0,
		DisplayedName =			"$7581",
		DisplayPriority =		306,                                                    -- <display priority (used to sort on screen)>,
		Description =			"$7582",
		UpgradeType =			Modifier,
		TargetType =			Ship,
		TargetName =			"Kad_Hw2MultibeamFrigate",
        UpgradeName =			"MAXHEALTH",
        UpgradeValue =			1.6,
		Icon = Icon_Health,
	ShortDisplayedName = "$7248",
	},

	{
		Name =					"Hw2MultibeamFrigateMAXSPEEDUpgrade1",
		RequiredResearch =		"MultibeamFrigateMAXSPEEDUpgrade1",                                         -- <list of prerequisite research items>
		RequiredSubSystems =	"",
		Cost = 					0,
		Time = 					0,
		DisplayedName =			"$7583",
		DisplayPriority =		309,                                                    -- <display priority (used to sort on screen)>,
		Description =			"$7584",
		UpgradeType =			Modifier,
		TargetType =			Ship,
		TargetName =			"Kad_Hw2MultibeamFrigate",
        UpgradeName =			"MAXSPEED",
        UpgradeValue =			1.2,
		Icon = Icon_Speed,
	ShortDisplayedName = "$7247",

	},

	{
		Name =					"Hw2MultibeamFrigateMAXSPEEDUpgrade2",
		RequiredResearch =		"MultibeamFrigateMAXSPEEDUpgrade2",     -- <list of prerequisite research items>
		RequiredSubSystems =	"",
		Cost = 					0,
		Time = 					0,
		DisplayedName =			"$7585",
		DisplayPriority =		309,                                                   -- <display priority (used to sort on screen)>,
		Description =			"$7586",
		UpgradeType =			Modifier,
		TargetType =			Ship,
		TargetName =			"Kad_Hw2MultibeamFrigate",
        UpgradeName =			"MAXSPEED",
        UpgradeValue =			1.35,
		Icon = Icon_Speed,
	ShortDisplayedName = "$7248",

	},

	{
		Name =					"P2MothershipHealthUpgrade1",
		RequiredResearch =		"",                             -- <list of prerequisite research items>
		RequiredSubSystems =	"",
		Cost = 					2000,
		Time = 					60,
		DisplayedName =			"Mothership Armor 1",
		DisplayPriority =		401,                                                    -- <display priority (used to sort on screen)>,
		Description =			"<b>Description:</b> Improves Mothership armor by 30%",
		UpgradeType =			Modifier,
		TargetType =			Ship,
		TargetName =			"Kad_P2Mothership",
		UpgradeName =			"MAXHEALTH",
		UpgradeValue =			1.3,
		Icon = Icon_Health,
		ShortDisplayedName = 		"Lvl 1 Mothership",
	},

	{
		Name =					"P2MothershipHealthUpgrade2",
		RequiredResearch =		"P2MothershipHealthUpgrade1",                 -- <list of prerequisite research items>
		RequiredSubSystems =	"",
		Cost = 					3000,
		Time = 					75,
		DisplayedName =			"Mothership Armor 1",
		DisplayPriority =		401,                                                    -- <display priority (used to sort on screen)>,
		Description =			"<b>Description:</b> Improves Mothership armor by 23%",
		UpgradeType =			Modifier,
		TargetType =			Ship,
		TargetName =			"Kad_P2Mothership",
		UpgradeName =			"MAXHEALTH",
		UpgradeValue =			1.6,
		Icon = Icon_Health,
		ShortDisplayedName = 		"Lvl 2 Mothership",
	},

	{
		Name =					"P2MothershipMAXSPEEDUpgrade1",
		RequiredResearch =		"CapitalProduction",                             -- <list of prerequisite research items>
		RequiredSubSystems =	"",
		Cost = 					1000,
		Time = 					30,
		DisplayedName =			"Mothership Engine 1",
		DisplayPriority =		404,                                                   -- <display priority (used to sort on screen)>,
		Description =			"<b>Description:</b> Improves Mothership max speed by 20%",
		UpgradeType =			Modifier,
		TargetType =			Ship,
		TargetName =			"Kad_P2Mothership",
		UpgradeName =			"MAXSPEED",
		UpgradeValue =			1.2,
		Icon = Icon_Speed,
		ShortDisplayedName = 		"Lvl 1 Mothership",

	},

	{
		Name =					"Hw2P2MothershipMAXSPEEDUpgrade2",
		RequiredResearch =		"P2MothershipMAXSPEEDUpgrade1",                  -- <list of prerequisite research items>
		RequiredSubSystems =	"",
		Cost = 					1500,
		Time = 					40,
		DisplayedName =			"Mothership Engine 1",
		DisplayPriority =		404,                                                   -- <display priority (used to sort on screen)>,
		Description =			"<b>Description:</b> Improves Mothership max speed by 12.5%",
		UpgradeType =			Modifier,
		TargetType =			Ship,
		TargetName =			"Kad_P2Mothership",
		UpgradeName =			"MAXSPEED",
		UpgradeValue =			1.35,
		Icon = Icon_Speed,
		ShortDisplayedName = 		"Lvl 2 Mothership",

	},
	
	{
		Name =					"Hw2P2MothershipHealthUpgrade1",
		RequiredResearch =		"P2MothershipHealthUpgrade1",                             -- <list of prerequisite research items>
		RequiredSubSystems =	"",
		Cost = 					0,
		Time = 					0,
		DisplayedName =			"$7595",
		DisplayPriority =		401,                                                    -- <display priority (used to sort on screen)>,
		Description =			"$7596",
		UpgradeType =			Modifier,
		TargetType =			Ship,
		TargetName =			"Kad_Hw2P2Mothership",
		UpgradeName =			"MAXHEALTH",
		UpgradeValue =			1.3,
		Icon = Icon_Health,
		ShortDisplayedName = "$7254",
	},

	{
		Name =					"Hw2P2MothershipHealthUpgrade2",
		RequiredResearch =		"P2MothershipHealthUpgrade2",                 -- <list of prerequisite research items>
		RequiredSubSystems =	"",
		Cost = 					0,
		Time = 					0,
		DisplayedName =			"$7597",
		DisplayPriority =		401,                                                    -- <display priority (used to sort on screen)>,
		Description =			"$7598",
		UpgradeType =			Modifier,
		TargetType =			Ship,
		TargetName =			"Kad_Hw2P2Mothership",
		UpgradeName =			"MAXHEALTH",
		UpgradeValue =			1.6,
		Icon = Icon_Health,
		ShortDisplayedName = "$7255",
	},
	
	{
		Name =					"Hw2P2MothershipMAXSPEEDUpgrade1",
		RequiredResearch =		"P2MothershipMAXSPEEDUpgrade1",                             -- <list of prerequisite research items>
		RequiredSubSystems =	"",
		Cost = 					0,
		Time = 					0,
		DisplayedName =			"Mothership Engine 1",
		DisplayPriority =		404,                                                   -- <display priority (used to sort on screen)>,
		Description =			"<b>Description:</b> Improves Mothership max speed by 20%",
		UpgradeType =			Modifier,
		TargetType =			Ship,
		TargetName =			"Kad_Hw2P2Mothership",
		UpgradeName =			"MAXSPEED",
		UpgradeValue =			1.2,
		Icon = Icon_Speed,
		ShortDisplayedName = 		"Lvl 1 Mothership",

	},

	{
		Name =					"Hw2P2MothershipMAXSPEEDUpgrade2",
		RequiredResearch =		"P2MothershipMAXSPEEDUpgrade2",                  -- <list of prerequisite research items>
		RequiredSubSystems =	"",
		Cost = 					0,
		Time = 					0,
		DisplayedName =			"Mothership Engine 1",
		DisplayPriority =		404,                                                   -- <display priority (used to sort on screen)>,
		Description =			"<b>Description:</b> Improves Mothership max speed by 12.5%",
		UpgradeType =			Modifier,
		TargetType =			Ship,
		TargetName =			"Kad_Hw2P2Mothership",
		UpgradeName =			"MAXSPEED",
		UpgradeValue =			1.35,
		Icon = Icon_Speed,
		ShortDisplayedName = 		"Lvl 2 Mothership",

	},

--AI behaviour 	
	{ 
		Name = "cpuplayers_defensive", 
		RequiredResearch = "", 
		RequiredSubSystems = "", 
		Cost = 1, 
		Time = 1, 
		DisplayedName = "", 
		DisplayPriority = 0,        
		Description = "",             
		TargetName = "",
	},	
	{ 
		Name = "cpuplayers_aggressive", 
		RequiredResearch = "", 
		RequiredSubSystems = "", 
		Cost = 1, 
		Time = 1, 
		DisplayedName = "", 
		DisplayPriority = 0,        
		Description = "",             
		TargetName = "",
	},	
	{ 
		Name = "cpuplayers_dynamic", 
		RequiredResearch = "", 
		RequiredSubSystems = "", 
		Cost = 1, 
		Time = 1, 
		DisplayedName = "", 
		DisplayPriority = 0,        
		Description = "",             
		TargetName = "",
	},
--AI no-rush	
	{ 
		Name = "cpuplayers_norushtime5", 
		RequiredResearch = "", 
		RequiredSubSystems = "", 
		Cost = 1, 
		Time = 1, 
		DisplayedName = "", 
		DisplayPriority = 0,        
		Description = "",             
		TargetName = "",
	},		
	{ 
		Name = "cpuplayers_norushtime10", 
		RequiredResearch = "", 
		RequiredSubSystems = "", 
		Cost = 1, 
		Time = 1, 
		DisplayedName = "", 
		DisplayPriority = 0,        
		Description = "",             
		TargetName = "",
	},		
	{ 
		Name = "cpuplayers_norushtime15", 
		RequiredResearch = "", 
		RequiredSubSystems = "", 
		Cost = 1, 
		Time = 1, 
		DisplayedName = "", 
		DisplayPriority = 0,        
		Description = "",             
		TargetName = "",
	},	
--AI build speed
	{ 
		Name =			"AllShipBuildSpeed",
		RequiredResearch =	"",                       
		RequiredSubSystems =	"",                               
		Cost = 			1,
		Time = 			1,
		DisplayedName =		"",
		DisplayPriority =	0,                                                    
		Description =		"",
		UpgradeType =		Modifier,
		TargetType =		Family,
		TargetName =		"Capital",
		UpgradeName =		"BUILDSPEED",
		UpgradeValue =		1.7,
	},	
	{ 
		Name =			"AllShipBuildSpeedHard",
		RequiredResearch =	"",                       
		RequiredSubSystems =	"",                               
		Cost = 			1,
		Time = 			1,
		DisplayedName =		"",
		DisplayPriority =	0,                                                    
		Description =		"",
		UpgradeType =		Modifier,
		TargetType =		Family,
		TargetName =		"Capital",
		UpgradeName =		"BUILDSPEED",
		UpgradeValue =		1.725,
	},	
	{ 
		Name =			"AllShipBuildSpeedExpert",
		RequiredResearch =	"",                       
		RequiredSubSystems =	"",                               
		Cost = 			1,
		Time = 			1,
		DisplayedName =		"",
		DisplayPriority =	0,                                                    
		Description =		"",
		UpgradeType =		Modifier,
		TargetType =		Family,
		TargetName =		"Capital",
		UpgradeName =		"BUILDSPEED",
		UpgradeValue =		1.75,
	},	
--AI resource rate
	{ 
		Name =			"ResourceCollectionRateHard",
		RequiredResearch =	"",                       
		RequiredSubSystems =	"",                               
		Cost = 			1,
		Time = 			1,
		DisplayedName =		"",
		DisplayPriority =	0,                                                    
		Description =		"",
		UpgradeType =		Modifier,
		TargetType =		Ship,
		TargetName = "tai_resourcecollector",
		UpgradeName =		"ResourceCollectionRate",
		UpgradeValue =		1.04,
	},	
	{ 
		Name =			"ResourceCollectionRateExpert",
		RequiredResearch =	"",                       
		RequiredSubSystems =	"",                               
		Cost = 			1,
		Time = 			1,
		DisplayedName =		"",
		DisplayPriority =	0,                                                    
		Description =		"",
		UpgradeType =		Modifier,
		TargetType =		Ship,
		TargetName = "tai_resourcecollector",
		UpgradeName =		"ResourceCollectionRate",
		UpgradeValue =		1.08,
	},	

}