-- Cold Fusion LUA Decompiler v1.0.0
-- By 4E534B
-- Date: 08-31-2012 Time: 09:39:46
-- On error(s), send source (compiled) file to 4E534B@gmail.com

AttackStyleName=AttackRun;
Data={howToBreakFormation=StraightAndScatter,
maxBreakDistance=2438,
distanceFromTargetToBreak=914,
safeDistanceFromTargetToDoActions=914, --1828
useTargetUp=0,
coordSysToUse=TargetPoint,
horizontalMin=0,
horizontalMax=1,
horizontalFlip=1,
verticalMin=0,
verticalMax=1,
verticalFlip=1,
RandomActions={{Type=PickNewTarget,
Weighting=1},
	{Type=NoAction,
Weighting=30},
	{Type=FlightManeuver,
Weighting=1,
FlightManeuverName="HW1WingWaggle"}},

BeingAttackedActions={{Type=FlightManeuver,
Weighting=6,
FlightManeuverName="HW1JinkLeft"},
	{Type=FlightManeuver,
Weighting=6,
FlightManeuverName="HW1JinkRight"},
	{Type=FlightManeuver,
Weighting=0,
FlightManeuverName="HW1Slalom"},
	{Type=FlightManeuver,
Weighting=18,
FlightManeuverName="HW1Split_S"},
	{Type=FlightManeuver,
Weighting=13,
FlightManeuverName="HW1Cobra"},
	{Type=PickNewTarget,
Weighting=8},
	{Type=FlightManeuver,
Weighting=6,
FlightManeuverName="HW1NinetyDegRightTurn"},
	{Type=FlightManeuver,
Weighting=6,
FlightManeuverName="HW1NinetyDegLeftTurn"},
	{Type=FlightManeuver,
Weighting=6,
FlightManeuverName="HW1JinkLeftAndBack"},
	{Type=FlightManeuver,
Weighting=6,
FlightManeuverName="HW1JinkRightAndBack"}},
FiringActions={{Type=FlightManeuver,
Weighting=10,
FlightManeuverName="HW1BarrelRoll"},

{Type=NoAction,
Weighting=1}}};

